### ISSUE TITLE
'UserWarning: Version mistmatch between Java ZMQ server and Python client.' with pycro-manager version 0.4.5

### ISSUE THREAD

**Issue by BinYangOptics** [micro-manager/pycro-manager#100]
Hi,

I got the warning 'UserWarning: Version mistmatch between Java ZMQ server and Python client.  Java ZMQ server version: 2.5.0
Python client expected version: 2.6.0'.

This happened with the updated pycro-manager version 0.4.5 but not with an older version 0.3.6.

**Comment by henrypinkard** [comment]
This means you have to update to the latest micro-manager nighly build in addition to pycromanager 0.4.5. I added an better error message to clarify this in the future
