### ISSUE TITLE
Bridge.get_studio  raises exception

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#11]
Here is the traceback:
```
Traceback (most recent call last):
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 459, in <module>
    s = b.get_studio()
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 205, in get_studio
    return self.construct_java_object('org.micromanager.Studio')
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 150, in construct_java_object
    valid_method_spec = _check_method_args(methods_with_name, args)
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 398, in _check_method_args
    ', '.join([str(type(a)) for a in fn_args]) ))
Exception: Incorrect arguments. 
Expected  
Got 
```

This appears to be an issue with the logic in `_check_method_args_` but I'm not sure.

**Comment by henrypinkard** [comment]
Can you post example code please?

**Comment by nanthony21** [comment]
`Bridge().get_studio()`

**Comment by nanthony21** [comment]
Basically, an exception is raised `if valid_method_spec is None`. But the only way for `valid_method_spec` to not be `None` if for the function to loop through `method_specs`. So if `method-specs` is just an empty list then we have a problem.

**Comment by henrypinkard** [comment]
Yes, good catch. This is a bug on the java side. Fixed in this PR: https://github.com/micro-manager/pycro-manager/pull/13/commits/2956e4c2a35c5f1433e303fff45e00e2dca8ece4

Also PRed micromanager to update build version: https://github.com/micro-manager/micro-manager/pull/804

**Comment by henrypinkard** [comment]
If you want to keep playing with it before the next build you can drop in the new version:
https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.4.0/

**Comment by nanthony21** [comment]
Thanks! I'll give it a try.
