### ISSUE TITLE
Locations for questions

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#133]
Hi,

Are github issues a good place to ask questions or is there somewhere else that would be best for that. / have you considered a gitter room?

**Comment by ianhi** [comment]
For example a question I have is: Can I, and if so how, set up the multi-d acquisition from the μmanager gui and then run that from pycromanager?

**Comment by henrypinkard** [comment]
Yes, Github is good for now. I may officially add pycro-manager to image.sc in the future (although people already ask questions there under micro-manager)

No, as of right now Pycro-manager and micromanager MDA are separate systems. In the future, this will likely change as the micromanager moves to using the newer acquisition engine that pycromanager uses (https://github.com/micro-manager/pycro-manager/issues/29). 

In the mean time, you can run very similar acquisition programatically. Or if you need a GUI, micro-magellan acquisitions have most of the same features: https://pycro-manager.readthedocs.io/en/latest/acq_overview.html

**Comment by ianhi** [comment]
Awesome. And thanks for the link to image.sc I somehow had never seen that before :O
