### ISSUE TITLE
generated method signatures can be misleading for overloaded java methods

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#15]
The signature for `Bridge().get_core().set_roi` looks like this `(string, int, int1, int2, int3=None)`

When it really should look more like `(string=None, int, int1, int2, int3)`, however this wouldn't be allowed by Python. The method still works as expected for both overloads, it is just the signature that can be incorrect.

**Comment by henrypinkard** [comment]
Any suggestions?

**Comment by nanthony21** [comment]
I think this could be resolved with some changes to how we transmit the java overrides for a class. For now I think it's fine to leave it as is, just wanted to put this up for future reference.

Would it be possible to transmit method argument names in addition to argument types?

**Comment by henrypinkard** [comment]
It is possible, but unless the Jars were built in debug mode, the arg names just come out as arg0, arg1, arg2, etc. The micromanager jars dont appear to be built in debug mode

**Comment by henrypinkard** [comment]
Closing since there doesnt appear to be anything that can be done about this
