### ISSUE TITLE
Use numpy style docstrings?

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#151]
This may be an idiosyncrasy but I much prefer the numpy docstring style when reading the docstrings from jupyter or an ipython session. Would you consider switching to using numpy style  docstrings (https://numpydoc.readthedocs.io/en/latest/format.html) for the functions in this library?

For example here is a section of the `multi_d_acquistion_events` docstring
**currently:**
```python
"""
:param num_time_points: How many time points if it is a timelapse
:type num_time_points: int
:param time_interval_s: the minimum interval between consecutive time points in seconds. Keep at 0 to go as
    fast as possible
:type time_interval_s: float
:param z_start: z-stack starting position, in µm
:type z_start: float
:param z_end: z-stack ending position, in µm
:type z_end: float
"""
```

**in numpydoc style:**
```python
"""
parameters
----------
num_time_points : int
    How many time points if it is a timelapse
time_interval_s : float
    the minimum interval between consecutive time points in seconds. Keep at 0 to go as fast as possible
z_start : float
    z-stack starting position, in µm
z_end : float
    z-stack ending position, in µm
"""
```

There are sphinx plugins that can render numpy style docstrings so I don't the readthedocs page would be affected at all, only the appearance of the tooltip would change.

**Comment by henrypinkard** [comment]
Yeah I agree that looks at lot better. No real rational I picked the former way--I had just never let up sphinx before. Happy to merge a PR that makes the switch
