### ISSUE TITLE
issue templates?

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#152]
@henrypinkard would you be interested in issue templates? They can be helpful for structuing enhancement requests and could also encourage people to include information in bug reports (e..g pycromanager verison, μmanager version). 

As an example you can check out the issue templates on mpl-interactions look: https://github.com/ianhi/mpl-interactions/issues/new/choose

They live here https://github.com/ianhi/mpl-interactions/tree/master/.github/ISSUE_TEMPLATE and I'd be happy to port them over to this repo.

**Comment by henrypinkard** [comment]
Yep, definitely
