### ISSUE TITLE
Variable z positions in multi_d_acquisition_events

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#153]
I'm happy to implement this if there is interest - wanted to open this first to get feedback.

### Problem

I'd like to be able to create z stacks that are relative to each position when creating multidimensional acquisitions. Currently it is possible to specify multiple xy positions, but the z positions are shared by all xy points. It would be great if there were an option to specify the xyz positions and then add a relative z stack to each point.

### Proposed Solution

Add an `xyz_positions` argument to `multi_d_acqusition_events` along with a way to specify what the relative z steps should be.

### Additional Context

This is how the studio MDA panel works

**Comment by henrypinkard** [comment]
Yes, I think it'd be nice addition. Relative z stack would be good to add in the general case as well (regardless of xzy positions), maybe just as a boolean argument. Then you could keep the same `z_start`, `z_end`, but they would be relative to XYZ position (which would also be similar to MDA window)
