### ISSUE TITLE
Acquistion with large number of events (millions) hangs when started

### ISSUE THREAD

**Issue by dpshepherd** [micro-manager/pycro-manager#168]
Hi all,

Thanks for all of the help getting the stage scanning going. We are trying to setup a stress test right now for what is a normal sized scan for us.

The acquisition is ~6 million 2048x256 images across various stage positions and lasers. When we try to run the acquistion, the CPU usage for Micromanager goes to 100% and everything stalls out. We have the `display=False` flag set for the Acquisition.

Is there something we should do differently to execute this large of an acquistion? If we have less events, the acquisition will start. We haven't exhaustively tested where it hangs yet.

**Comment by henrypinkard** [comment]
I bet this is the acquisition continuing to process events for a really long time and not being able to combine them into sequences. If so, that would suggest that if you left it for a while, it would eventually get through them all and start running.

It would be instructive to know what is causing the delay for so many events. There are a bunch of calls to the core, and maybe some of these are slow for your particular hardware. Is it possible you could set up the [development environment on the Java side ](https://github.com/micro-manager/pycro-manager/issues/123)and run the acquisition engine from source? It is likely there is a delay somewhere in [this function](https://github.com/micro-manager/AcqEngJ/blob/360d12b07bd86f2b42e44f7b7514606978f514ec/src/main/java/org/micromanager/acqj/internal/acqengj/Engine.java#L166) and figuring out where would enable finding a solution

**Comment by dpshepherd** [comment]
We upped the RAM allocated to ImageJ, lengthed the timeout of the camera waiting for the initial trigger to a few minutes, and set `display=True`. The acquisition does eventually start.

The acquistion seems to work at 10 ms exposure time, but not if we use a 5 ms exposure time. 

For 5 ms, the acquisition starts but then images stopped being acquired after only a few thousand frames. The 10 ms acquistion has now been running since last night 

It isn't an SSD issue, as we are at less than half the write speed of the SSD array.

**Comment by dpshepherd** [comment]
Accidentally hit close.

**Comment by dpshepherd** [comment]
I'll see if one of the group members can setup the Java environment. Java and java environments are not something I'm familiar with and unfortunately don't have time to dive into.

**Comment by henrypinkard** [comment]
> The acquistion seems to work at 10 ms exposure time, but not if we use a 5 ms exposure time.

Maybe images cant be pulled from circular buffer fast enough? If you lok at plugins -- developer tools --sequence buffer monitor, you can see if images are getting stuck in the C++ core or making it into java layer

**Comment by henrypinkard** [comment]
> For 5 ms, the acquisition starts but then images stopped being shown and added to the acquisition after only a few thousand frames. The 10 ms acquistion has now been running since last night.

Strange. Anything suspicious in core log?

**Comment by henrypinkard** [comment]
> I'll see if one of the group members can setup the Java environment. Java and java environments are not something I'm familiar with and unfortunately don't have time to dive into.

Okay sounds good. If you cant find anything I can remote control and take a look, but I won't have time to do this for a week or two

**Comment by dpshepherd** [comment]
> Maybe images cant be pulled from circular buffer fast enough? If you lok at plugins -- developer tools --sequence buffer monitor, you can see if images are getting stuck in the C++ core or making it into java layer

It didn't appear so last time we checked. We will check again once this current large acquisition is finished. 

We are using 12-bit images, I wonder if we are seeing something related to this: https://forum.image.sc/t/fast-time-series-acquisition-for-10gige-camera/

We can successfully with 5 ms exposures, 12-bit readout, and 2048x256 ROI when using our Beanshell script without overflowing the circular buffer. But I'm assuming things are about different for pycro-manager acquistions.

**Comment by henrypinkard** [comment]
I doubt it, since that appears to be related to hardware and yours isnt since it runs with beanshell script.

memory management should be pretty much the same. If you look at ImageJ plugins-utilities--monitor memory you can see java memory usage, though I doubt it will spike too high.

You could try subbing in demo camera running a sequence if you think its specific to your hardware

**Comment by dpshepherd** [comment]
For the 10 ms acquisition, the circular buffer is always 0%, the disk usage is about ~100-120 MB/s (this is correct for the framerate and image bit depth), and the memory usage is a periodic function. It grows linearly 15 GB to 30 GB over a period of roughly 30 seconds. At 30 seconds, it drops nearly instantly back down to 15 GB and you can see the image display hiccup in the NDViewer. It has been repeating like this since the acquisition started last night.

**Comment by henrypinkard** [comment]
Makes sense, its accumulating images until it garbage collects. Theres an option on the viewer to not show every new image on arrival if you want to have a viewer but there might be a performance hit

**Comment by dpshepherd** [comment]
We would prefer to not have the viewer to prioritize performance, but the acquisition did not start with `display=False`. Not clear what is going on. Because we can't increase the timeout on the camera any farther, we are not sure if the camera is timing out because it has not seen a trigger or if there is something else going on.

We will test more once this current acquisition finishes.

**Comment by dpshepherd** [comment]
Allocating more RAM to ImageJ and extending the camera timeout solves this issue.
