### ISSUE TITLE
Exception: java.lang.RuntimeException: Internal class accidentally exposed

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#17]
The following calls have caused this java exception to be reported, I am sure there are many other ways to cause it as well.
 - Any call to a method of `Bridge.get_studio().plugins() in an attempt to access a plugin.
 - Any call to a method of `Bridge.get_studio().skin()`

As a side note, it may be helpful if a java traceback was included with exceptions.

**Comment by henrypinkard** [comment]
Fixed by https://github.com/micro-manager/pycro-manager/pull/18
