### ISSUE TITLE
Loading multi-terabyte datasets

### ISSUE THREAD

**Issue by dpshepherd** [micro-manager/pycro-manager#172]
We have a dataset on disk that should have dimensions of

[24010,37,1,4,256,1600] for [stage_x,stage_y,stage_Z,channels,cam_x,cam_y]

When we try to load this back into Python using,
```
dataset = Dataset(data_path)
dask_array = dataset.as_array(verbose=True)
print(dask_array.shape)
```

we get the following error,
```
Opening file 778 of 778C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\pycromanager\data.py:178: RuntimeWarning: overflow encountered in long_scalars
  info['next_ifd_offset'] = np.frombuffer(self._read(byte_offset + num_entries * 12 + 2,
C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\pycromanager\data.py:179: RuntimeWarning: overflow encountered in long_scalars
  byte_offset + num_entries * 12 + 6), dtype=np.uint32)[0]
Dataset opened
Adding data chunk 3553480 of 3553480 Stacking tiles
Traceback (most recent call last):
  File "c:/Users/dpsheph1/Documents/GitHub/OPM/Control-MM/test_load_data,py.py", line 11, in <module>
    dask_array = dataset.as_array(verbose=True)
  File "C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\pycromanager\data.py", line 537, in as_array
    array = da.stack(blocks)
  File "C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\dask\array\core.py", line 4384, in stack
    seq = [asarray(a) for a in seq]
  File "C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\dask\array\core.py", line 4384, in <listcomp>
    seq = [asarray(a) for a in seq]
  File "C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\dask\array\core.py", line 3857, in asarray
    a = np.asarray(a)
  File "C:\Users\dpsheph1\Anaconda3\envs\napari\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError: Unable to allocate 678. GiB for an array with shape (24010, 37, 256, 1600) and data type uint16
```

The appears to be two problems.
1. I'm assuming overflow is due to the huge number of images. Is there a flag we can pass to change how indexing is done for this large of a dataset? I'm also assuming is the reason the shape is wrong at the end?
2. Asking for the shape of a Dask array should not trigger a read event into memory. Is there something different here?

It's not clear to me this a bug, since there may be a way we need to handle this large dataset that we are not aware of.

**Comment by dpshepherd** [comment]
We tried this without the `verbose` flag and get the same error as above. Looking at the `as_array()` function it's not clear to me why this is triggering a read event.

I also looked into the code producing the uint32 overflow, but that appears to be tied to the NDTiffStorage formatting and it is not immediately clear to me how to rework that code to solve that issue.

**Comment by henrypinkard** [comment]
Axes being wrong is first problem to look at I think. Does it have the correct value for `self.axes` at this line?

https://github.com/micro-manager/pycro-manager/blob/016183b52cf990bcd7b8449321de2cccff10ee8e/pycromanager/data.py#L477

 It should be a dict with keys for each one of your non-singleton axes (i.e. no stage_Z)


For second one, can you print value of `byte_offset` and `num_entries` when that line problem triggers?

**Comment by dpshepherd** [comment]
It takes a very long time to open the dataset (>30 minutes), so any crashes are making it a bit prohibitive to troubleshoot. Is this normal?

We'll make the change to diagnose and let you know once we have some values.

**Comment by henrypinkard** [comment]
Unfortunately, yes. Inherent downside of having images in discontinuous chunks across many files, which is difficult if not impossible to avoid using Tiff. There's also some big overhead in combining all the constituent memory mapped numpy arrays into the dask array, but this is something internal to dask. 

Its possible some of the issues would be present with smaller datasets with only a few images on each axis, but maybe not since you might be the first person to stress test the huge dataset case

**Comment by dpshepherd** [comment]
```
byte_offset = 2147483518
num_entries = 13
```

Still working on the `self.axes`.

**Comment by henrypinkard** [comment]
Okay so the fact that `byte_offset = 2147483518` tells me that this is a problem with a uint32 being interpretted as a uint32 somwhere, because 2147483518 is the first value that is greater than 2 ^ 31. Same thing doesnt happen on my machine though. If you run

```
dataset = Dataset(data_path)
reader = dataset.res_levels[0].reader_tree[0][0][0][0]
slice = reader.np_memmap[2147483518:2147483522]
b = slice.tobytes()
arr = np.frombuffer(b, dtype=np.uint32)
val = arr[0]
```

does one of those lines give an error?

**Comment by dpshepherd** [comment]
No errors. See below.

```
reader = dataset.res_levels[0].reader_tree[0][0][0][0]
print(reader)
```
<pycromanager.data._MultipageTiffReader object at 0x00000237CC5BF0D0>

```
slice = reader.np_memmap[2147483518:2147483522]
print(slice)
```
[107   0  99   0]

```
b = slice2.tobytes()
print(b)
```
b'k\x00c\x00'

```
arr = np.frombuffer(b, dtype=np.uint32)
print(arr)
```
[6488171]

```
val = arr[0]
print(val)
```
6488171

**Comment by dpshepherd** [comment]
The `self.axes` structure looks correct to me. It is quite large, so not sure it makes sense to paste here. Let me see if I can put it in a text file and upload.
[axes.txt](https://github.com/micro-manager/pycro-manager/files/5442022/axes.txt)

**Comment by henrypinkard** [comment]
Looks like the shape isnt wrong, its just that the error happens when its trying to stack together 4  (24010, 37, 256, 1600) arrays to make a  (4, 24010, 37, 256, 1600). It does channels last because its alphabetical order I believe.

I think your error is not coming from `.shape`, its coming from `asarray`. Seems like dask is trying to allocate an empty (24010, 37, 256, 1600) array which is overflowing memory. Maybe because one of the ones thats supposed to be passed in is empty or messed up in some way. I assume this has to do with that warning. Since my little example before didnt give an error, it seems like the error might be coming from a particular file. Try inserting in a `print(self.tiff_path)` at line 178 before the problematic line, then you might be able to trace it to a particular file.

**Comment by dpshepherd** [comment]
Ok, we'll try that in a bit.

Right now, we are going to read each image in using some loops over the dataset and convert everything to an BigDataViewer H5. Once that is done, we will do some more troubleshooting.

**Comment by henrypinkard** [comment]
I suspect you might run into the same problem while doing so

**Comment by dpshepherd** [comment]
Understood., Since that is our own code it is a bit easier for us to troubleshoot.

**Comment by dpshepherd** [comment]
> Try inserting in a print(self.tiff_path) at line 178 before the problematic line, then you might be able to trace it to a particular file.

This returns an empty string. It is placed in the exception block that grabs `byte_offset` and `num_entries`.

**Comment by dpshepherd** [comment]
Ok, confusingly, running again gives the following file as triggering the error,
`E:\20201024\restrepo_z000_1\Full resolution\restrepo_z000_MagellanStack_565.tif`

**Comment by henrypinkard** [comment]
Also is there anything suspicious about the file? Last one in the dataset? different size than others? Does it open like a regular tiff when you drag it onto imagej/FIJI?

**Comment by dpshepherd** [comment]
`Also is there anything suspicious about the file?`
Does not appear to be.

` Last one in the dataset?` 
No.

`different size than others? `
All of the files are different sizes from each other. The size progressively becomes smaller as the files go from _000 -> _777

`Does it open like a regular tiff when you drag it onto imagej/FIJI?`
Yes.

**Comment by henrypinkard** [comment]
> All of the files are different sizes from each other. The size progressively becomes smaller as the files go from _000 -> _777

Thats kinda weird. By how much?

**Comment by dpshepherd** [comment]
We are >60% done deskewing and creating the H5 by reading each image from the dataset using `dataset.read_image()` No errors yet.

The deskewing code is not optimized for machines with less than 128 gb of RAM, so it is a running a bit slow on the acquisition computer. Should be done this afternoon.

We can try opening it using the Python reader once this is done.

**Comment by dpshepherd** [comment]
> Thats kinda weird. By how much?
Roughly 1,600 KB each file, which would correspond to ~2 images.

_000 is 4,186,782 KB and _776 is 3,299,682 KB.

_777 is only 290,140 KB - but I'm assuming that is because it didn't need to fill the TIFF container for the last images in the acquistion.

**Comment by henrypinkard** [comment]
Okay, tracking that now (https://github.com/micro-manager/NDTiffStorage/issues/16). Doesn't seem like its especially problematic though, and probably not related to the error here

**Comment by dpshepherd** [comment]
The deskewing and creating the BDV H5 was successful, with no errors pulling images out of the dataset. When viewed, there is no obvious missing data.

**Comment by henrypinkard** [comment]
So maybe an error in the non tiff-spec parts of the file. Can you share it?

**Comment by dpshepherd** [comment]
Sure, we will upload and link later this morning.

**Comment by dpshepherd** [comment]
Sorry for the delay on this, we have the file on our NAS but the network is being troublesome.

That said, we re-ran the acquisition two more times. For the new datasets, we do not get the error in `dataset = Dataset(data_path)` when loading the data. However, `dask_array = dataset.as_array()` still triggers Dask to try and create a 678 GB object in the memory.

**Comment by henrypinkard** [comment]
Okay, that says 2 different errors maybe. The one specific to that dataset maybe disk error.

For the other one, would it be easy to run an acquisition with the same axes but 2 or 3 images per an axis for debugging purposes?

**Comment by dpshepherd** [comment]
Yes, we can do that. Should have time on the instrument at the end of this week to setup the run.

**Comment by henrypinkard** [comment]
I think this is now fixed with all the other data saving changes
