### ISSUE TITLE
core.setSLMImage(java.lang.String slmLabel, byte[] pixels) doesnt work

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#173]

**Comment by henrypinkard** [comment]
maybe fixed by: https://github.com/micro-manager/micro-manager/pull/991 and https://github.com/micro-manager/pycro-manager/pull/174, but I don't have ability to test.

Misha?

**Comment by MishaRubanov** [comment]
Hi Henry,

I just upgraded my version of Pycromanager to 0.5. However, when I tried to use the SetSLMImageTo method, I was given an error: 
'NoneType object is not subscriptable'. 

I tried this with many different image formats - numpy arrays (dtype uInt32), lists, bytearrays, etc. What was the format that the method expects for the image?

Thanks for the help!
Misha

**Comment by MishaRubanov** [comment]
Also, attached is the file I've tried running, as well as the different image formats I've tried to use. 

[slm_v3.txt](https://github.com/micro-manager/pycro-manager/files/5446463/slm_v3.txt)

**Comment by henrypinkard** [comment]
Is the PIL Image a numpy array? the `im` in `core.setSLMImage(DMD,im)` should be a numpy array with shape (n,) where n is the number of pixels with dtype of uint8, uint16, or uint32, which correspond to java byte[], short[], or int[]. The uint8 version was the one I just fixed, but that change hasn't gone through yet into the nightly builds. So if you want to use it, you need to drop in pycromanager [0.9.5](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.9.5/) to replace whatever version you have in the plugins/micro-manager directory of your micromanager install. Also, before you do any of this, you should upgrade to the latest nightly build of micro-manager

**Comment by MishaRubanov** [comment]
Thank you for walking me through how to integrate the updated version of pycromanager. I've updated to the 102620 nightly build of micromanager, and replaced my 0.9.3 version in the build with the 0.9.5 version you linked. I changed the image that I'm uploading to a uin8 using the matplotlib image reader. I think I'm close, as the error I'm currently getting:

java.lang.Exception: Image dimensions are wrong for this SLM.
mmcorej.MMCoreJJNI.CMMCore_setSLMImage__SWIG_0(Native Method)
mmcorej.CMMCore.setSLMImage(CMMCore.java:1396)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:337)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:393)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:102)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Which points towards the wrong value for n. However, I think n is correct as I flattened the image (that has the dimensions equal to the height/width of the SLM) so I think n is correct. I've attached the updated file here. What do you suggest?
[slm_v4.txt](https://github.com/micro-manager/pycro-manager/files/5447361/slm_v4.txt)

**Comment by henrypinkard** [comment]
Okay so it seems that the array is correctly making it from python to the Java side, but as you say the size is wrong. I'm not familiar with that `imread` function. What if you generate a test array like this:

```
h = get_slm_height(DMD)
w = get_slm_width(DMD)
im2 = np.random.rand(h * w).astype(np.uint8)
```

Also I dont know if `uint8` is correct. What does `core.get_slm_number_of_components(DMD)` return?

**Comment by henrypinkard** [comment]
and also `core.get_slm_bytes_per_pixel`

**Comment by MishaRubanov** [comment]
Agreed - there is a bug somewhere on the Java side. I tried generating a test array the same way you did - but I got the same error (Image dimensions are wrong for this SLM.).

for core.get_slm_number_of_components(DMD) the return was 1
for core.get_slm_bytes_per_pixel(DMD) the return was also 1

**Comment by MishaRubanov** [comment]
Is there a Java method for finding the number of pixels the SLMImage method needs?

**Comment by henrypinkard** [comment]
it might be some improper conversion of numpy arrays to java arrays. Next thing to try would be to see if you can set it from the java side (i.e. in a beanshell script). Something like

```
pixels = new byte[mmc.getSLMHeight(DMD) * mmc.getSLMWidth(DMD)];
mmc.setSLMImage(DMD, pixels);
```
and then see if the size matches between java and python

**Comment by MishaRubanov** [comment]
That worked. Here is the beanshell file I used:
[test_um_v1.txt](https://github.com/micro-manager/pycro-manager/files/5447801/test_um_v1.txt)
So it must be something to do with numpy to java array conversion.

**Comment by henrypinkard** [comment]
Okay, will take a look

**Comment by nicost** [comment]
+1 for solving this, I'll be wanting to use this soon.  Thanks!

**Comment by MishaRubanov** [comment]
Thank you Henry! If there's anything I can do to help, let me know.

**Comment by henrypinkard** [comment]
I think this should fix it: https://github.com/micro-manager/pycro-manager/pulls?q=is%3Apr+is%3Aclosed

Could you give it a try? You'll need to both upgrade to [0.10.0](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.10.0/) and install pycromanager 0.6.0

**Comment by henrypinkard** [comment]
@nicost could you merge this: https://github.com/micro-manager/micro-manager/pull/991 when you get chance? I had to make some potentially backwards incompatible changes in the bridge so pypi version and nightly builds might not work together until it goes in

**Comment by nicost** [comment]
Done!  Not sure if it makes it in tonight's build, but certainly tomorrow.  Thanks for your work on this @henrypinkard !

**Comment by MishaRubanov** [comment]
@henrypinkard @nicost I just updated to 0.10.0 and installed the latest version of pycromanager, and the setSLMImage worked! Like you said, as long as the image is a uint8 np array of length (n,) with n being the number of pixels, the image was successfully passed to the java backend. Thanks again for all the work towards fixing this bug.

**Comment by henrypinkard** [comment]
Awesome! let me know if you run into anything else

**Comment by jmschr** [comment]
Hello @henrypinkard , I have run into what seems to be the exact same problem. I am trying to display an image on a Mightex Polygon400 with the set_slm_image function in pycro-manager and get the same error message about the image dimensions. With the above beanshell script it worked though and set_slm_pixels_to works as well. I also checked the type and shape of the array that I pass.

What confuses me is that I am using pycro-manager 0.10.13 and one of the latest MM2.0 builds of the last weeks, even though this issue occured and was fixed versions before that. 

Do you have any idea what I or the program might be doing wrong?

**Comment by henrypinkard** [comment]
Looks like a bug was introduced when I changed some underlying stuff to improve speed. Should be fixed in https://github.com/micro-manager/pycro-manager/pull/261.

If you go [here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.19.0/) and download the latest pycromanager-java jar, and replace the previous version in your `plugins/micro-manager` folder in your micromanager install directory, that should give you the fix

**Comment by jmschr** [comment]
It did indeed. Thank you for your work!
