### ISSUE TITLE
Stopping and restarting the ZMQ server on the Java side does not lead to a functional bridge

### ISSUE THREAD

**Issue by nicost** [micro-manager/pycro-manager#184]
Not sure if this belongs here or in the micro-manager repo, but stopping and restarting the ZMQ server (by unchecking the box in the Micro-Manager options dialog, and checking it again) does not result in a functional bridge (i.e. `bridge = Bridge()` times out).  

Not very important, but I ran in similar issues as described in #90 and was hoping that this simple action could restore speed.

**Comment by henrypinkard** [comment]
Turns out it was restarting, but an a different port. Fixed by:

https://github.com/micro-manager/pycro-manager/pull/185

https://github.com/micro-manager/micro-manager/pull/1024
