### ISSUE TITLE
Accessing Plugins - Multi Andor Control

### ISSUE THREAD

**Issue by mattgbiz** [micro-manager/pycro-manager#186]
I run an acquisition with an EMCCD camera and before our runs we change the "EM Gain" which is under Plugins-> Device Control -> Multi Andor Control. Is this a property that can be changed through a similar way as setting the exposure time? I am unsure how to access the plugins through the core.

**Comment by henrypinkard** [comment]
I'm not familiar with that specific hardware, but maybe. If you open **devices -- device property browser**, do you see EM Gain listed there? If so you can just call `core.set_property`
