### ISSUE TITLE
Isues with PositionListManager

### ISSUE THREAD

**Issue by nicost** [micro-manager/pycro-manager#204]
### Bug report

**Bug summary**
`pm = mm.positions()`
Type of pm is `MMStudio` (same as `mm`) instead of expected `PositionListManager`.  Same is observed for:
`pm = mm.get_postion_list_manager()`

Strangely enough, the `mm` object has all methods of the `PositionListManager` (`get_position_list(), mark_position(), set_position_list()`), so it seems as if pycro-manager someway combines the Java Studio and PostionListManager objects into one object.

Is this intentional, or accidental?  It is certainly strange that the Java API changes going through the pycro-manager bridge.

**Version Info**

  * Operating system:  Win 10 Pro
  * pycromanager version: 0.7.6
  * MicroManager version: from current source
  * Python version: 3.7.9
  * Python environment (command line, IDE, Jupyter notebook, etc) Pycharm

**Comment by henrypinkard** [comment]
Took a look and everything is working correctly. 

Turns out the `PositionListManager` is `MMStudio`

https://github.com/micro-manager/micro-manager/blob/b9bc2da2873543a9d4041997e8d2ebe322c87072/mmstudio/src/main/java/org/micromanager/internal/MMStudio.java#L1785

**Comment by nicost** [comment]
Wow, yes that makes sense, but is quite confusing!  I guess the problem is that the Java API documentation is all about interfaces, whereas pycro-manager gets the objects implementing those Java interfaces.  Seems that it would be best to strive for having classes that implement only a single interface, so that this confusion goes away. 

I'll open a ticket on micro-manager, seems straight forward to at least put PositionListManager into its own implementing class.

**Comment by henrypinkard** [comment]
Agreed.

Btw if you run into other problems with the Bridge, it can be really helpful to do `Bridge(debug=True)`, which will make it print all the messages going back and forth
