### ISSUE TITLE
Corrupted  file generated when running at extremely high data rates (>1.2 GB/s)

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#217]
[pycromanager_30fps_with_md_MagellanStack_21.zip](https://github.com/micro-manager/pycro-manager/files/5779092/pycromanager_30fps_with_md_MagellanStack_21.zip)

**Comment by henrypinkard** [comment]
@ieivanov Do you think you could give this a try again with all the new changes under the hood? I would expect now that if you go at a faster rate than it can write, the acquisition will fail and clean up properly. I'd also be curious to know what data rates are achievable on your hardware. But no need to hurry to this

**Comment by ieivanov** [comment]
Hi @henrypinkard, just wanted to let you know that I haven't forgotten about this. Yesterday I found out that it seems like my hard drive has slowed down a bit - I couldn't complete high speed acquisitions that used to run before. I'll troubleshoot that a bit, and then I'll test the new data writer. I'll let you know what I find out!

**Comment by henrypinkard** [comment]
Sounds good, let me know if there's anything I can do to help!
