### ISSUE TITLE
Dataset.as_array() is slow

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#220]

**Comment by henrypinkard** [comment]
@dpshepherd NDTiffstorage [1.5.0](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/ndtiffstorage/NDTiffStorage/1.5.0/) has changes to write additional metadata so that opening`Dataset` with a large number of files should be substantially faster. You also need to upgrade to pycromanager 0.8.0 to take advantage of this

**Comment by dpshepherd** [comment]
In limited testing using the demo config and code for the other issue, this is **much** faster! Converting to a Dask array still requires a surprising amount of transient RAM use, but I was able to rapidly load a `(2500, 12, 3, 256, 1600)` set as a Dask array on our microscope machine with 64 GB of RAM.

**Comment by henrypinkard** [comment]
Great! 

If you do `as_array(verbose=True)`, when does the RAM spike relative to "Stacking tiles" printing to the console? If its after this is printed, then the RAM spike is internal to a dask call.

**Comment by dpshepherd** [comment]
Verified that it is internal to a Dask call.

**Comment by henrypinkard** [comment]
I opened an issue in dask about this (https://github.com/dask/dask/issues/7161)

**Comment by henrypinkard** [comment]
Apparently, switching to different dask calls could make this a lot faster:

https://github.com/dask/dask/issues/5913

**Comment by dpshepherd** [comment]
I tested using `map_blocks` using `dataset.read_image(...)` as the reader, following [](https://docs.dask.org/en/latest/array-creation.html) and definitely works better. 

I had a look at the `Dataset` code and it wasn't immediately clear to me how to change the main code from dask `stack` to `map_blocks`. I need to sit down and map out the logic in `recurse_axes(loop_axes,point_axes)`.

**Comment by henrypinkard** [comment]
I can add in some comments to make it make more sense

**Comment by henrypinkard** [comment]
A bit more clear now hopefully:

https://github.com/micro-manager/pycro-manager/pull/258

**Comment by henrypinkard** [comment]
Maybe is fixed now?

https://github.com/dask/dask/issues/7161

**Comment by dpshepherd** [comment]
I don't think this is fixed yet. If you load a large dataset, it still triggers a very large memory read that is approximately the size of the data on the disk.

**Comment by henrypinkard** [comment]
Switched over to `dask.array.map_blocks`, which fixes the large memory read and gives a 🔥1000x speedup🔥 for `as_array` 


https://github.com/micro-manager/pycro-manager/pull/348
