### ISSUE TITLE
RGBA channel inverted for color camera

### ISSUE THREAD

**Issue by binli123** [micro-manager/pycro-manager#221]
### Bug report

**Bug summary**
The RGBA channel order is inverted as ABGR in Acquisition for RGB cameras. When the images are collected, the dataset contains the first three channels which are ABG, and are treated as RGB channels. Since the A channel is always 255 (which is treated as R channel), the image looks saturated in red color.

**Code for reproduction**

![image](https://user-images.githubusercontent.com/25302567/104234385-f0277c80-5418-11eb-8b57-815295925a77.png)

**Comment by henrypinkard** [comment]
The micro-manager demo RGB camera appears to be ABGR, and `Acquisition` is made to work with this. Seems like this is something that might need to be sorted out in the core/device adapter layer, either to provide taggedimages with a consistent ordering of RGBA channels or some function for figuring this out. Maybe @nicost or @marktsuchida know more?

**Comment by binli123** [comment]
> The micro-manager demo RGB camera appears to be ABGR, and `Acquisition` is made to work with this. Seems like this is something that might need to be sorted out in the core/device adapter layer, either to provide taggedimages with a consistent ordering of RGBA channels or some function for figuring this out. Maybe @nicost or @marktsuchida know more?

Few other observations that might help to locate the bug. Snap image in MM2 works just fine for the RGB camera and gives the correct image. Using core.snap_image() image and retrieving the tagged_image gives BGRA, and in order to plot it correctly using matplotlib I had to take the first three channels and invert the order so that it becomes RGB. Is there anyway that Acquisition could provide 4-channel color images? If so I can flip and re-arrange the channel after I get the image from the dataset.

**Comment by marktsuchida** [comment]
Yep, please see https://github.com/micro-manager/micro-manager/issues/541 and https://github.com/micro-manager/micro-manager/issues/734. Now that I have reprioritized a few things, these are very near the top of my to-do list.

Most device adapters work correctly with Micro-Manager 1.4 and (ancient) 2.0beta, but the current 2.0gamma branch still has the channels swapped in parts of MMStudio.

**Comment by henrypinkard** [comment]
Sounds like this is then a double bug -- channels swapped in device adapter and mmstudio -- which makes it work with snap/live, but the device adapter will need to be fixed to work as expected with pycromanager

**Comment by nicost** [comment]
@binli123 I may start working on this.  No doubt you moved on, but do you remember what camera and what camera device adapter you used?

**Comment by nicost** [comment]
One more question: do the colors look correct in the "normal" Micro-Manger window?

**Comment by binli123** [comment]
> One more question: do the colors look correct in the "normal" Micro-Manger window?

It looks correct in the snap and live window.

**Comment by nicost** [comment]
In that case, the Micro-Magellan viewer and or Pycromanager code is not handling them the same as the Micro-Manager code and viewer (note, I am not saying that any of these is "right", just that they should agree;).  There are many nasty issues with RGB byte ordering (see: https://en.wikipedia.org/wiki/RGBA_color_model).  The democamera has a mode called "Color Test Pattern" that is very useful.  It shows (top to bottom) stripes in blue, green, red, black, yellow, magenta, cyan, and white.  That on e seems most useful to be sure your byte ordering is the same (whatever it is;).

**Comment by henrypinkard** [comment]
Thanks that color test pattern was very helpful. I think this is now fixed by https://github.com/micro-manager/micro-manager/pull/1141 (was confusing because there were offseting bugs in the storage and viewer)
