### ISSUE TITLE
How to read stitched image from an acquisition

### ISSUE THREAD

**Issue by DanielGelfand-dev** [micro-manager/pycro-manager#243]
Hello, 

So the code I'm trying to write is supposed to acquire an acquisition and then read the dataset and output the stitched image.

this is the code and the result where it gives the following error: Exception : Method not yet implemented for in progress acquisitions

![image](https://user-images.githubusercontent.com/60196080/107862161-e5497880-6e18-11eb-94d5-3c681c201623.png)

If I do acq.acquire({'row': 0, 'col': 0}) it still doesn't let me read the stitched image as the final product. 
If I use a multi-d acquisition I get the same error but the stage goes through all the locations I'm interested in and then with
`img = dataset.read_image()
plt.imshow(img)`

I get the following 
![image](https://user-images.githubusercontent.com/60196080/107863206-4294f800-6e20-11eb-9dab-6028c5694501.png)

Any help would be greatly appreciated because I've been stuck on this for last 2 weeks and anything I try just doesn't work.
thank you.

**Comment by henrypinkard** [comment]
As the error says, that function is not yet implemented. Try opening the dataset from its path on disk, as described [here](https://pycro-manager.readthedocs.io/en/latest/read_data.html#creating-a-dataset-object)
