### ISSUE TITLE
Closed-loop acquisition and perturbation with pycro-manager

### ISSUE THREAD

**Issue by ulisesrey** [micro-manager/pycro-manager#264]
### Can't find the ImageProcessorFOCO package

I am trying to follow the tutorial on Closed-loop acquisition using pycro-manager and I could not install the ImageProcessorFOCO package.

I don't know where to find the package to install it.
I tried pip install ImageProcessorFOCO but could not find it.

Ref: https://pycro-manager.readthedocs.io/en/latest/application_notebooks/closedloop_headless_demo.html

### Update Documentation page

If you could improve the documentation on that section it would be great. At the moment it has some errors like 'Module not found', for cv2 or matplotlib.

Thank you very much.

**Comment by henrypinkard** [comment]
@RaymondDunn created it, maybe he can advise

**Comment by RaymondDunn** [comment]
Hi @ulisesrey (thx for the @ henry), 

the ImageProcessorFOCO is a local module (a single python file) in the pycro-manager applications notebook directory, you can find it at https://github.com/micro-manager/pycro-manager/blob/master/docs/source/application_notebooks/ImageProcessorFOCO.py

it's a quick-and-dirty class which takes a numpy array (image) as input and returns xy centers of peaks, using some packages like numba to accelerate processing. filtering params may need to be tweaked depending on your data.

thanks for pointing this out - the file is somewhat hidden if you don't clone the whole repo. i think a good fix is to take that code out of a separate module, and just include it in the notebook. this solution should also solve whatever testing generated the "module not found" errors. i'll work on this this weekend but you should be good with that file in the meantime

**Comment by RaymondDunn** [comment]
Hi @henrypinkard @ulisesrey, the changes were simple enough so I just pushed them to my branch and made a pull request. Sorry for the delay - I got a concussion shortly after my above message :/ a bottle of martinelli's fell of a shelf and got me upside the head

**Comment by henrypinkard** [comment]
Yikes!! Sorry to hear that and hope youre using those neuroscientist skills to heal that brain up right

**Comment by ulisesrey** [comment]
Cool thank you! I will have a look at it soon.

**Comment by henrypinkard** [comment]
Fixed with #284
