### ISSUE TITLE
Sequenced Acquisition works in MDA gui but not with pycromanager acquisition engine?

### ISSUE THREAD

**Issue by camFoltz** [micro-manager/pycro-manager#282]
### Bug report

**Bug summary**

@ieivanov and I typically run experiments that use hardware triggering of a z-stage from camera pulses.  We do this by running a "sequenced acquisition" where Micromanager will send a sequence of z-positions to the stage, and it will step through that sequence when it receives a pulse from the camera.  We use an ASI piezo stage and we prepare this acquisiton by setting the device property `ZStage-Use Sequence: 'Yes'`.  I am not sure what happens behind the scenes on Micromanagers acquisiton engine, but after this property is set to "Yes", any z-stack acquisition will now be acquired through hardware sequencing.

Pycromanager seems to have a bug when I try this same setup, but run an acquisition with the code below.  I receive a java.lang error immediately upon trying to run the acquisition. See Below

**Code for reproduction**

```python
from pycromanager import Bridge
from pycromanager import Acquisition, multi_d_acquisition_events

bridge = Bridge()
mmc = bridge.get_core()
mms = bridge.get_studio()

save_dir = 'Q:\\Cameron\\test'

# Z-Stack Settings

z_start =  -8#um
z_end = 8 #um
z_step = 0.25 #um

name='test'

pos_list_single = np.expand_dims(np.asarray([mmc.get_xy_stage_position().x, mmc.get_xy_stage_position().y, mmc.get_position('ZStage')]),0)

if __name__ == '__main__':
    with Acquisition(directory=save_dir, name=name, show_display=True) as acq:
        events = multi_d_acquisition_events(order = 'pz',
                                            z_start = z_start,
                                            z_end = z_end,
                                            z_step = z_step,
                                           xyz_positions = pos_list_single,
                                            )
        acq.acquire(events, keep_shutter_open=True)
```

**Expected outcome**

I expect this to run a triggered z stack acquisition at the current position

**Actual outcome**

An acquisition display window will pop up, and then the error below immediately follows in a pop-up window:

`java.lang.RuntimeException: java.lang.RunTimeException: java.util.concurrent.ExecutionException: org.micromanager.acqj.internal.acqengj.HardwareControlException`

**Note**
This was not an issue before we updated the firmware for the stage controller.  This started happening immediately after the update.  I am in conversation with ASI about the firmware and can relay any questions to them.  I want to blame the firmware, but I was surprised to see that it still works fine with the Micromanager MDA acquisition engine, so I am wondering if you have any ideas here.

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.10.13
  * MicroManager version: 4/28/2021
  * Python version: 3.7
  * Python environment (command line, IDE, Jupyter notebook, etc): jupyter notebook

**Comment by henrypinkard** [comment]
It looks like you're doubly supply the z positions, both directly (`z_start`, `z_end`, ...) and with (`xyz_positions`). If you print the events generated by `multi_d_acq`... do they look right?

**Comment by henrypinkard** [comment]
If thats not the problem, you could try calling the relevant code that the acquistion engine is calling directly, and see if you can reproduce. If so, that says error in device layer and not pycromanager

This is Java, but striaghtforward to translate and call through pycromanager:

```
DoubleVector zSequence = new DoubleVector() ;

// Loop and add all z positions
zSequence.add(zPos);
core_.loadStageSequence(zStage, zSequence);
core_.prepareSequenceAcquisition(core_.getCameraDevice());
core_.startStageSequence(zStage);

while (core_.isSequenceRunning()) {
                 //wait
}
core_.stopSequenceAcquisition();

//N is number of images
core_.startSequenceAcquisition(N, 0, true);

//loop and call N times to throw away the images
core_.popNextTaggedImage();
```

**Comment by camFoltz** [comment]
Hi Henry,

I supply the starting z position in the `xyz_positions` such that it creates events with relative z to that position.  These generated events are fine and run when `ZStage-UseSequence: 'No'` 

I ran that java code in python:

``` 
mmc = bridge.get_core()

z_stage = mmc.get_focus_device()
z_stage = mmc.get_focus_device()

mmc.load_stage_sequence(z_stage, posJ)
mmc.prepare_sequence_acquisition(mmc.get_camera_device())
mmc.start_stage_sequence(z_stage)

mmc.start_sequence_acquisition(len(pos_sequence), 0, True)

while mmc.is_sequence_running():
    pass

mmc.stop_sequence_acquisition()
```

  This code runs fine with no errors.  Can you point me to the full code which is responsible for this?  Maybe I can test out a bit more of it

**Comment by henrypinkard** [comment]
Hmm weird. The source of that code is here: https://github.com/micro-manager/AcqEngJ/blob/9c98c478794cf43d2fc45f3264fdb49eea8d4fb4/src/main/java/org/micromanager/acqj/internal/acqengj/Engine.java#L219

You can look around and try to copy more and run from python, or even better set up the Java dev environment and try to step through it line by line to see what goes wrong

**Comment by henrypinkard** [comment]
Information on how to do that [here](https://github.com/micro-manager/pycro-manager/issues/123)

**Comment by ieivanov** [comment]
Thanks for troubleshooting with us Henry!

Cam, I do have the java env set up, if that would be useful. Let me know and I can point you to it.

Cam, can you also confirm that z sequencing used to run with this pycromanager code before the firmware upgrade? It's quite strange that we're running into this problem.

Henry, the firmware upgrade was to increase the available sequence buffer length from 50 positions to 250 positions. Do you see why that may be a problem? Here we're using an ASI MS-2000 controller (https://micro-manager.org/wiki/ASIStage). I know that 250 positions work with their Tiger controller (https://micro-manager.org/wiki/ASITiger) without a problem. Could it possibly be a device adapter issue?

**Comment by henrypinkard** [comment]
Yeah that would make sense to me, except its weird that it works with MM MDA. So its possible theres a bug in AcqEngJ in dispatching the sequence to the hardware.

You could also try adding a `pre_hardware_hook`, and print the event, which at that point will be a sequence of multiple events, to see if it looks right
