### ISSUE TITLE
Issues with Pycro-Manager Acquisition

### ISSUE THREAD

**Issue by tschulze-ipms** [micro-manager/pycro-manager#287]
Hey guys, 
I just started working with Pycro Manager and as I went through the tutorials using the CameraDemo configuration I got an error when using the Acquisition class.

![Unbenannt](https://user-images.githubusercontent.com/84575544/119137970-a8a5a280-ba41-11eb-815c-a48d88b2b3eb.png)

So basically this should give me 10 images which are supposed to be saved in the given directory but unfortunately I get this error message.

![Unbenannt](https://user-images.githubusercontent.com/84575544/119138388-223d9080-ba42-11eb-8119-49f113ec280c.png)

So apparently the input arguments are somewhat off. But I basically just copied every line from the tutorial. Do you guys have any idea what the issue is?

Thanks in advance,
Tim

**Comment by tschulze-ipms** [comment]
Im using Win10 by the way.

**Comment by henrypinkard** [comment]
mismatch between pycro-manager and micro-manager versions. Upgrade to the latest versions of each

**Comment by tschulze-ipms** [comment]
Thanks, I will try that.

**Comment by tschulze-ipms** [comment]
That did the trick!
