### ISSUE TITLE
How to access images during multi-d-acquisition?

### ISSUE THREAD

**Issue by OptoManishK** [micro-manager/pycro-manager#296]
I am just getting started with pycro-manager.

I tried the simple example code (coped below) which worked nicely with files being written to the disk and a viewer popping up to display live images as they were getting acquired.

```
with Acquisition(directory=save_dir, name=save_name) as acq:
    events = multi_d_acquisition_events(num_time_points=10)
    acq.acquire(events)
```

Is it possible to "access" these images as they arrive? In other words, is there something like `core.get_tagged_image() ` for image stacks acquired with multi_d_acquisition? 

For example, if I am interested in on the fly numerical binning or image rotation etc. - is it possible to perform such actions from within python?

**Comment by dpshepherd** [comment]
Hi Manish!

It is possible using the hook function specifications, but the Java <-> Python bridge is limited to ~100 Mb/s. For image processing on the fly, the relevant doc pages are [here](https://pycro-manager.readthedocs.io/en/latest/img_processors.html).

We have a bunch of experience using pycro-manager for controlling OPM, please feel free to reach out if you have more specific questions.

Doug

**Comment by OptoManishK** [comment]
Thank you Doug for the reply. I'll go through the documentation in details and be sure to reach out if I needed help with OPM implementations.
