### ISSUE TITLE
Micro-Manager issue finding “Run server on port 4827” option 

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#297]
Hi,
I am trying to run pycro-manager and in the installation process it says to enable “Run on server port 4827” and that it is located in tools-options but I cannot seem to locate the box to check to run on this server port. If anyone could help me find it it would be much appreciated

Thank you very much,
Kai Wagoner

**Comment by henrypinkard** [comment]
Looks like its solved:

https://forum.image.sc/t/micro-manager-issue-finding-run-server-on-port-4827-option/54538
