### ISSUE TITLE
Unclean shutdown in headless mode.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#298]
Running the latest version of pycro-manager with the port number arguments.  It looks like the shutdown is not clean.  If I just run my script and exit at the end, I get this error and a hang.  Interestingly, if I send the process a kill signal, things seem to shut down fine.

`Exception ignored in: <function JavaObjectShadow.__del__ at 0x1b3ad3940>
Traceback (most recent call last):
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/pycromanager/core.py", line 474, in __del__
    self._close()
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/pycromanager/core.py", line 464, in _close
    self._socket.send(message)
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/pycromanager/core.py", line 115, in send
    self._socket.send_multipart(message_parts)
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/zmq/sugar/socket.py", line 555, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/zmq/sugar/socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 759, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
`

**Comment by henrypinkard** [comment]
There was a low level error with the shutdown of Bridges that I just fixed in trying to debug https://github.com/micro-manager/pycro-manager/issues/286. The cleanup behavior was erroneously in the destructor, which wasn't always called as I expected. I believe its fixed now by #299. You now need to use Bridge in a `with` statement, or explicitly call `close()` when finished with it. Available in v0.13.0

**Comment by carlkesselman** [comment]
thanks.. .suspected something like that.  

Question: so if I create a bridge in a with the statement, and then get the core from the bridge, is it safe to use that core outside of the with, or would that result in trouble.

**Comment by henrypinkard** [comment]
That will result in trouble because all the python handles to java obects get shutdown when the bridge closes. I think I should add in an error message for that situation

**Comment by carlkesselman** [comment]
ok.  So with headless, its probably best not to think of the bridge as being ephemeral, but rather something that should be managed for the durati9on.


I was also going to prepare a PR for threading through the bridge timeout into the headless create. I can go ahead and do that, or it might be easier just to stick that in if you think its a good idea.

**Comment by henrypinkard** [comment]
Not sure I understand exactly what you mean? Could you explain a bit more?

Also I just merged https://github.com/micro-manager/pycro-manager/pull/300 to adapt the port-specific caching to the changes I made

**Comment by carlkesselman** [comment]
I was just going to add a timeout argument to start_headless, so you can pass that on to the Bridge object in that call.

**Comment by henrypinkard** [comment]
Aha got it. go for it

**Comment by carlkesselman** [comment]
there is an error in the logic used to add bridge_count for additional ports.  I think I've fixed it... will submit a PR on this.

**Comment by carlkesselman** [comment]
hmm... I seem to still be getting the same error in the _del call.

**Comment by carlkesselman** [comment]
Ok... the following generates a shutdown error:

```
def shutdown_bug(config_file):
    # Start initial node, so we can figure out what cameras we have.
    print(f"Starting core on port")
    start_headless(mm_app_path, config_file, java_loc=java_loc)

    with Bridge() as bridge:
        core = bridge.get_core()
        default_camera = core.get_camera_device()
        bridge.get_core().set_camera_device(default_camera)
        with Bridge() as bridge:
            bridge.get_core().set_camera_device(default_camera)
```

The error is:

```
Exception ignored in: <function JavaObjectShadow.__del__ at 0x111601a60>
Traceback (most recent call last):
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 499, in __del__
    self._close()
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 488, in _close
    self._socket.send(message)
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 106, in send
    self._socket.send_multipart(message_parts)
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/zmq/sugar/socket.py", line 555, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/zmq/sugar/socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 759, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by carlkesselman** [comment]
This also seems to not work (debug flag used):

def shutdown_bug(config_file):
    # Start initial node, so we can figure out what cameras we have.
    print(f"Starting core on port")
    start_headless(mm_app_path, config_file, java_loc=java_loc)

    with Bridge(debug=True) as bridge:
        core = bridge.get_core()
        default_camera = core.get_camera_device()
        bridge.get_core().set_camera_device(default_camera)

This generates a timeout error,suggesting that the server is messed up.  Removing the debug flag makes it run fine.  The timeout is generated by the round trip of the debug message.

**Comment by henrypinkard** [comment]
> I'm also a little confused by the _closed variable. If a bridge instance is per port and per thread, and close is called on the destruction of the bridge instance, how could _closed ever be accessable. Specifically, would
> 
> ```
>  if self._bridge._closed:
>             raise Exception('The Bridge used to create this has been closed. Are you trying to call it outside of a "with" block?')
> ```
> 
> ever be called?

That I added to get a more interpretable error in this situation:

```python
with Bridge() as bridge():
   core = bridge.get_core()
# core is no longer valid now that bridge is closed to this should throw an interpretable error
core.get_exposure()
```

**Comment by henrypinkard** [comment]
> ```
> with Bridge(debug=True) as bridge:
>     core = bridge.get_core()
>     default_camera = core.get_camera_device()
>     bridge.get_core().set_camera_device(default_camera)
> ```

Yes I've seen that too. I believe its because a bunch of stuff is serialized and printed on the Java side of the bridge, and this counts against the timeout time. Is there any reason you cant just set the timeout extra long if you've got debug on?

**Comment by carlkesselman** [comment]
Yea, I can change the timeout, was just tyring to sort out if there is a deeper underlying problem related to the other problem I'm trying to sort out WRT the nested with statements.

**Comment by henrypinkard** [comment]
Not that I know of. 

Why do you need to use nested with statements rather than just reusing the same bridge?

**Comment by carlkesselman** [comment]
This is simplified code... in the real library I'm writing, its actually calling start_headless inside of the with, and the Bridge call is inside of that.  I can restructure, but it would probably be nice to figure out why this isn't working and get it right.... I'm trying to sort out exactly what is going on here.

**Comment by henrypinkard** [comment]
Okay. You can also call

```python
b = Bridge()
# Stuff
b.close()
```
In case that makes things easier

**Comment by carlkesselman** [comment]
Right....  I'm not convinced that the two issues I have found are unrelated, and I suspect there is a real bug lurking there someplace.

**Comment by henrypinkard** [comment]
It might be worth checking the micro-manager core log to see what is printed on the Java side
