### ISSUE TITLE
Headless Mode: Java Versions.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#302]
I am having a problem loading a configuration in headless mode that works fine when running under micromanager. 

I am running on MacOS and want to load the adapter for the Basler camera.  It wasn't provided with the release, so I downloaded, configured and compiled the module and placed in the latest micromanager release directory. Fired up micromanager with the configuration and all is fine.

Tried using the same configuration in headless mode and I get an error:
[hs_err_pid77161.log](https://github.com/micro-manager/pycro-manager/files/6759017/hs_err_pid77161.log)

Note that I am using V8 as the JRE in headless startup to get the class load to work, but it seems that micromanager is running V9.  Not sure if this is the issue, but its one difference that I see between the two setups.

**Comment by henrypinkard** [comment]
Thats pretty clearly an error coming from the device adapter itself, so its not clear to me why running headless or through micromanager would make a difference. Does the same thing happen when you swap in the demo camera for the basler camera? If so than I'd suspect there is an issue in the device adapter.

It does seem from that file that you're actually using JRE 9 to run the headless, not JRE8:

```
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
```

So perhaps that has something to do with it?

**Comment by carlkesselman** [comment]
Everything works fine with demo camera.

Not sure why it's jre9.  That is not the path I am using in the arg to headless start.  If you recall I had to specify jre8 to get the class load to work.  Let me see if something funny is goning on with the path.


Sent from my iPhone

On Jul 4, 2021, at 10:59 AM, Henry Pinkard ***@***.***> wrote:

﻿

Thats pretty clearly an error coming from the device adapter itself, so its not clear to me why running headless or through micromanager would make a difference. Does the same thing happen when you swap in the demo camera for the basler camera? If so than I'd suspect there is an issue in the device adapter.

It does seem from that file that you're actually using JRE 9 to run the headless, not JRE8:

# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)


So perhaps that has something to do with it?

**Comment by carlkesselman** [comment]
hmm... jre9 might have been something funny.  Its showing the correct JRE version after clean restart... still seeing same error and different behavior between headless start and using the GUI for the same config file.  

One thing I did notice from the stack trace is that the core seems to be trying to unload all of the drivers as part of loading the config file and the error occurs when the driver is unloaded.  Is is possible that this is causing the difference between the two scenarios?

[hs_err_pid50381.log](https://github.com/micro-manager/pycro-manager/files/6765461/hs_err_pid50381.log)

**Comment by henrypinkard** [comment]
It would make sense to me that the basler adapter has some error that only comes up when it is unloaded. 

But I don't know why this would only get triggered with headless start. The calls made as headless start are directly copied from those that launch micro-manager in Java. You can see them here:

https://github.com/micro-manager/pycro-manager/blob/49b68607cc04d4405bf9b1f7cde74f6559ca1cf7/pycromanager/acquire.py#L77

I don't see any reason why this would be different from the source it was copied from:

https://github.com/micro-manager/micro-manager/blob/fe1a3b72f3a6fd36b717789ccb76c4c185b66298/mmstudio/src/main/java/org/micromanager/internal/MMStudio.java#L797

**Comment by carlkesselman** [comment]
As a test, I tried to just load the module, and I also get an error.  While I'm willing to believe I did something wrong building the module, the difference in behavior between headless start and regular start is concerning.  Is it possible there is something in my setup that would make the two behave differently?  The micro-manager download is just a nightly build, right out of the box. 

```b.get_core().load_device("BaslerCamera")
Traceback (most recent call last):
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4d0ec9da58eb>", line 1, in <module>
    b.get_core().load_device("BaslerCamera")
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 426, in <lambda>
    ): instance._translate_call(signatures_list, args)
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 534, in _translate_call
    valid_method_spec, deserialize_types = _check_method_args(method_specs, fn_args)
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 698, in _check_method_args
    raise Exception(
Exception: Incorrect arguments. 
Expected java.lang.String, java.lang.String, java.lang.String 
Got <class 'str'>
b.get_core().load_device("Camera","BaslerCamera","FooBar")
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:346)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:401)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:108)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Failed to load device "FooBar" from adapter module "BaslerCamera" [ Device adapter "BaslerCamera" failed to instantiate device "FooBar" ]
	at mmcorej.MMCoreJJNI.CMMCore_loadDevice(Native Method)
	at mmcorej.CMMCore.loadDevice(CMMCore.java:312)
	... 11 more
Traceback (most recent call last):
  File "/Users/carl/opt/anaconda3/envs/spim-data/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-0b57b264d972>", line 1, in <module>
    b.get_core().load_device("Camera","BaslerCamera","FooBar")
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 426, in <lambda>
    ): instance._translate_call(signatures_list, args)
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 548, in _translate_call
    return self._deserialize(self._socket.receive())
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 167, in receive
    self._check_exception(message)
  File "/Users/carl/Repos/Projects/pycro-manager/pycromanager/core.py", line 172, in _check_exception
    raise Exception(response["value"])
Exception: java.lang.Exception: Failed to load device "FooBar" from adapter module "BaslerCamera" [ Device adapter "BaslerCamera" failed to instantiate device "FooBar" ]
mmcorej.MMCoreJJNI.CMMCore_loadDevice(Native Method)
mmcorej.CMMCore.loadDevice(CMMCore.java:312)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:346)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:401)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:108)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by henrypinkard** [comment]
> As a test, I tried to just load the module, and I also get an error.

Unclear on what exactly you did. Can you post code?

> I'm willing to believe I did something wrong building the module, the difference in behavior between headless start and regular start is concerning. Is it possible there is something in my setup that would make the two behave differently? The micro-manager download is just a nightly build, right out of the box.

I agree. But there's nothing obvious to me as to what would be causing that. Maybe there is something weird with your string formatting + passing from java to python such that `config_file` in `core.load_system_configuration(config_file)` is incorrect?

**Comment by carlkesselman** [comment]
sorry, I led you astray... I didn't check carefully enough.  It turns out that the first start_headless works fine.  I then do a second on a different port and this is the one that fails with the java error message.  I wonder if there is some shared state that is messing up the second instance... perhaps in the USB driver iteself.  I will play around some more.

**Comment by carlkesselman** [comment]
yep, that seems to be it.  It would seem that micromanager is not happy when you try to load the same adapter twice, even though it is on a different port.

**Comment by henrypinkard** [comment]
Sounds like it is an adapter-specific bug then. Worth opening an issue on main micro-manager repo
