### ISSUE TITLE
basic operations like getPosition(), setPosition() etc.

### ISSUE THREAD

**Issue by yellenlab** [micro-manager/pycro-manager#303]
I was wondering if there is a simple way to directly control the hardware without going through the multidimensional acquisition functions.  Basically I just want to do things like getPosition, setPosition, setProperty('Turret', 'State', value).  Do you have any quick an easy examples that I can follow?

**Comment by henrypinkard** [comment]
https://pycro-manager.readthedocs.io/en/latest/core.html

**Comment by yellenlab** [comment]
Thanks, that's a nice resource on how to use the package.
