### ISSUE TITLE
XY tiling issue

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#306]
Hello,

When trying to acquire using XY tiling method via pycromanager it wont capture the first position (0,0) unless we write the first line twice. Is there anyway around this issue?
Below is our code with the first line doubled

from pycromanager import Acquisition, multi_d_acquisition_events
with Acquisition('/Users/Min/Desktop/Summer_2021/071321', 'pythontest', tile_overlap=10) as acq:
    acq.acquire({'row':0, 'col':0})
    acq.acquire({'row':0, 'col':0})
    acq.acquire({'row':1, 'col':0})
    acq.acquire({'row':2, 'col':0})
    acq.acquire({'row':2, 'col':1})
    acq.acquire({'row':1, 'col':1})
    acq.acquire({'row':0, 'col':1})
    acq.acquire({'row':0, 'col':2})
    acq.acquire({'row':1, 'col':2})
    acq.acquire({'row':2, 'col':2})

**Comment by henrypinkard** [comment]
You've discovered a bug. Will take a look

**Comment by henrypinkard** [comment]
I didn't see exactly what you described but found an issue with tiling which would definitely create some unexpected problems. I fixed that one (https://github.com/micro-manager/micro-manager/pull/1275)

Can you double check if it fixes your issue? You can either wait until tomorrow and download the latest micro-manager nightly build, or you can manually update by replacing AcqEngJ.jar with the [new version](https://s01.oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.micro-manager.acqengj&a=AcqEngJ&v=0.12.3&e=jar). This is in the `plugins/micro-manger` folder of your micro-manager install

**Comment by kwagoner94** [comment]
Thank you very much, this solved our issue
