### ISSUE TITLE
Acquisition Hangs after 30 images

### ISSUE THREAD

**Issue by michaelpmay** [micro-manager/pycro-manager#308]
Hello, 

I am trying to use Acquisition and multi_d_acquisition_events to generate some images, but the acquisition hangs after 30 events.

When I change the acquisitions to 10 sets of 10 images instead of one set of 100 images the acquisition works.

When I create a multi d acquisition of 100 images directly from micromanager it also works.

Here is the code snippet I am using. It stops printing after 30 events when it should be 100.

def PrintEvent(event, bridge, stack):
    print(event)
    pass
events=multi_d_acquisition_events(num_time_points=100,time_interval_s=0.5)
acq = Acquisition(post_camera_hook_fn=PrintEvent)
acq.acquire(events)

Here is the output:

{'axes': {'time': 0}, 'min_start_time': 0, 'properties': []}
{'axes': {'time': 1}, 'min_start_time': 0, 'properties': []}
{'axes': {'time': 2}, 'min_start_time': 1, 'properties': []}
{'axes': {'time': 3}, 'min_start_time': 1, 'properties': []}
{'axes': {'time': 4}, 'min_start_time': 2, 'properties': []}
{'axes': {'time': 5}, 'min_start_time': 2, 'properties': []}
{'axes': {'time': 6}, 'min_start_time': 3, 'properties': []}
{'axes': {'time': 7}, 'min_start_time': 3, 'properties': []}
{'axes': {'time': 8}, 'min_start_time': 4, 'properties': []}
{'axes': {'time': 9}, 'min_start_time': 4, 'properties': []}
{'axes': {'time': 10}, 'min_start_time': 5, 'properties': []}
{'axes': {'time': 11}, 'min_start_time': 5, 'properties': []}
{'axes': {'time': 12}, 'min_start_time': 6, 'properties': []}
{'axes': {'time': 13}, 'min_start_time': 6, 'properties': []}
{'axes': {'time': 14}, 'min_start_time': 7, 'properties': []}
{'axes': {'time': 15}, 'min_start_time': 7, 'properties': []}
{'axes': {'time': 16}, 'min_start_time': 8, 'properties': []}
{'axes': {'time': 17}, 'min_start_time': 8, 'properties': []}
{'axes': {'time': 18}, 'min_start_time': 9, 'properties': []}
{'axes': {'time': 19}, 'min_start_time': 9, 'properties': []}
{'axes': {'time': 20}, 'min_start_time': 10, 'properties': []}
{'axes': {'time': 21}, 'min_start_time': 10, 'properties': []}
{'axes': {'time': 22}, 'min_start_time': 11, 'properties': []}
{'axes': {'time': 23}, 'min_start_time': 11, 'properties': []}
{'axes': {'time': 24}, 'min_start_time': 12, 'properties': []}
{'axes': {'time': 25}, 'min_start_time': 12, 'properties': []}
{'axes': {'time': 26}, 'min_start_time': 13, 'properties': []}
{'axes': {'time': 27}, 'min_start_time': 13, 'properties': []}
{'axes': {'time': 28}, 'min_start_time': 14, 'properties': []}
{'axes': {'time': 29}, 'min_start_time': 14, 'properties': []}
{'axes': {'time': 30}, 'min_start_time': 15, 'properties': []}

It stalls here at 30.

What am I doing wrong here?
Thanks!

**Comment by henrypinkard** [comment]
First thing to figure out is if this is related to your specific hardware. Do you still see this behavior when running with the micromanager demo configuration?

**Comment by michaelpmay** [comment]
Hello again, 

I tried with the demo config and it appears that it also hangs at 30 images

**Comment by henrypinkard** [comment]
You're not supplying a saving name and saving directory to `Acquisition`. It has an internal queue of images that build up, which happens to have a default size of 30. Without anywhere to save them, it just hangs.

You either need to supply a saving name and directory, or implement and image processor to intercept the images and do something with them without saving to disk.
