### ISSUE TITLE
Problem acquiring 

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#309]
Hi I am running into an issue where my code keeps producing an error. 
Below is the code I am trying to run. When I ran it last week it was working fine.

from pycromanager import Acquisition

with Acquisition('/Users/Min/Desktop/Summer_2021/072021', 'pythontest', tile_overlap=25) as acq:
    acq.acquire({'row':0, 'col':0})
    acq.acquire({'row':0, 'col':1})
    acq.acquire({'row':0, 'col':2})
    acq.acquire({'row':1, 'col':0})
    acq.acquire({'row':1, 'col':1})
    acq.acquire({'row':1, 'col':2})
    acq.acquire({'row':2, 'col':0})
    acq.acquire({'row':2, 'col':1})
    acq.acquire({'row':2, 'col':2})

The error I am getting is: 

C:\Users\Min\PycharmProjects\pycromanage\venv\Scripts\python.exe C:/Users/Min/PycharmProjects/pycromanage/test.py
Traceback (most recent call last):
  File "C:\Users\Min\PycharmProjects\pycromanage\test.py", line 3, in <module>
    with Acquisition('/Users/Min/Desktop/Summer_2021/072021', 'pythontest', tile_overlap=25) as acq:
  File "C:\Users\Min\PycharmProjects\pycromanage\venv\lib\site-packages\pycromanager\acquire.py", line 431, in __init__
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Users\Min\PycharmProjects\pycromanage\venv\lib\site-packages\pycromanager\core.py", line 419, in <lambda>
    ): instance._translate_call(signatures_list, args)
  File "C:\Users\Min\PycharmProjects\pycromanage\venv\lib\site-packages\pycromanager\core.py", line 541, in _translate_call
    return self._deserialize(self._socket.receive())
  File "C:\Users\Min\PycharmProjects\pycromanage\venv\lib\site-packages\pycromanager\core.py", line 167, in receive
    self._check_exception(message)
  File "C:\Users\Min\PycharmProjects\pycromanage\venv\lib\site-packages\pycromanager\core.py", line 172, in _check_exception
    raise Exception(response["value"])
Exception: java.lang.RuntimeException: Cannot run acquisition with XY tiling without first definingaffine transform between camera and stage. Check pixel size calibration
org.micromanager.acqj.api.Acquisition.initialize(Acquisition.java:246)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:31)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:40)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:341)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:396)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:103)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1

My micromanger is properly calibrated and I just updated pycromanager so I am unsure what I am doing wrong/missing
Thank you very much

**Comment by henrypinkard** [comment]
It runs fine for me with the demo configuration, which makes me suspect that, as the error suggests, there is something wrong with your pixel size calibration. Try running with the demo configuration (should work), and then you might be able to work backwards from there to debug

**Comment by kwagoner94** [comment]
Yes it worked when we recalibrated the system.

Thank you very much
