### ISSUE TITLE
Calling Autofocus feature using pycro

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#311]
Hi,

I was curious if there was a way to call upon the autofocus feature using pycromanager when doing multiple acquisitions and tiling.

Thank you very much,
Kai Wagoner-Oshima

**Comment by henrypinkard** [comment]
You can try using the autofocus features of the [Micro-Manager studio API](https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmstudio/org/micromanager/Studio.html#getAutofocusManager--). Or alternative you can manually implement autofocus in an acquisition hook (e.g. to focus at every position while tiling). Or you might be able to combine these

**Comment by kwagoner94** [comment]
I tried calling the autofocus feature using the studio API. The code runs all the way through but doesn't seem to actually perform the autofocus function. Could you take a look at the code I used below:

            with Bridge(convert_camel_case=False) as bridge:
                mm = bridge.get_studio()
                focus = mm.getAutofocusManager()
                focus.getAutofocusMethod()
                focus.initialize()
