### ISSUE TITLE
Error running Autofocus with XY tiling feature

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#316]
Hi there,

When running my code for XY tiling with autofocus, I occasionally get a java/micromanager error and am wondering if there is a way to solve this issue. Below is my code followed by the error message I am getting:

![code](https://user-images.githubusercontent.com/66525533/128387526-8817a645-9744-4a6a-a3c1-5ce6c62a6a94.JPG)

![code_java error pycro](https://user-images.githubusercontent.com/66525533/128387072-0dbb93e8-2925-4fec-ba7d-60d119bb691b.JPG)

**Comment by henrypinkard** [comment]
It looks like this error is coming from the Java side in the Micro-Manager API (and is thus outside the scope of pycro-manager). I suggest opening an issue in the main micro-manager repository
