### ISSUE TITLE
`image_process_fn` with smaller image size

### ISSUE THREAD

**Issue by yfukai** [micro-manager/pycro-manager#317]
Hi, I appreciate this great attempt toward a programmable microscope, thanks! 
I am trying to use pycromanager in a situation where four channels are projected onto a single camera. I would like to split the images in the acquisition and thought `image_process_fn` would suffice. However, I found the resulting image is broken.

The following is my code:
```python
import copy
import os

import numpy as np
from pycromanager import Bridge, Acquisition
from pycromanager import multi_d_acquisition_events

bridge = Bridge()
core = bridge.get_core()
mmStudio = bridge.get_studio()

events=multi_d_acquisition_events(
    num_time_points=100, 
    time_interval_s=0,
    channel_exposures_ms=50)


subimage_offsets=(0,0)
subimage_sizes=(256,256)
channel_names=["ch1","ch2","ch3","ch4"]

def img_process_fn(image, metadata):
    assert len(image.shape)==2
    images=[]
    for poss,channel_name in zip(
        [(0,1),(0,0),(1,0),(1,1)],channel_names 
    ):
        roi=[(shape//2*pos+subimage_offset,
              shape//2*pos+subimage_offset+subimage_size)
              for shape,pos,subimage_offset,subimage_size 
              in zip(image.shape,poss,subimage_offsets,subimage_sizes)]
        subimage=np.array(image[roi[0][0]:roi[0][1],
                                roi[1][0]:roi[1][1]],copy=True)
        metadata2 = copy.deepcopy(metadata)
        #metadata2["Width"]=subimage_sizes[1]
        #metadata2["Height"]=subimage_sizes[0]
        metadata2['Channel'] = channel_name
        metadata2["roi"]=roi
        images.append((subimage,metadata2))
    return images

def img_process_fn2(image, metadata):
    assert len(image.shape)==2
    return np.array(image[:100,:100],copy=True),metadata

image_path="20210816-image_process_fn-test"
os.makedirs(image_path,exist_ok=True)

with Acquisition(directory=image_path, 
                name=f"test1",
                image_process_fn=img_process_fn1
                ) as acq:
    acq.acquire(events)

with Acquisition(directory=image_path, 
                name=f"test2",
                image_process_fn=img_process_fn2
                ) as acq:
    acq.acquire(events)
```

I expected four-channel images with 256x256px for `test1` and small image with 100x100px for `test2`. 
However, the following is what I get with the demo camera:

(for test1)
![image](https://user-images.githubusercontent.com/5919272/129540097-96b8822e-1932-447c-a65e-b00eb8b50121.png)
(for test2)
![image](https://user-images.githubusercontent.com/5919272/129540292-bef2d7e5-2710-4118-a05a-e5cf12c6a7cb.png)

Setting the metadata for `"Width"` and `"Height"` did not help. 
Is this kind of ROI cropping supported in `image_process_fn`, and if not, is there any plan for the implementation of this feature? (Or possibly am I doing something wrong in my code?)

The version info is as following:
```
pycromanager: 0.13.2
Python: 3.8.8 
MM Studio version: 2.0.0
MMCore version: 10.1.1
Device API version 70, Module API version 10

in Windows 10 64bit
```

Thanks!

**Comment by henrypinkard** [comment]
This is a bug in the underlying data storage code. It is not accounting for image-resizing on the fly right now, so this will need to be fixed

**Comment by yfukai** [comment]
I see, thank you @henrypinkard for your reply!

**Comment by yfukai** [comment]
Hello @henrypinkard, I'm wondering whether I could make some contribution, but not sure where is the cause of this bug. If you would have time, would you mind guiding me to the part of the code possibly causing this?

**Comment by henrypinkard** [comment]
Thanks for offering, it was kind of buried deep in the code though so I went ahead and fixed it. You'll need to update to (tomorrows) nightly build of MM

**Comment by henrypinkard** [comment]
Here's the code I used with the MM demo configuration:

```python
import copy
import os

import numpy as np
from pycromanager import Bridge, Acquisition
from pycromanager import multi_d_acquisition_events

bridge = Bridge()
core = bridge.get_core()
mmStudio = bridge.get_studio()

events=multi_d_acquisition_events(
    num_time_points=100, 
    time_interval_s=0,
    channel_exposures_ms=50)


def img_process_fn2(image, metadata):
    pairs = []
    for i in range(4):
        metadata = copy.deepcopy(metadata)
        metadata['Width'] = 256
        metadata['Height'] = 256
        metadata['Axes']['crop'] = i
        if i == 0:
            image = np.array(image[:256, :256], copy=True)
        elif i == 1:
            image = np.array(image[-256:, :256], copy=True)
        elif i == 2:
            image = np.array(image[:256, -256:], copy=True)
        elif i == 3:
            image = np.array(image[-256:, -256:], copy=True)
        pairs.append((image, metadata))

    return pairs


with Acquisition(directory='/Users/henrypinkard/tmp/',
                name=f"test2",
                image_process_fn=img_process_fn2
                ) as acq:
    acq.acquire(events)
```

**Comment by yfukai** [comment]
Thanks a lot, @henrypinkard. I truly appreciate this update.
I will check if this works in my environment as soon as possible.

**Comment by yfukai** [comment]
I checked how it works here! When I check the output, the four channels seem to be correctly output. however, the on-the-fly display seems to be showing only one of the channels, irrespective of the `c` slide value. I'm wondering this display might be still not adapted to the new code.

![image](https://user-images.githubusercontent.com/5919272/133033743-d10bc572-536d-48a5-b733-59db53559060.png)
![image](https://user-images.githubusercontent.com/5919272/133033802-c11af7b4-4d26-42cd-b564-821ed3a5e808.png)

```
MM Studio version: 2.0.1 20210912
MMCore version 10.1.1
Device API version 70, Module API version 10
```

**Comment by yfukai** [comment]
I changed the test code as below, but confirmed that four-channel splitting is working with `MM Studio version: 2.0.1 20210912, MMCore version 10.1.1, Device API version 70, Module API version 10`. Thanks a lot @henrypinkard !
```python
        if i == 0:
            image2 = np.array(image[:200, :200], copy=True)
        elif i == 1:
            image2 = np.array(image[-200:, :200], copy=True)
        elif i == 2:
            image2 = np.array(image[:200, -200:], copy=True)
        elif i == 3:
            image2 = np.array(image[-200:, -200:], copy=True)
        pairs.append((image2, metadata))
```
