### ISSUE TITLE
Properties in Acquisition events won't work

### ISSUE THREAD

**Issue by LuisFMCuriel** [micro-manager/pycro-manager#318]
Hi,

I have been using event acquisition but I need to set some properties for the devices I am using. I tried to do it as documented [here](https://pycro-manager.readthedocs.io/en/latest/acq_events.html?highlight=acquire)

```
with Acquisition('/Users/henrypinkard/megllandump', 'pythonacqtest') as acq:
    events = []
    for index in range(10):
        evt = {
                'axes': {'arbitrary_axis_name': index},
                #'properties' for the manipulation of hardware by specifying an arbitrary
                #list of properties
                'properties':
                   [['device_name', 'property_name', 'property_value'],
                    ['device_name_2', 'property_name_2', 'property_value_2']]}
        events.append(evt)

    acq.acquire(events)
```

However, using this approach don't seem to be applied the changes that I made. Therefore, I have been forced to use `core.set_property` to change the properties before the acquisition:

```
with Acquisition(directory=path_s, name='Test') as acq:
        events = []
        for j in range(10):
            evt = {
                    'axes': {'z': i},
                    'exposure': 250,
                    'keep_shutter_open': False,
                    'min_start_time': 1.0,
                    'z': Z[i], 
                    'x': X[i], 
                    'y': Y[i],
                    #properties should be here, but it does not work
                }
            events.append(evt)
            
        core.set_property("Spectra", "State", 1)
        core.set_property("Spectra", "Cyan_Enable", 1)
        core.set_property("Spectra", "Cyan_Level", 5)
        core.set_property("Spectra", "Green_Enable", 1)
        core.set_property("Spectra", "Green_Level", 10) 
        acq.acquire(events)
```

I was wondering if you can help solve this problem. I want the shutter to be open ONLY during the acquisition process (to avoid photobleaching). But with this approach, the shutter is always open.

Thanks in advance!

**Comment by henrypinkard** [comment]
> I have been using event acquisition but I need to set some properties for the devices I am using. I tried to do it as documented [here](https://pycro-manager.readthedocs.io/en/latest/acq_events.html?highlight=acquire)

Im confused. I don't see that you've tried to set any properties in the code you posted

**Comment by LuisFMCuriel** [comment]
Oh no, for some reason my edit was not made to my question. I am so sorry for the confusion. To be more specific, I tried this:
```

with Acquisition(directory=path_s, name='Test') as acq:
        events = []
        for j in range(10):
            evt = {
                    'axes': {'z': i},
                    'exposure': 250,
                    'keep_shutter_open': False,
                    'min_start_time': 1.0,
                    'z': Z[i], 
                    'x': X[i], 
                    'y': Y[i],
                    'properties':[ ["Spectra", "State", 1], 
                                        ["Spectra", "Cyan_Enable", 1],
                                        ["Spectra", "Cyan_Level", 5],
                                        ["Spectra", "Green_Enable", 1],
                                        ["Spectra", "Green_Level", 10]]

                }
            events.append(evt)
```

but for some reason, the properties changes don't seem to be applied. It acquires the images without setting those properties to my device. Any idea how I can fix this?

Thank you for your reply and sorry again for the confusion.

**Comment by henrypinkard** [comment]
It works for me with demo configuration and:

```
with Acquisition(directory="/Users/henrypinkard/tmp", name="tcz_acq", debug=False) as acq:
    events = []
    for j in range(10):
        evt = {
            'axes': {'z': j},
            'exposure': 250,
            'keep_shutter_open': False,
            'z': 2.2,
            'properties': [["Camera", "Gain", 3],]

        }
        events.append(evt)
    acq.acquire(events)
```

2 questions: 
1) Are you using hardware sequencing (my example is not)?
2) Do you see anything in micromanager core logs indicating that an exception was thrown on the java side?
