### ISSUE TITLE
Clean termination of acquisition.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#328]
I would like to deal with the error case where I have an acquire that has some number of events that are generated via a hardware trigger, and for whatever reason the camera misses one or more of the triggers.  I am running the acquire in its own thread, and  I can tell by the amount of time that has passed that I'm hung waiting for a missed trigger.  Ideally, I think I would like to somehow terminate the acquire without loosing any of the data that was captured.  

Is this possible?

**Comment by henrypinkard** [comment]
The data saves as it goes, so could you just kill the thread? Or do you need to kill the acquisition within the thread?

**Comment by carlkesselman** [comment]
I think I need to kill the acquisition, which is running in the thread.  I want to deal with the case where I’ve got given the acquire a lot of events, and I generate one trigger per event.  If something bad happens and a trigger is missed the acquisition is left waiting.
 Killing the thread would be ok, as long as it doesn’t corrupt the index file.

Thanks,

Carl



----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Profesor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine
Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.******@***.***>
Web: http://www.isi.edu/~carl










On Oct 8, 2021, at 1:10 PM, Henry Pinkard ***@***.******@***.***>> wrote:



The data saves as it goes, so could you just kill the thread? Or do you need to kill the acquisition within the thread?

**Comment by carlkesselman** [comment]
Ok... part of my problem was I didn't realize the context manager for Acquire had a await_completion in the exit, so I didn't need a thread at all.  However, I'm still not quite sure how to tell the acquisition manager to stop trying to get the missing images so I can close the bridge on the Acquisition object and discard it.  Should this be done via the studio acquisition manager object?
