### ISSUE TITLE
Micro-Manager events in pycromanager

### ISSUE THREAD

**Issue by wl-stepp** [micro-manager/pycro-manager#330]
Hi everyone,

is there a way to connect to the events emitted internally by micro-manager like DefaultAcquisitionStartedEvent and XYStagePositionChangedEvent in python using pycromanager? I would like to use some GUIs developed with PyQt to work alongside the default Micro-Manager Java GUI and have interaction between the two.
I think I saw that pymmcore allows to connect to events, but I did not see an obvious way to then interact with the Java GUI. I have started to implement something in Java using additional zmq sockets, I then connect to those from python. This still feels pretty hacky, so I was wondering if I was missing something here.

Thanks.

**Comment by henrypinkard** [comment]
I don't think so. The Java python bridge used by pycromanager doesnt support calls from java to python. Doing so would require keeping track of Python objects on the java side, which would add a lot of complication.

The quickest way to get something like this I can think would also be a zmq hack, where you listen for events on the java side and then send them out through a push socket to a pull socket on python side. This is essentially what pycromanager image processors do, so you might be able to make use of some of that code.

I don't know for sure, but I suspect that if pymmcore does this its implementing in its own wrapper on the core that has python code that listens for events. This would not be part of pycromanager

**Comment by wl-stepp** [comment]
Ok, thanks.
I will see where I go with this. I will update here if I get it to work stable enough so that someone else might be interested.

**Comment by wl-stepp** [comment]
Hey,
I came up with a solution to this that works OK for us [pymm_eventserver](https://github.com/LEB-EPFL/pymm-eventserver). Definitely room for improvement and I have only implemented/activated the events that we are interested in at the moment. This runs a second ZMQ server, so that is one thing that might not be optimal. Also, to not keep all the images in memory that are sent over when a new image arrives, I am not saving those on the java side. Meaning that there is no access to their methods etc. later.

**Comment by henrypinkard** [comment]
Glad you were able to figure it out. I don't think there's anything wrong with a second ZMQ server, provided you run it on a different port. You may even be able to instantiate the second one from the python side, if you're not already.

Btw I think that link has private access

**Comment by wl-stepp** [comment]
Thanks for the hint, just changed it to public.
Yes, it's on a different port. Is there a specific reason for pycro-manager to communicate via port 4827?
I will add some more granularity to choose which events to send on the java side etc.

**Comment by henrypinkard** [comment]
That looks very cool. If you want, I think it could nice to link to that from [this page](https://pycro-manager.readthedocs.io/en/latest/calling_java.html) in the docs as it might be useful for others as well

> Is there a specific reason for pycro-manager to communicate via port 4827?

If i recall correctly the unused ports had numbers between 4000-8000, or something close to that and I arbitrarily chose 4827 because it seemed random looking enough that it was less likely to be used by other applications. But you should be able to swap in another number if you want. Probably best to avoid 4828-4840ish though, because pycro-manager can use many other ports when running `Acquisition`s

**Comment by wl-stepp** [comment]
Thanks, I created a pull request with a small addition to the page mentioned. I might just go for port 5827 then in the end.
