### ISSUE TITLE
Hardware acquisition hook only entered when specifying interval and exposure time?

### ISSUE THREAD

**Issue by romanbarth** [micro-manager/pycro-manager#332]
Dear pycro team,

first of all: I love pycro and what it can do. Absolutely perfect to incorporate a uManager-like tool into an existing custom GUI to manage my acquisition. Thank you for that great piece of software!

I have a question though:
For my experiment, I would like to have the freedom to change the exposure time for various channels that I want to image. Brief example:
ch1   100 ms
ch2    50 ms
ch3    25 ms
... and repeat

When specifying events for acquisition, I noticed I can do it two ways:
1) by explicitely stating the exposure time (possibly varying for different axes (an axis here would be time and channel):
`   exposureTime  = 100`
`events.append({
        'axes': {'time': t}, 'exposure': exposureTime
        })`
2) by giving the exposure as additional event axis:
`exposureTime  = 100`
`events.append({
        'axes': {'time': t,
        'exposure': exposureTime
                            }},
        })`
and then changing the exposure time manually in a acquisition hook:
`with Acquisition(directory=os.path.dirname(savepath), name='deleteme', pre_hardware_hook_fn=pre_hardware_hook_fn, show_display=True) as acq:`
    `acq.acquire(events_min_start_time_exposure)`
and
`def pre_hardware_hook_fn(event, bridge, event_queue):`         
                `mmc = bridge.get_core()`
                `mmc.set_property("Camera", 'Exposure', event[continuousCounterHardware]['axes']['exposure'])`
`return event`
... and `continuousCounterHardware` set appropriately to loop through the events of course.

While seemingly doing the same thing, I noticed that method 1) keeps calling the pre_hardware_hook_fn for every time point as expected, yet method 2) calls it only once (but calls a potential image_process_fn repeatedly).

Is this intended? I would like to have method 2) but with a repeated call to some acquisition hook that allows me to update some other piece of hardware before every frame... Is that possible?

Attached is a complete minimal example (acqTool_minimal_original_share_noTiming.py (as txt)) and its output on my machine (acqTool_minimal_original_share_output_demo.txt; the uManager demo config should run this).

[acqTool_minimal_original_share_output_demo.txt](https://github.com/micro-manager/pycro-manager/files/7527358/acqTool_minimal_original_share_output_demo.txt)
[acqTool_minimal_original_share_noTiming.txt](https://github.com/micro-manager/pycro-manager/files/7527359/acqTool_minimal_original_share_noTiming.txt)

**Comment by henrypinkard** [comment]
It sounds like method 2 is doing hardware sequencing and converting all the individual events as one long sequence of events in order to achieve faster speeds. You could verify this by printing the event argument in the one call of the hook_fn.

But if what you want is to have a separate exposure axis, I don't think you should need to use a hook. You can combine the two methods. Also, it looks like you're using the exposure time as the axis index, which is a little weird. Would be more standard to index each exposure (e.g. 0 means 100ms, 1 means 200 ms, 2 means 400 ms, etc.). Try something like this:

```python
exposure_ind = 0 #change this as needed 
{ 'axes': {'time': t, 'exposure_index': exposure_ind}, 'exposure': exposureTime }
```

**Comment by romanbarth** [comment]
Hi Henry,

thank you very much for your comments! Sorry for my slow reply, I was out of the lab for a few days...

You're right, method 2 indeed gives all events as one list, thus doing hardware sequencing under the hood.

I tried your suggestions of giving the 'smallest denominator' of all exposure times to the key 'exposure' and then adding a exposure_index axis (btw, is "exposure_index" a somewhat special key for pycro?). 
Unfortunately I haven't managed to get that to work, the camera always takes the exposure time from the 'exposure' key. The 'exposure_index' axis gets properly transmitted as checked within a hardware hook, but then how does pycro know to multiply the set exposure time by the index? I can see how to implement that using a hardware hook, but how would it work without (as you suggested)?

One more question: For switching channels, I need a hardware hook to tell my AOTF which channel to open/close. However, I cannot figure out how to repeatedly call a hardware hook while also enabling hardware sequencing. Can this be achieved at all? Whenever I repeatedly call a hardware hook (e.g. using method 1 above), my timing is off.

**Comment by henrypinkard** [comment]
> (btw, is "exposure_index" a somewhat special key for pycro?).

No, you can use whatever

> the camera always takes the exposure time from the 'exposure' key.

This is the intended behavior


> how does pycro know to multiply the set exposure time by the index

This is not what is happening. The index is just to distinctly identify images

>  However, I cannot figure out how to repeatedly call a hardware hook while also enabling hardware sequencing. Can this be achieved at all?

No, these are mutually exclusive. Sequenceing takes the computer out of the loop to achieve speed gains
