### ISSUE TITLE
Bridge: Double class/double primitve confusion

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#335]
```
from pycromanager import Bridge
bridge = Bridge()

image = bridge.get_studio().acquisitions().snap().get(0)
builder = bridge.get_studio().acquisitions().generate_metadata(image, False).copy_builder_preserving_uuid()
builder.elapsed_time_ms(100.)
```

**Comment by ilyasdc** [comment]
Hi @henrypinkard , we're facing a similar issue pertaining to metadata (we want to change them) :
You can also reproduce such issue by directly invoking the object: 
```python
bridge.construct_java_object('java.lang.Integer',args=[int(42)])
```
The returned `serialized_object` is not of the right class:
```python
>>> serialized_object
{'type': 'primitive', 'value': 42}
```

I tried to directly pass the value to the builder but as you noticed it failed even when adding `java.lang.Integer` to the `_JAVA_TYPE_NAME_TO_PYTHON_TYPE ` and `_JAVA_TYPE_NAME_TO_CASTABLE_PYTHON_TYPE`

**Comment by henrypinkard** [comment]
Could you say/post a little bit more about where this ends up going wrong? I think in a lot of cases auto converting `Integer` to `int` on return is probably the desired behavior.

**Comment by ilyasdc** [comment]
> Could you say/post a little bit more about where this ends up going wrong? I think in a lot of cases auto converting `Integer` to `int` on return is probably the desired behavior.

Hi, sorry I should have explained when this fails, the `SummaryMetaData.Builder` signature states  `java.lang.xx` objects for the setters (ex: `zStepUm` https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmstudio/org/micromanager/data/SummaryMetadata.Builder.html ). When using the script panel this works because Java auto cast to the proper type (as far as I know).

**Comment by henrypinkard** [comment]
Gotcha. I think then the solution is to the Java side of the bridge such that when you send in a python `int` as an argument it autoconverts to `Integer` as needed. Does that sound right to you?

**Comment by ilyasdc** [comment]
Agreed, it would solve the problem.

**Comment by henrypinkard** [comment]
Ended up needing a bunch of changes, but fixed now:

https://github.com/micro-manager/pycro-manager/pull/374

**Comment by ilyasdc** [comment]
Hi @henrypinkard , I tried your fix and I can't make it work. I get a null pointer exception when I try to use double on the metadatabuilder, your example also leads to the same behaviour.  Do you know what happens ? ( I include the jupyter notebook, latest pycro-manager version 0.16.4 and I also pulled latest micro-manager version)
[nullpointer.ipynb.zip](https://github.com/micro-manager/pycro-manager/files/8171348/nullpointer.ipynb.zip)
