### ISSUE TITLE
Micro Magellan Error

### ISSUE THREAD

**Issue by kwagoner94** [micro-manager/pycro-manager#337]
Hi,

I followed the instructions on GitHub for installing Micro-Magellan, but when I attempt to use it the log appears and states 
"main.java.org.micromanager.plugins.magellan.json.JSONException: JSONArray[0] not found." along side a long list of "at mauin.java.org.micromanger......." lines. How can I get around this issue. My Micro-Magellan file in is my mmplugins file for micromanager 2.0 gamma

Thank you very much

**Comment by henrypinkard** [comment]
You shouldn't need to install Magellan. It is automatically bundled with Micro-Manager2.0
