### ISSUE TITLE
Possible bug in start_headless

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#338]
### Bug report

**Bug summary**
I have a config file for a Zyla camera using the Andor sCMOS Camera driver that loads fine using micromanager directly.  I have the latest nightly build of micromanager and pycromanager and am running on Windows 10.

However, when I try using the same config file using start_headless, I get the following error:

`
Exception: java.lang.Exception: Line 7: Device,Andor sCMOS Camera,AndorSDK3,Andor sCMOS Camera
Failed to load device "Andor sCMOS Camera" from adapter module "AndorSDK3" [ Failed to load device adapter "AndorSDK3" [ Failed to load module "C:\Program Files\Micro-Manager-2.0\mmgr_dal_AndorSDK3.dll" [ The module, or a module it depends upon, could not be found (Windows error: The specified module could not be found.) ] ] ]
`

This smells a little the mmgr driver not being able to find the vendor specific dll.  Is this a bug, or am I doing something wrong?

Thanks,

Carl

**Comment by henrypinkard** [comment]
Yeah thats a possibility. Not sure why this would happen with Pycro-Manager and not Micro-Manager, as they use the exact same code for starting up the core. see here: https://github.com/micro-manager/pycro-manager/blob/9ac6ffd968cf692f1d366c943eb589a7e132d77e/pycromanager/acquire.py#L18

Maybe the andor device adapter writes something to the core log about why it failed. If not, I'm not sure what to do besides setting up the device adapter dev environment and trying to find where it goes wrong, or contacting Andor.

**Comment by carlkesselman** [comment]
Its not generating a log file at all.

I'm going to try loading in the module via the API and see if I can get any more information.

**Comment by carlkesselman** [comment]
Ok.  Figured this out.  It has to do with the search path.  I was able to solve this by adding the micromanager search path to the system path variable in windows and then everything is ok.    So this is not a bug, but actually a known issue with starting micromanager outside of the GUI.  Similar problem exists when running micromanager under Eclipse.  

Might be worth documenting this somewhere?

Carl;

**Comment by henrypinkard** [comment]
Yeah definitely. I haven't put up the headless documentation yet, but I'll definitely include that when I do.

Do you think there's any way to do this at runtime with the headless launcher?

**Comment by carlkesselman** [comment]
Yes, probably.  I think you can pass the environment explicitly to python popen.  You could get the environment, look at the path and hack it.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Profesor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine
Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.******@***.***>
Web: http://www.isi.edu/~carl










On Dec 6, 2021, at 11:58 AM, Henry Pinkard ***@***.******@***.***>> wrote:



Yeah definitely. I haven't put up the headless documentation yet, but I'll definitely include that when I do.

Do you think there's any way to do this at runtime with the headless launcher?

**Comment by henrypinkard** [comment]
Okay good to know. If you ever want to give it a shot, PRs welcome

**Comment by carlkesselman** [comment]
Actually, looks like I may be wrong:

For Windows, see the documentation of the lpApplicationName and lpCommandLine parameters of WinAPI CreateProcess, and note that when resolving or searching for the executable path with shell=False, cwd does not override the current working directory and env cannot override the PATH environment variable. Using a full path avoids all of these variations.

I will have to test to see what actually happens with ddl load path.

Carl



----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Profesor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine
Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.******@***.***>
Web: http://www.isi.edu/~carl










On Dec 6, 2021, at 12:05 PM, Henry Pinkard ***@***.******@***.***>> wrote:



Okay good to know. If you ever want to give it a shot, PRs welcome

**Comment by henrypinkard** [comment]
Did you ever get clarity on this? As far as I can tell headless mode works when you pass it the MM install directory, so I'm not sure why additional paths would be needed

**Comment by henrypinkard** [comment]
Fixed by https://github.com/micro-manager/pycro-manager/issues/420 I think
