### ISSUE TITLE
Clean termination of ongoing acquisition

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#340]
Not sure if this is a pycromanager or micromanager question.

I have a MDA running that I would like to terminate prior to completion (its being externally triggered). I am not using a context manager, but rather creating the acquisition object and then sending its event queue a None to shut down. 

Is there a way to tell micromanger to stop the acquision in such a way that the pycromanager object will cleanly shut down?

Thanks,

Carl

**Comment by henrypinkard** [comment]
If im understanding correctly, sending the `None` event is the way to do this that will make it shut down properly

**Comment by carlkesselman** [comment]
This still leaves two threads running in my case: ImageProcessor and the AcquisitionHook for the post camera hook (these are two hooks I specify in my Acquisition.  This means that I cannot exit the program using sys.exit.

I tried using await_completion, but that hangs up waiting for the remote acquisition to close down.

**Comment by henrypinkard** [comment]
Many fixes in the intervening time make me thing this is no longer an issue. Feel free to reopen if not
