### ISSUE TITLE
How to aquire images continuously?

### ISSUE THREAD

**Issue by phantomlsh** [micro-manager/pycro-manager#342]
I would like to continuously acquire images as fast as possible, and use a function to process that. How can I set up such an acquire event? Is there any example?

**Comment by phantomlsh** [comment]
Maybe I should use `core.start_continuous_sequence_acquisition()`? Is it efficient enough to acquire images fast?

**Comment by henrypinkard** [comment]
`Acquisition` class is calling that under the hood. 

Check out:

https://pycro-manager.readthedocs.io/en/latest/hardware_triggering.html

For on the fly processing youll be limited to 100 MB/s (see supplementary info in the publication for more info)
