### ISSUE TITLE
How to move the XY stage without acquisition  

### ISSUE THREAD

**Issue by kidantad** [micro-manager/pycro-manager#343]
Hello. How can I move my xy stage in a set sequence(for instance from 0-5 at 0.1 interval) without taking an image. I tried to implement "import org.micromanager.MultiStagePosition;" but I get the error that there is no module named 'org'.  In the end, I want to be able to run a section of code and see my xy stage move in a given sequence without the camera turning on. To create my sequence for the x positions, I did the following: 
nSteps =5
x_step =0.1
x_end = nSteps*x_step
x_sequence = np.arange(0, x_end + x_step, x_step).reshape(nSteps+1,1)

Thanks

**Comment by henrypinkard** [comment]
[`core.set_xy_position()`](https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmcorej/mmcorej/CMMCore.html#setXYPosition-double-double-)

**Comment by kidantad** [comment]
Thank you for replying, I'm fairly new to pycromanager. I actually tried that before, but with the set of parameters that I mentioned before, when I use core.set_xy_position(), I get error: Exception: Incorrect arguments. 
Expected double, double or java.lang.String, double, double 
Got 

I just want to make sure that I don't have to add any more parameters. Thanks

**Comment by kidantad** [comment]
I am fairly new to pycromanager so please correct me if I'm wrong, but the above code allows me to move the xy stage to a specific position. However, for my application, it is critical that I get to the final x and y position by moving 0.1um each time. How can I make sure of that? if I put x_sequence as the x position inside the parenthesis, I get the key Error 'double' 

Thanks

**Comment by henrypinkard** [comment]
Can you just call it multiple times?

Also, these are more micro-manager usage questions, rather than pycro-manager questions. A better place for them would be [the micro-manager part of the image.sc forum](https://forum.image.sc/micro)

**Comment by kidantad** [comment]
No, because I have minimum 200 positions. Okay, thank you.
