### ISSUE TITLE
DAQ triggering

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#346]
@dpshepherd , You mentioned in [this](https://forum.image.sc/t/loading-micromanager-tif-series-into-napari/62398/16) thread that pycro-manager has advantages and disadvantages for your DAQ triggering setup. Could you elaborate a bit on what those are?

**Comment by dpshepherd** [comment]
@henrypinkard 

There are two main issues for us:

1. For our purposes, having fast on-the-fly processing in Python (with potential feedback to hardware) is helpful. We can do this in Python at the full speed of the hardware without the Java <-> Python bridge speed limitation.
2. We still get ZMQ socket cleanup errors when using a `post _camera _hook` in the acquisition. This eventually crashes our big runs where we need to call the acquisition engine many times because we are running fluidics or other Python code in between microscope calls. We don't have this issue in a pure Python implementation.

**Comment by henrypinkard** [comment]
Got it. Good to know. 

I'll continue to keep an eye out for what might be causing (2).

For (1), I think this is something that could be addressed with a future update to the core. In the mean time though, in case it is helpful, `Acquisition`s can accept a `storage_monitor_callback_fn` which allows you to read the data from natively disk in python as soon as NDTiff finishes writing it. You'd still have the overhead of writing then reading, but would probably be much faster than the bridge with your hardware

**Comment by henrypinkard** [comment]
I'm keen on trying to fix (2). Is this the issue described in #286, where you get a ZMQ error randomly after running hundreds of acquisitions? Or was it #169? I just checked this and it seems to be fixed

**Comment by dpshepherd** [comment]
I believe it is the same as #286.

Also, it doesn't take hundreds. It can occur within tens sometimes if we are using `post_camera_hook`. It also occurs if we leave the same copy of Micromanager open for long periods of time and run a bunch of different Pycromanager acquisitions (with a camera hook) on different days.  The pattern is always that we get this error randomly when running an `Acquisition  using a  `post_camera_hook`,

```python
Exception ignored in: <function JavaObjectShadow.__del__ at 0x00000280A6DE2160>
Traceback (most recent call last):
  File "C:\Users\qi2lab\miniconda3\envs\OPM\lib\site-packages\pycromanager\core.py", line 503, in __del__
    self._close()
  File "C:\Users\qi2lab\miniconda3\envs\OPM\lib\site-packages\pycromanager\core.py", line 493, in _close
    self._socket.send(message)
  File "C:\Users\qi2lab\miniconda3\envs\OPM\lib\site-packages\pycromanager\core.py", line 107, in send
    self._socket.send_multipart(message_parts)
  File "C:\Users\qi2lab\miniconda3\envs\OPM\lib\site-packages\zmq\sugar\socket.py", line 591, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "C:\Users\qi2lab\miniconda3\envs\OPM\lib\site-packages\zmq\sugar\socket.py", line 541, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 759, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: not a socket
```

which eventually leads the error noted in #286, `zmq.error.ZMQError: Permission denied`.

When we get the Permission denied error, we have to shutdown Micromanager and restart it before we can run a `Acquisition` again.

**Comment by henrypinkard** [comment]
I still haven't been able to reproduce it myself.

But since it occurs intermittently and randomly it sounds like a race condition between different threads. That error I think comes from the destructor of a python shadow of a Java object, which may happen because the bridge gets garbage collected before object shadows that depend on it. Not sure how this could be happening, but I added a bunch more thread safety stuff to try to make sure things shut down in the proper order (https://github.com/micro-manager/pycro-manager/pull/347).

Can you see if the problem persists in `0.14.2`?

**Comment by dpshepherd** [comment]
Should be able to do some testing this week.

For `storage_monitor_callback_fn`, are there any use examples? Looking at the [code](https://github.com/micro-manager/pycro-manager/blob/13e41e4f3b679896e09796beaf97c36296e1877b/pycromanager/acquire.py#L379), it's clear we need to define a function that ingests the axes of the just added data. How do we access the current dataset within that function without global variables?

Specifically we would want to:
1. have access to the dataset
2. parse the metadata of just added images (through the Axes passed to the function)
3. load an image that meets criteria back into memory (e.g. a specific channel)
3. perform some computations on image
4. save image back to disk into a different data structure that we use later on in the pipeline

If we can get that working we can remove some (and potentially all) of our sequential `Acquisition` calls.

**Comment by henrypinkard** [comment]
The example below does pretty much that. Given the speed at which your systems produce images, you might want to pass off the computation and I/O onto a different thread(s) so the whole thing doesn't get too backed up.

 > How do we access the current dataset within that function without global variables?

As you can see below, you do have a global variable with the way its currently set up. `acq` is defined in the function before anything gets bound to it. Somehow this just works in python. I'm not sure if its the best programming practice. It'd be easy enough to just change the signature to `storage_monitor_fn(axes, dataset)`. Now that I think about it that's probably more consistent with the syntax of how the hook functions work

```python
from pycromanager import Acquisition, multi_d_acquisition_events


def storage_monitor_fn(axes):
    if axes['channel'] == 0:
        dataset = acq.get_dataset()
        pixels = dataset.read_image(**axes)
        # Do something with image pixels/metadata

dir = '/Users/henrypinkard/tmp/'
with Acquisition(directory=dir, name="tcz_acq", debug=False,
                 storage_monitor_callback_fn=storage_monitor_fn) as acq:
    events = multi_d_acquisition_events(
        num_time_points=5,
        time_interval_s=0,
        order="tcz",
    )
    acq.acquire(events)


```

**Comment by dpshepherd** [comment]
Thanks! A quick test shows that if I run the above script with or without `image_saved_fn=image_saved_fn`, I can't delete the acquisition folder once the python script is running if Micromanager is still running. Once I close Micromanager, I can delete the folder.

I think this is a regression?

**Comment by henrypinkard** [comment]
Hmmm okay, I do'nt think that is related to `image_saved_fn` because its been in the codebase for a while. 

It sounds like the dataset not being properly released when finished in the acquisition engine. I'll take a look

**Comment by dpshepherd** [comment]
It doesn't happen if `show_display = False`. With `show_display = True`, I close the `NDViewer `window and still can't delete the folder.

**Comment by dpshepherd** [comment]
It says "Finished".  This is using the demo config on my Windows 11 laptop. I'll check with a lab Windows 10 machine.
