### ISSUE TITLE
Image acquisition slow in MDA and snap() 

### ISSUE THREAD

**Issue by jonfouch** [micro-manager/pycro-manager#367]
Hi all, 

I'm trying to perform simple image acquisition with pycromanager and find acquisition very slow. It is the case with both multi_d_acquisition_events or snapping through the core (See code below). Acquisition works fine in Micro-manager. 

Do you have a clue where the communication could slow down ? 

Thanks for your help,

```
from pycromanager import Acquisition, multi_d_acquisition_events
import time

dir_im = 'C:/Users/Jon_LBD/Desktop/Platine Controle/images'
start = time.time()
with Acquisition(directory=dir_im, name=str(time.time())) as acq:
    events = multi_d_acquisition_events(num_time_points=100, time_interval_s=0.1,order='t', channel_exposures_ms=20)
    acq.acquire(events)
end = time.time()
print('\t{}'.format(end - start))
```

Output is '35.92000389099121' seconds instead of 10 seconds.

Same with core.snap()

```
from pycromanager import Bridge
import time
import numpy as np

bridge = Bridge()
core = bridge.get_core()
exposure = core.get_exposure()
auto_shutter = core.get_property('Core', 'AutoShutter')
core.set_property('Core', 'AutoShutter', 0)   
core.set_exposure(20)

while True:
    start = time.time()
    core.snap_image()
    end = time.time()
    print('\t{}'.format(end- start))

```
Output is '0.3058054447174072' second

**Version Info**

 * Operating system: Windows 10
 * pycromanager version: 0.12.9
  * MicroManager version: 2.0.0-gamma1 20210602
  * Python version: 3
  * Python environment : jupyter notebook

**Comment by jonfouch** [comment]
> Do you mean if you just call `snap_image()` in micro-manager (like in a beanshell script) its fast, but not in pycro-manager? That would be weird since theyre calling the same function.

Sorry, no I meant if i perform a normal multi-dimensional acquisition in micro-manager, I get the required framerate, but not when using pycro-manager.



> I don't think this is related to the speed of `snapImage`

Since this line shows up multiple times in the Core log for each image taken, I was thinking this could be the source of the slow-down. Do you have an other idea ?

**Comment by henrypinkard** [comment]
I think I need to get a little more information. Can you try:

1) Try running the equivalent beanshell script in micromanager with  "tools--script panel", and see how it compares to your script:

```
exposure = mmc.getExposure();
mmc.setProperty("Core", "AutoShutter", 0);
mmc.setExposure(20);

time = System.currentTimeMillis();
for (i = 0; i < 100; i++) {
	newtime = System.currentTimeMillis();
	print(newtime - time);
	time=newtime;
	mmc.snapImage();
}
```

2) Try running same two scripts, but using the micro-manager demo configuration

**Comment by jonfouch** [comment]
Hi Henry, 
thanks for your help.

> 1. Try running the equivalent beanshell script in micromanager with  "tools--script panel", and see how it compares to your script

So this leads to the same issue : 300 ms on average between snaps


> Try running same two scripts, but using the micro-manager demo configuration. 

This gives 100 ms on average between snaps.

**Comment by henrypinkard** [comment]
Okay, then this is not related to pycromanager. It has something to do with your camera device adapter. You should open an issue on the main micromanager repository
