### ISSUE TITLE
as_array verbose explanation

### ISSUE THREAD

**Issue by kdmarchuk** [micro-manager/pycro-manager#368]
Hi Henry, I have some minor confusion on how the data is opened into the Dask array.

### Problem
https://pycro-manager.readthedocs.io/en/latest/apis.html#dataset

The documentation for `as_array()` states:
"Read all data image data as one big Dask array with last two axes as y, x and preceeding axes depending on data."

There is no explanation as to how the dimensions are added depending on the acquisition parameters.

### Suggested Improvement
Can you please add examples and/or the logic of how adding, z with t, z without t, t without z, etc... are packed? 

Thanks!

**Comment by henrypinkard** [comment]
Its in the description of the parameters:

"The order of axes supplied in this list will be the order of the axes of the returned dask array"

**Comment by kdmarchuk** [comment]
Sorry. Should have been more clear. If you're unsure what axes are in the file (for a file converter), is there a logic?

**Comment by henrypinkard** [comment]
All good. Call `dataset.axes` which should list all of them. Some of them might be singleton, like it always adds a channel axis or something like that
