### ISSUE TITLE
Memory ramps up with repeated calls to getImage()

### ISSUE THREAD

**Issue by ilyasdc** [micro-manager/pycro-manager#371]
### Bug report

**Bug summary**

Simple repeated calls to getImage consume more and more memory at some points the loop fails ( we set the MM memory limit to 10GB)

**Code for reproduction**

```python
from pycromanager import Bridge

input_dir= "somefolder"

with Bridge(convert_camel_case=False,debug=False) as bridge: 
    mm = bridge.get_studio()
    stack = mm.data().loadData(input_dir,True)
    coords = mm.data().getCoordsBuilder().z(0).time(0).channel(0).stagePosition(0).build()
    for i in range(5000): 
        stack.getImage(coords) 
```

The same script on the script panel doesn't consume as much memory. 
Clicking on the imageJ bar at the end of the loop to garbage collect works though.

**Expected outcome**

The image is garbage collected on the java side and the memory doesn't explode

**Actual outcome**

<img width="625" alt="image" src="https://user-images.githubusercontent.com/44259072/156060837-501ef946-2607-4496-9731-aa1d80e9f6a2.png">

**Version Info**

  * Operating system: Linux
  * pycromanager version: 0.16
  * MicroManager version: 2.0.x dev
  * Python version: Python 3.9.5
  * Python environment: jupyter notebook

**Comment by henrypinkard** [comment]
Can you post an example dataset to use with the script?

**Comment by ilyasdc** [comment]
> Can you post an example dataset to use with the script?

Hi, yes, sure, here it is, generated with the demo microscope:  https://wormhole.app/v05WM#bOhA1bhmXOGVDra-_0o6-w

**Comment by henrypinkard** [comment]
I just tested it out. I don't think there's any bug here, since the Java side garbage collector runs when you click the graph, which means there isn't a memory leak. You can always force the Java GC to run with: `bridge.get_java_class('java.lang.System').gc()`

**Comment by ilyasdc** [comment]
> I just tested it out. I don't think there's any bug here, since the Java side garbage collector runs when you click the graph, which means there isn't a memory leak. You can always force the Java GC to run with: `bridge.get_java_class('java.lang.System').gc()`

Hi @henrypinkard, unfortunately this isn't solved. My example was actually not the best one since, as you noticed, if the bridge is closed, the memory can be released. However if you don't use a context manager the garbage collector calls don't clean anything.

The same script running as beanshell works reasonably well and memory doesn't jump up
![image](https://user-images.githubusercontent.com/44259072/156416603-e4d95a93-6194-43ad-a7a4-89fde19086ce.png)

Is there another way to get image (or even substacks) obtained from an MM acquisiton without using too much memory ?

**Comment by henrypinkard** [comment]
Can you post code where the problem persists?

> Is there another way to get image (or even substacks) obtained from an MM acquisiton without using too much memory ?

If you use the [high level acquisition API](https://pycro-manager.readthedocs.io/en/latest/acq_overview.html), which is designed for python, you can avoid these problems. But it sounds like you you've already acquired this data with the MDA gui. In that case it might be easier to just read them as normal TIffs, or you could find an OME-tiff reader that works through python.

**Comment by ilyasdc** [comment]
> 

Hi Henry,

Here's the code and the data: [Test_multid.zip](https://github.com/micro-manager/pycro-manager/files/8172305/Test_multid.zip)
```
from pycromanager import Bridge

input_dir= "xxx/Test_multid/_1/"

bridge = Bridge(convert_camel_case=False,debug=False) 
mm = bridge.get_studio()
stack = mm.data().loadData(input_dir,True)
coords = mm.data().getCoordsBuilder().z(0).time(0).channel(0).stagePosition(0).build()
for i in range(5000): 
    stack.getImage(coords) 
bridge.get_java_class('java.lang.System').gc()
```

The call to the garbage collector doesn't work, nor the click on the imageJ bar. Only do they work after the bridge has been closed.

We know about the alternatives (tifffile, aicsimageio) but to my knowledge they are horribly slow for relatively small datasets (100-200GB). People in my group use mostly the multi-dimensional acquisition of MM with some custom script that allows to correct for slide drift I'm not sure your acquisiton engine is an alternative. I've seen your code meant to convert : https://pycro-manager.readthedocs.io/en/latest/application_notebooks/convert_MM_MDA_data_into_zarr.html but how about keeping all the metadata ?

Thanks for your responsiveness anyway !

**Comment by ilyasdc** [comment]
Hi @henrypinkard, upon further investigation I could avoid the mentioned issue, an explicit call to the `._close()` (or __del__()) method allows the garbage collection (as expected), however deleting the python  object doesn't. This can be explained by the fact that if one gets the reference count of the object( `sys.getrefcount`) you can see that there are 3 references, hence a single del won't do it. I don't know if this can be easily solved (or should)

**Comment by henrypinkard** [comment]
I just changed some of the APIs yesterday, and now the following code works as expected for me. Everything cleans up, no need to explicitly call destructors

```python
from pycromanager import Studio, JavaClass

input_dir= "/Users/henrypinkard/Downloads/Test_multid"

mm = Studio(convert_camel_case=False)
stack = mm.data().loadData(input_dir,True)
coords = mm.data().getCoordsBuilder().z(0).time(0).channel(0).stagePosition(0).build()
for i in range(5000):
    stack.getImage(coords)
JavaClass('java.lang.System').gc()
```

By the way, it is in general helpful when going back and forth on these things if you always post your full code every time you try something new. For example, its not clear to me what class your counting references on or calling `._close()` on

> We know about the alternatives (tifffile, aicsimageio) but to my knowledge they are horribly slow for relatively small datasets (100-200GB). 

It may be faster, with pycromanager, but not faster than 100-200 MB/s with this mechanism

> People in my group use mostly the multi-dimensional acquisition of MM with some custom script that allows to correct for slide drift I'm not sure your acquisiton engine is an alternative. 

It should be. The PM acquisition engine was designed to be able to do everything the MM one can do and more. It will eventually replace the one in MM

> I've seen your code meant to convert : https://pycro-manager.readthedocs.io/en/latest/application_notebooks/convert_MM_MDA_data_into_zarr.html but how about keeping all the metadata ?

Its possible. I dont know what the call to the Studio api is off the top of my head though
