### ISSUE TITLE
Update build system

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#377]
from @ianhi (https://github.com/micro-manager/pycro-manager/pull/375):

move everything in setup.py into setup.cfg

specify the build requirements in pyproject.toml
eliminate setup.py

remove requirements.txt and instead use the concept of extra_requires

like so: https://github.com/tlambert03/pymmcore-plus/blob/62416c797ec40a7c7614fc16061f1928ced8382d/setup.cfg#L44-L61

build system stuff, you can get rid of setuptoolsscm bc you don;t use that.

https://github.com/tlambert03/pymmcore-plus/blob/62416c797ec40a7c7614fc16061f1928ced8382d/pyproject.toml#L1-L3

**Comment by ianhi** [comment]
For setting the versoin in setup.cfg you should do this: https://github.com/micro-manager/pymmcore/blob/c92463f9e8eee3ced996d2b891a4a44ed9de0ae5/setup.cfg#L3
