### ISSUE TITLE
autofocusing with pycromanager

### ISSUE THREAD

**Issue by BDImagingLab** [micro-manager/pycro-manager#394]
Hi,

When I modify the example from the note book as the following, 
with Acquisition(directory=save_dir, name=save_name, post_hardware_hook_fn=hook_fn) as acq:
    events = multi_d_acquisition_events(
        num_time_points=20, time_interval_s=0)
    acq.acquire(events)

it gives me error like this:
Warning (from warnings module):
  File "C:\Program Files\Python39\lib\site-packages\pycromanager\acquisitions.py", line 98
    warnings.warn("exception in acquisition hook: {}".format(e))
UserWarning: exception in acquisition hook: list indices must be integers or slices, not str

Any solution for this?
Thank you.

**Comment by henrypinkard** [comment]
what hook function are you using?

**Comment by BDImagingLab** [comment]
Hi Henry,

Thank you for replying the message. I'm using the example script that you provided in this link. https://pycro-manager.readthedocs.io/en/latest/application_notebooks/Single_shot_autofocus_pycromanager.html 

My modification is as the following. My purpose is to do autofocusing based on the image captured by the camera. It's similar approach as that in the link above.

from pycromanager import Acquisition, multi_d_acquisition_events
import numpy as np

### TODO:
# model = some_trained_model

save_name = 'autofocus_test'
save_dir = 'C:/Users/bind/Desktop/Temporal Storage of data/Bin/test data'

import numpy as np


i = 0
# This hook function will do the autofocusing
def hook_fn(event):

    if not hasattr(hook_fn, 'time_index'):
        hook_fn.time_index = event['axes']['time']

    # Only apply this focus correction at the beginning of a new time point (except the first one)
    if event['axes']['time'] != hook_fn.time_index:
        print('there is axes')
        

    # get the Micro-Manager core
    from pycromanager import Core
    core = Core()
    #core = bridge.get_core()

    core.snap_image()
    tagged_image = core.get_tagged_image()
    # pixels by default come out as a 1D array. We can reshape them into an image
    global pixels
    pixels = np.reshape(tagged_image.pix,
                            newshape=[tagged_image.tags['Height'], tagged_image.tags['Width']])

    # use the image to predict focus correction
    #focus_correction = model.predict(pixels)
    # Apply the predicted correction
    z_device_name = core.get_focus_device()
    #core.set_position(z_device_name, core.get_position(z_device_name) + focus_correction)

    # Keep track of last time point on which autofocus ran
    hook_fn.time_index = event['axes']['time']
    
    return event

events = multi_d_acquisition_events(
    num_time_points=20, time_interval_s=0)
# This acquisition runs with the Micro-Manager demo config
with Acquisition(directory=save_dir, name=save_name, post_hardware_hook_fn=hook_fn) as acq:
    events = multi_d_acquisition_events(
        num_time_points=20, time_interval_s=0)
    acq.acquire(events)

**Comment by BDImagingLab** [comment]
Sorry the code was very messy. Here is the clean version.

from pycromanager import Acquisition, multi_d_acquisition_events
import numpy as np

save_name = 'autofocus_test'
save_dir = 'C:/Users/bind/Desktop/Temporal Storage of data/Bin/test data'

def hook_fn(event):

    if not hasattr(hook_fn, 'time_index'):
        hook_fn.time_index = event['axes']['time']

    # Only apply this focus correction at the beginning of a new time point (except the first one)
    if event['axes']['time'] != hook_fn.time_index:
        print('there is axes')
        

    # get the Micro-Manager core
    from pycromanager import Core
    core = Core()
    #core = bridge.get_core()

    core.snap_image()
    tagged_image = core.get_tagged_image()
    # pixels by default come out as a 1D array. We can reshape them into an image
    global pixels
    pixels = np.reshape(tagged_image.pix,
                            newshape=[tagged_image.tags['Height'], tagged_image.tags['Width']])

    # use the image to predict focus correction
    #focus_correction = model.predict(pixels)
    # Apply the predicted correction
    z_device_name = core.get_focus_device()
    #core.set_position(z_device_name, core.get_position(z_device_name) + focus_correction)

    # Keep track of last time point on which autofocus ran
    hook_fn.time_index = event['axes']['time']
    
    return event


with Acquisition(directory=save_dir, name=save_name, post_hardware_hook_fn=hook_fn) as acq:
    events = multi_d_acquisition_events(
        num_time_points=20, time_interval_s=0)
    acq.acquire(events)

**Comment by BDImagingLab** [comment]
Thank you for the clarification, Henry. Really appreciate it. I was able to overcome this by putting Pycromanager in a while loop.
