### ISSUE TITLE
Tagged Image Memory Leak

### ISSUE THREAD

**Issue by jsokoloff23** [micro-manager/pycro-manager#398]
**Bug summary**

Tagged image remains in memory

**Code for reproduction**

Reproducible in the demo config:

```python

core.startSequenceAcquisition(500, 0., True)

while core.getRemainingImageCount() > 0 or core.isSequenceRunning():
    if core.getRemainingImageCount() > 0:
	tagged = core.popNextTaggedImage()
    else:
        core.sleep(5)

```

**Expected outcome**
tagged image is removed from memory each time a new image is popped. This is at least how it works in the Beanshell script and in plugins.

**Actual outcome**

Tagged image remains in memory until Micro-Manager is closed.

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.17.4
  * MicroManager version: Gamma 2.0 3/29/22 build
  * Python version: 3.9.6
  * Python environment (command line, IDE, Jupyter notebook, etc): For this I used the shell. Usually VSC.

**Comment by henrypinkard** [comment]
Looks like something got at some point for garbage collecting python views of Java objects. Should be fixed in the new pip version (#399). Thanks for the very good bug report!

**Comment by jsokoloff23** [comment]
Thanks for the quick fix! One more (hopefully) quick one: when I run the following code through the shell, I get an attribute error 'org_micromanager_remote_RemoteAcquisitionFactory' object has no attribute 'create_acquisition'

```python
path = 'G:'
name = 'acquisition'
with Acquisition(directory=path, name=name, show_display=False) as acq:
	events = multi_d_acquisition_events(num_time_points = 100)
	acq.acquire(events)
```
I'm new to this acquisition class (right now I'm just using a script I wrote a while back for acquisitions). Am I doing something wrong or something weird?

It's maybe worth noting that if I don't establish a Core or Studio object, it seems to work fine,

**Comment by jsokoloff23** [comment]
I think I figured it out. I use the core with convert_camel_case = False. When create_acquisition() is called on the RemoteAcquisitionFactory object, the method doesn't exist because the method is actually createAcquisition(). I'm fine with just creating a new cord object with convert_camel_case = True.

**Comment by jsokoloff23** [comment]
Hey Henry, I'm having the same bug but with image objects. See:

**Bug summary**

Image object remains in memory

**Code for reproduction**

Reproducible in the demo config (OutOfMemoryException is thrown if Java environment runs out of memory)

```python

for i in range(20):
    core.start_sequence_acquisition(400, 0, True)
    while core.get_remaining_image_count() > 0 or core.is_sequence_running():
        if core.get_remaining_image_count() > 0:
            tagged = core.pop_next_tagged_image()
            studio.data().convert_tagged_image(tagged)
        else:
            core.sleep(5)
```

Same thing happens if you assign a variable to studio.data().convert_tagged_image(tagged) (ie image).

**Expected outcome**
Image is removed from memory each time a new image is popped. Loop runs without OutOfMemoryException.

**Actual outcome**

Image remains in memory until Micro-Manager is closed. Throws OutOfMemoryException


**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.23.0 (works on 0.20.0, breaks after that)
  * MicroManager version: Gamma 2.0 12/18/2022 build
  * Python version: 3.9.6
  * VSC
