### ISSUE TITLE
Studio object from Headless launcher ?

### ISSUE THREAD

**Issue by ilyasdc** [micro-manager/pycro-manager#404]
### Problem

Currently only acquisition engine and internal pycromanager objects features available from the headless launcher (I probably forgot some others). The `Studio` objects is not one of them.  

### Proposed Solution

If it's easy to implement getting the `Studio` object would be a huge relief for my colleagues. An alternative but less elegant solution would be to be able to set up zmq server port for non headless launcher which would require less work if I refer to https://github.com/micro-manager/micro-manager/pull/1265#issuecomment-867178973

### Additional context

Currently we have one instance of micro-manager running for multiple users in the background. We use it like so because there's no alternative to quickly read TB sized datasets as fast as MM and we also also want to generate post-treated datasets fully compliant with MM image format (ex: deconvolve images and saving back the hyperstack) 

Writing files is therefore done with the user launching this instance (me), this is causing some trouble. What's more it seems that having many users using concurently the same server side on the bridge is not ideal (maybe not even a typical usecase).

**Comment by henrypinkard** [comment]
This is by design because the launching the studio entails launching ImageJ, the full application, etc. since that part of the code is pretty monolithic. In order to keep it lightweight that stuff is excluded.

I don't quite understand what your proposed solution is. Do you mean that you'd want to launch via the GUI but be able to specify your own port number?

You might also consider launching the application not through headless mode: https://forum.image.sc/t/looking-for-a-way-to-bypass-micro-manager-startup-screen-for-automation-scripting/63241


> What's more it seems that having many users using concurently the same server side on the bridge is not ideal (maybe not even a typical usecase).

If you want to reduce traffic on a given port, just call:

`studio = Studio(new_socket=True)` and go from there

**Comment by ilyasdc** [comment]
> This is by design because the launching the studio entails launching ImageJ, the full application, etc. since that part of the code is pretty monolithic. In order to keep it lightweight that stuff is excluded.
> 
> I don't quite understand what your proposed solution is. Do you mean that you'd want to launch via the GUI but be able to specify your own port number?
> 

The discussion I referenced seemed to show that the port number is passed as argument to the headless launcher, I was thinking to something similar but for the whole MM. A setting from the GUI is equivalent I guess.

> You might also consider launching the application not through headless mode: https://forum.image.sc/t/looking-for-a-way-to-bypass-micro-manager-startup-screen-for-automation-scripting/63241
> 

I see. But if multiple user launch the same micro-manager binary (this is our case) what zmq server gets prioritized ? 
Basically my idea would be that user A/B/C are assigned fixed ports X/Y/Z which correspond to their own instance of MM  and allow e.g. to write in their `/home/` folder. But that's a niche request I guess ( see following comment)

> > What's more it seems that having many users using concurently the same server side on the bridge is not ideal (maybe not even a typical usecase).
> 
> If you want to reduce traffic on a given port, just call:
> 
> `studio = Studio(new_socket=True)` and go from there

I will recompile and assign a different port for the background micro manager instance that I manage. I will make sure that every bridge is called with this `new_socket` argument and see  If that fixes our problem, at the moment that would suffice.

**Comment by henrypinkard** [comment]
> > > What's more it seems that having many users using concurently the same server side on the bridge is not ideal (maybe not even a typical usecase).
> > 
> > 
> > If you want to reduce traffic on a given port, just call:
> > `studio = Studio(new_socket=True)` and go from there
> 
> I will recompile and assign a different port for the background micro manager instance that I manage. I will make sure that every bridge is called with this `new_socket` argument and see If that fixes our problem, at the moment that would suffice.

Its not clear to me why you'd need to assign a different port to the instance you manager. If you just start on the default 4827, then `new_socket` will increment from there. Is there something else using 4827?

**Comment by ilyasdc** [comment]
> > > > What's more it seems that having many users using concurently the same server side on the bridge is not ideal (maybe not even a typical usecase).
> > > 
> > > 
> > > If you want to reduce traffic on a given port, just call:
> > > `studio = Studio(new_socket=True)` and go from there
> > 
> > 
> > I will recompile and assign a different port for the background micro manager instance that I manage. I will make sure that every bridge is called with this `new_socket` argument and see If that fixes our problem, at the moment that would suffice.
> 
> Its not clear to me why you'd need to assign a different port to the instance you manager. If you just start on the default 4827, then `new_socket` will increment from there. Is there something else using 4827?

There were multiple instances of MM using the same user profile....
I think a combination of a dedicated user profile for the MM instance used for pycromanager and the `new_socket` option of studio will solve most of our problems. I'll report back if it doesn't. As usual, thanks for your very prompt help ! I think I should close this issue.
