### ISSUE TITLE
bridge.construct_java_object no longer supported? 

### ISSUE THREAD

**Issue by cfan-curio** [micro-manager/pycro-manager#408]
We used to have this: 
`pos_sublist=bridge.construct_java_object("mmc.DoubleVector")`
that has been working perfectly before the latest pycromanager update. 

Now with the pycromanager update, it says 'Bridge' object has no attribute 'construct_java_object'

**Comment by henrypinkard** [comment]
Its now just `JavaObject`. see [here](https://pycro-manager.readthedocs.io/en/latest/calling_java.html)
