### ISSUE TITLE
Stage and camera synchronization error after pycromanager update

### ISSUE THREAD

**Issue by kidantad** [micro-manager/pycro-manager#413]
I used the code below to run a fast acquisition imaging using hardware triggering. By using the SCAN module for my XY stage(MS 2000), I used TTL signal to trigger the camera(HamamatsuHam_DCAM) for certain XY positions. When the code was working properly, the SCAN command will turn the camera on for the X positions specified as "scan_start" and "scan_end". Then the stage will move up in Z(raster scanning) while the camera is turned off and repeat the process. The only issue I had with this code was a ZMQ error, but I was still able to acquire and save my images so I didn't do anything to solve it. After the new pycromanager update, the code was not acquiring any images at all. After checking that the hardware was working properly, I updated my micromanager and pycromanager to the latest build. Per the new pycromanager I stopped using BRIDGE to connect with the core and followed the instruction. I did not make any other changes to the code.

The issue now is that the camera turns on after the stage has reached "scan_end" and acquires image when stage isn't moving instead of turning on at "scan_start" till "scan_end".  I checked that triggering is working properly using my stage's and camera software. Therefore, I am assuming that there is miscommunication in post_camera or hardware hook, but I'm no expert. Like I said, I haven't changed anything in the code and have used this to run fast acquisition for multiple Z layers. I would really appreciate any input into how I can fix this error. Thank you

```
#Import required functions

from datetime import datetime
import numpy as np
from pycromanager import Bridge, Acquisition, multi_d_acquisition_events,Core
from time import sleep
import gc
#Create the Micro-Managert to Pycro-Manager transfer layer

#bridge = Bridge()
#get object representing micro-manager core
#mmc = bridge.get_core()
mmc= Core()

print(mmc)

#save parameters
date = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
save_dir = r'E:\3D SSM\test_scan' + str(...)
save_name =  r'test_'+ date 
# open shutter
mmc.set_auto_shutter(False) # disable auto shutter
mmc.set_shutter_open(True)

#Configurations
mmc.set_config('Laser control','Measure')
#mmc.set_config('sCMOS','NewPreset')
#mmc.set_config('stage','scan')

# nFrames = 2; # Frames per position, always bigger than 1
ExposureTime = 5# in ms
liveExposure = 10 # in ms
ROI = [0, 512, 2048, 1024]
mmc.set_roi(*ROI)

def post_camera_hook_(event,bridge,event_queue):

    """
    Run a set of commands after the camera is started

    """

    # acquire core from bridge
    #mmc = bridge.get_core()
    mmc= Core()
    
    #new
    return event

    # send MS2000 command to start constant speed scan
    command='SCAN'
    mmc.set_property('XYStage','SerialCommand',command)

    return event

ready = mmc.get_property('XYStage','SerialResponse')


def post_hardware_hook(event,bridge,event_queue):

    """
    Run a set of commands after the hardware setup calls by acquisition engine are finished

    :param event: current list of events, each a dictionary, to run in this hardware sequence

    """

    # acquire core from bridge
   
    #mmc = bridge.get_core()
    mmc= Core()

    # turn on 'transmit repeated commands' for MS2000
    No='No'
    mmc.set_property('XYStage','OnlySendSerialCommandOnChange',No)
    
    command='SCAN'
    mmc.set_property('XYStage','SerialCommand',command)


    # check to make sure MS2000 is not busy
    ready='B'
    while(ready!='N'):
        command = 'STATUS'
        mmc.set_property('XYStage','SerialCommand',command)
        ready = mmc.get_property('XYStage','SerialResponse')
        sleep(.500)

    # turn off 'transmit repeated commands' for MS2000
    Yes= 'Yes'
    mmc.set_property('XYStage','OnlySendSerialCommandOnChange',Yes)
    
    return event


#SET UP SCAN START POSITION,END POSITION AND SPEED

x_pos = mmc.get_x_position() #get current x position

scan_start= (-1*(x_pos/1000))  #Start position in mm
scan_end = (scan_start) - 0.04 #End position in mm. 20um relatively
scan_speed = 0.02 #in seconds
scan_step = 0.0001 #in mm
scan_range = np.abs(scan_end-scan_start)
scan_positions= np.rint((scan_range/scan_step)+1).astype(int)  #number of positions


#Y_AXIS

y_start = mmc.get_y_position()/1000 #get current y position
y_end = y_start

#y_pos = y_start*np.ones((scan_positions+1,1))
#y_positions= len(y_pos)

    # set range and return speed (25% of max) for constant speed movement of scan (x) axis
    # expects mm
#bridge = Bridge()
#mmc = bridge.get_core()
mmc= Core()

# turn on 'transmit repeated commands' for MS2000
mmc.set_property('XYStage','OnlySendSerialCommandOnChange','No')

command = 'SPEED X=.02'
mmc.set_property('XYStage','SerialCommand',command)

    # check to make sure Tiger is not busy
ready='B'
while(ready!='N'):
        command = 'STATUS'
        mmc.set_property('XYStage','SerialCommand',command)
        ready = mmc.get_property('XYStage','SerialResponse')
        sleep(.500)

    # turn off 'transmit repeated commands' for MS2000
    Yes='Yes'
    mmc.set_property('XYStage','OnlySendSerialCommandOnChange',Yes)
    # turn on 'transmit repeated commands' for MS2000
    No='No'
    mmc.set_property('XYStage','OnlySendSerialCommandOnChange',No)


#command = 'SCANR X='+str(scan_start)+' Y='+str(scan_end) 
#SCAN command for raster scan in x and scanv to specify location in y
command = 'SCANR X='+str(scan_start)+' Y='+str(scan_end)
mmc.set_property('XYStage','SerialCommand',command)

# turn off 'transmit repeated commands' for MS2000
Yes='Yes'
mmc.set_property('XYStage','OnlySendSerialCommandOnChange',Yes)


#Set and save the overshoot factor and the y position

command='SCAN F=1'
mmc.set_property('XYStage','SerialCommand',command)


command='SS Z'
mmc.set_property('XYStage','SerialCommand',command)

command= 'SCANV X=' +str(y_start)+' Y='+str(y_end)
mmc.set_property('XYStage','SerialCommand',command)


z_scan_start = 0.0
z_scan_end =0.3
z_scan_step = 0.15
z_sequence = np.arange(z_scan_start, z_scan_end+z_scan_step, z_scan_step)
num_z_slices = len(z_sequence)    


%%time
for z in z_sequence:
    with Acquisition(directory=save_dir, name=save_name, post_hardware_hook_fn=post_hardware_hook,
                    post_camera_hook_fn=post_camera_hook_, show_display=True) as acq:
        events = multi_d_acquisition_events(
                                        num_time_points=400, time_interval_s=0,
                                        z_start =z, z_end=z-.5*z_scan_step, z_step=z_scan_step,
        )
        
        
        acq.acquire(events)

```

**Comment by dpshepherd** [comment]
Why are you send the stage the `SCAN` command in both the `post_camera_hook_` and `post_hardware_hook` functions?

**Comment by kidantad** [comment]
No particular reason. I thought I had to include the SCAN command in both of the post_hooks.

**Comment by dpshepherd** [comment]
The code you posted will send `SCAN` to the stage to execute a scan both when the hardware is done being setup and the camera is ready. Is that the goal of your experiment?

**Comment by kidantad** [comment]
Thanks for clarifying that. I only want the SCAN command to be executed when the stage reaches the start position. This in turn needs to send a trigger signal to the camera to start capturing. So would that mean removing the SCAN command from the post_Camera_hook?

**Comment by dpshepherd** [comment]
Are you triggering the camera to start acquiring off of the stage? It isn't clear because you are calling a camera preset.

If you set `SCANR` and `SCANV`, I believe you should just call `SCAN` once per Z plane, as the MS-2000 controller will automatically scan both axes. [ASI SCAN module manual](http://www.asiimaging.com/docs/scan_module#scan_module_sync_and_scanning_addendum).

**Comment by kidantad** [comment]
I added the camera preset to make my camera setting to External start trigger mode. My stage is the leader and needs to send a trigger to my camera to take images as fast as possible. Is it better to set the camera mode in pycromanager?

**Comment by kidantad** [comment]
Thanks for your help @dpshepherd . That is what I think, because I took several imaging data sets with great synchronization between the stage and the camera before the update. I will need to look more into the communication

**Comment by dpshepherd** [comment]
To be clear, I don't think this is a pycromanager problem. You are sending the stage too many `SCAN` commands.

You should only be calling `SCAN` in the `post_camera_hook`, because the camera is waiting for a trigger. Once you send that command, you should be run an acquisition that collects the total number of images that match the number of images you expect for your SCANR axis, repeated by the number of tiles that the SCANV axis creates.

**Comment by henrypinkard** [comment]
Thanks for all the insights @dpshepherd !

**Comment by dpshepherd** [comment]
The `post_hardware_hook` is run before the camera is started. When the `SCAN` command is issued before the camera is started, the TTL pulse from the stage controller to the camera will likely arrive before the camera is ready for an external trigger. This exact situation is why @henrypinkard implemented the `post_camera_hook`.

**Comment by kidantad** [comment]
That makes so much sense. Then I would not need `post_hardware_hook` at all
