### ISSUE TITLE
Dataset fails to initialize when saving is not specified in Acquisition

### ISSUE THREAD

**Issue by 0101101001001100** [micro-manager/pycro-manager#415]
### Bug report

**Bug summary**

Cannot initialize an acquisition with a custom image processor without saving (works when specified `directory` and `name`). This behavior can be reproduced on another PC with a clean installation of Python and Micro-Manager on demo hardware config.

**Code for reproduction**

```python
from pycromanager import Acquisition, multi_d_acquisition_events

def img_process(image, metadata):
    return None
    # TODO: process and save images.

with Acquisition(image_process_fn=img_process) as acq:
    events = multi_d_acquisition_events(num_time_points=2, time_interval_s=0.1)
    acq.acquire(events)
```

**Expected outcome**

An instance of `Acquisition` is initialized as described in [docs](https://pycro-manager.readthedocs.io/en/latest/img_processors.html#returning-multiple-or-zero-images):

> Rather than returning one or more image, metadata tuples to propogate the image to the default viewer and saver, the image processing function can return nothing. This can be used if one wants to delete a specific image, or divert all images to customized saving/visualization code. If the latter behavior is desired, the [Acquisition](https://pycro-manager.readthedocs.io/en/latest/apis.html#pycromanager.Acquisition) should be created without the name and directory fields.

**Actual outcome**
`Acquisition.__init__()` encounters a Java exception:
```
Exception: java.lang.NullPointerException
org.micromanager.remote.RemoteAcquisition.getStorageMonitor(RemoteAcquisition.java:47)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Version Info**

  * Operating system: Windows 10 (64 bit)
  * pycromanager version: 0.17.9
  * MicroManager version: 2.0.1 (20220528)
  * Python version: 3.9.13

**Comment by henrypinkard** [comment]
Fixed by https://github.com/micro-manager/pycro-manager/pull/416

You'll need to pip update and get tomorrows nightly build
