### ISSUE TITLE
Another python framework: PyMoDAQ

### ISSUE THREAD

**Issue by seb5g** [micro-manager/pycro-manager#417]
Hello,
I'm developing a python framework called PyMoDAQ that enables modular interfaces and control of various experimental setups (not only microscopes but also microscopes). I'm organizing in late october, a kind of user/developer meeting and would love to have one of micro-manager (or pycro-manager) "managers" to come and have a presentation and round table about opportunities in between our developments. Would you be interested? You can contact me directly out of this issue (it was the only way I found to reach you :-) ):
sebastien.weber@cemes.fr

Cheers

**Comment by henrypinkard** [comment]
Emailed you
