### ISSUE TITLE
random java.lang.NumberFormatException error with programmed position list

### ISSUE THREAD

**Issue by cfan-curio** [micro-manager/pycro-manager#423]
We are using pycromanager to program micromanager to do multi-dimensional acquisition and running into some randomly occurring error related to programmed position list and perhaps formatting issue with scientific notation.

Here’s the workflow:
We have a position list of 800 positions defined by x,y. It is initially created interactively by the micro-manager ‘create grid’ function. Then we start our python script. For every 16 positions, the program autofocuses on one of the positions, and applies the z-height found by autofocus to all the 16 positions. Then it creates a sub-position list of only those 16 positions, now with x, y, z defined, and then triggers acquisition.

There are multiple occasions that the script ran fine until somewhere down the 800 position list that micromanager will give this error randomly and not able to acquire:
java.lang.NumberFormatException: For input string: ".E4"
It looks like it’s something to do with conversion of string with scientific notation to number. The x, y position list does contain numbers >10,000, while the z height is usually around 3000. But we don’t understand how this error just occurs randomly for certain positions. We don't have a way to systematically reproduce the error. Not sure if this is micromanager issue or pycromanager issue. We would like to seek advice on how to fool-proof the code to prevent this error. 

Our code:
`    numsubtile=16;

    # get position list
    xyStage = mmcore.get_xy_stage_device();
    zStage = mmcore.get_focus_device();
    posList=mmstudio.positions().get_position_list(); #get master position list
    numpos = posList.get_number_of_positions()
    
    ROInum=1;
    for i in range(int(numsubtile/2-1)-1, numpos, numsubtile):
        msp=posList.get_position(i); # get position list
        ztemp=msp.get(zStage); # get z stage
        z=ztemp.get1_d_position(); # get z height
        xytemp=msp.get(xyStage); # get xy stage
        x=xytemp.get2_d_position_x(); # get x position
        y=xytemp.get2_d_position_y();  # get y position
        
        #move_stage_to_specific_XY_location
        mmcore.set_xy_position(x,y);
        
        #move_stage_to_specific_Z_location
        mmcore.set_position(z);
        
        #autofocus
        AfM=mmstudio.get_autofocus_manager();
        AfMM=AfM.get_autofocus_method();
        astart=time.time(); # autofocus start time
        AfMM.full_focus();
        aend=time.time(); # autofocus end time

        #get_z_position after autofocus
        new_z=mmcore.get_position();
        print('New z height after autofocusing:'+str(new_z));

        #apply new position to all tiles within ROI
        for j in range(i-(int(numsubtile/2-1)-1), i+(numsubtile-int(numsubtile/2)+2)):
            msp_each=posList.get_position(j);
            ztemp_each=msp_each.get(zStage);
            ztemp_each.set1_d_position(zStage, new_z);
                           
        #make a new position list of a sublist
        pos_sublist=bridge.construct_java_object('org.micromanager.PositionList'); 
        for j in range(i-(int(numsubtile/2-1)-1), i+(numsubtile-int(numsubtile/2)+2)):
            msp_each=posList.get_position(j);
            pos_sublist.add_position(msp_each);`

**Comment by henrypinkard** [comment]
handled on image.sc
