### ISSUE TITLE
Every other acquisition (multi_d_acquisition_events ) fails with a ZMQException error

### ISSUE THREAD

**Issue by muellerflorian** [micro-manager/pycro-manager#428]
### Bug report

First, thank you for this fantastic projet. It is incredibly useful!

**Bug summary**

Just to give you the context. We would like to use pycromanager in a project, where we run several cycles of
an experiment, where we alternate between operating a fluidics system (controlled with Python) and imaging (by using
Pyromanager and `multi_d_acquisition_events`).

I'm new to pycromanager, and I'm slowly building up the code, and ran into a smaller issue. I define the acquisition event once, and then want to acquire images with this pre-defined event in a for loop (code below). When doing this, every other acquisition seems to fail and gives an error (`org.zeromq.ZMQException: Errno 48 : Address already in use`, more details below).

I had a look at open and closed issues and thought that #286 and #406 might be relevant, but unfortunately I couldn't find something that solved the problem. 

Any pointer for how to resolve this problem would be very much appreciated (I hope I didn't overlook something obvious).

**Code for reproduction**

```python

# Imports 
from pycromanager import Core
from pycromanager import Acquisition, multi_d_acquisition_events
import gc
import numpy as np 

# Connect to core
core = Core()
print(core)

# Create acquisition event
x = np.arange(0, 5)
y = np.arange(0, -5, -1)
xy = np.hstack([x[:, None], y[:, None]])

events = multi_d_acquisition_events(
    channel_group = 'Channel', 
    channels = ['Cy5','DAPI',], 
    channel_exposures_ms = [300,50], 
    xy_positions = xy)

# Loop over N acquisitions
for i in range(10):
    print (f'\nAcquisition {i}')

    try: 
        with Acquisition(directory=r'D:\\tmp', name='test', show_display=False, debug=False) as acq:
            acq.acquire(events)
            
            del acq       # Adding ths didn't help
            gc.collect()  # Adding ths didn't help
            print('\tAll good!')
            
    except Exception as e:
        print(e)

```

**Expected outcome**

N Acquisitions successfully complete.

**Actual outcome**

Only every other acquisition is successful (N=0,2,4,...). 

Acquistions (N=1,3,...) terminate with an error 

``` bash
Acquisition 0
	All good!

Acquisition 1
org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
org.micromanager.internal.zmq.ZMQPushSocket.initialize(ZMQPushSocket.java:32)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPushSocket.<init>(ZMQPushSocket.java:24)
org.micromanager.remote.RemoteStorageMonitor.<init>(RemoteStorageMonitor.java:36)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:99)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:298)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:246)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:32)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)


Acquisition 2
	All good!

Acquisition 3
org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)

...

```

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.18.1 
  * MicroManager version: MMCore version 10.2.0
  * Python version: 3.7.10
  * Python environment : Visual studio code. Error occurs when running in interactive mode and also when executing script directly in the terminal.

**Comment by henrypinkard** [comment]
Hi Florian! Good to hear from you and glad to hear you like pycro-manager.

This does seem like its the same issue as #406. I am unable to reproduce it though, either on a windows or mac computer.

I do see on your code that the indent level is wrong. The `del acq` should occur after the `with` block exits so it has properly cleaned up:

```python
with Acquisition(directory=r'D:\\tmp', name='test', show_display=False, debug=False) as acq:
      acq.acquire(events)
      
del acq       # Adding ths didn't help
gc.collect()  # Adding ths didn't help
print('\tAll good!')
```

However, I don't think this is the primary cause, and leaving it unchanged still did not trigger the issue for me.

Looks like you're not on the latest version of pycromanager though. Can you try updating that and also downloading the latest [nightly build](https://micro-manager.org/Micro-Manager_Nightly_Builds) of micromanager and see if the problem persists?

**Comment by muellerflorian** [comment]
Hi Henry, 

thanks for the fast reply! Sorry, should have checked before if I use the latest versions ...  I upgraded both Micromanager (last nightly build) and pycromanager (0.18.3) & the problem seems to be gone for the demo version! Awesome!

I didn't have time to see how this actually works on our "real" microscope. Will do this on Monday. Will keep you posted on this thread.

**Comment by muellerflorian** [comment]
Hey Henry,

I now tested the code on our microscope and everything works like a charm. 

Can't wait to try the MicroMagellan acquisitions. 

A big thanks for this development! It's really fantastic.

**Comment by henrypinkard** [comment]
Awesome! 

I may be doing some work to make generalized versions of the Magellan acquisitions and incorporate them closer into Micro-Manager in the near future. So let me know if you have any feedback/missing features/improvements/etc.
