### ISSUE TITLE
Java ZMQ server and Python client version missmatch

### ISSUE THREAD

**Issue by smallfishabc** [micro-manager/pycro-manager#433]
Hi,
Our lab has already installed the micro-manager on our microscope with certain protocols running properly. We do not want to uninstall the micro-manager and then upgrade it. Could you tell me which pycro-manager I should use to match our micro-manager version? We have tried the troubleshooting command mentioned in the readme file. Our micro-manager version is 2.0 Nightly Builds.

Thank you
Best
Feng Yu

C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\bridge.py:281: UserWarning: Version mistmatch between Java ZMQ server and Python client.
Java ZMQ server version: 4.0.0
Python client expected version: 4.2.0
 To fix, update to BOTH latest pycromanager and latest micro-manager nightly build
  warnings.warn(
[3276 3339 3402 ... 5839 5843 5845]
C:\Users\Shahar_group_scope\Documents\Patrick\pycromanager_scripts\pycromanager_script_1.py:17: DeprecationWarning:
The Bridge context manager (i.e. with Bridge...) is deprecated and will be
removed in a future version. Bridge does not need to be explicitly created anymore.
Instead use the classes JavaObject, JavaClass, Core, Studio, Magellan
  with Bridge(port=5000) as b:
C:\Users\Shahar_group_scope\Documents\Patrick\pycromanager_scripts\pycromanager_script_1.py:18: DeprecationWarning: Deprecated. use "from pycromanager import Core; core = Core()"
  b.get_core().snap_image()
C:\Users\Shahar_group_scope\Documents\Patrick\pycromanager_scripts\pycromanager_script_1.py:19: DeprecationWarning: Deprecated. use "from pycromanager import Core; core = Core()"
  print(b.get_core().get_image())
Traceback (most recent call last):
  File "C:\Users\Shahar_group_scope\Documents\Patrick\pycromanager_scripts\pycromanager_script_1.py", line 27, in <module>
    with Acquisition(directory=save_dir, name=save_name) as acq:
  File "C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\acquisitions.py", line 356, in __init__
    self._create_remote_acquisition(**named_args)
  File "C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\acquisitions.py", line 469, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\bridge.py", line 599, in _translate_call
    valid_method_spec, deserialize_types = _check_method_args(method_specs, fn_args)
  File "C:\Users\Shahar_group_scope\anaconda3\lib\site-packages\pycromanager\bridge.py", line 774, in _check_method_args
    raise Exception(
Exception: Incorrect arguments.
Expected java.lang.String, java.lang.String, boolean, boolean, int, int, int, int, boolean
Got <class 'str'>, <class 'str'>, <class 'bool'>, <class 'int'>, <class 'bool'>

**Comment by henrypinkard** [comment]
I don't have a list of which matches up with which. You could probably figure it out from looking at the commit histories on the repositories.

However, I would strongly recommend upgrading to a newer Micro-Manager. If there are bugs in MM, it is better to identify and fix them then stay fixed on one version (and everyone benefits from this). There have been a lot of bug fixes and improvement to PM recently that you would miss out on.
