### ISSUE TITLE
Can't create display settings

### ISSUE THREAD

**Issue by impact27** [micro-manager/pycro-manager#44]
I am trying to modify the display settings for one of micromanager windows. If I understood the doc correctly, this is the way of creating display settings:
```
from pycromanager import Bridge
bridge = Bridge(convert_camel_case=False)
mmStudio = bridge.get_studio()
displayManager = mmStudio.displays()
dsb = displayManager.displaySettingsBuilder()
display_settings = dsb.build()
```
But running this, I get:
```
Exception: java.lang.IllegalAccessException: Class org.micromanager.internal.zmq.ZMQServer can not access a member of class org.micromanager.display.internal.DefaultDisplaySettings$Builder with modifiers "public"
```

PS: I find it easier to work with acquisitionSettings. The code I use is:
```
    from pycromanager import Bridge
    bridge = Bridge(convert_camel_case=False)
    acquisition_manager = mmStudio.acquisitions()
    settings = bridge.construct_java_object(
        'org.micromanager.acquisition.SequenceSettings')
    settings.intervalMs = int(interval  * 1000)
    settings.numFrames = numFrames
    settings.prefix = experiment_name
    settings.root = save_dir
    settings.save = True
    settings.shouldDisplayImages = True
    settings.comment = comments
    acquisition_manager.runAcquisitionWithSettings(settings, False)
```
Is there a reason why I couldn't do something similar with display settings?

**Comment by henrypinkard** [comment]
WIth the caveat that I'm not especially familiar with the MM2.0 java APIs, it looks like this is be a consequence of the fact that the `org.micromanager.display.internal.DefaultDisplaySettings.Builder` class is private, which prevents its member functions being called using reflection (as Pycro-Manager does to all Java classes) (based on [this](https://stackoverflow.com/questions/25020756/java-lang-illegalaccessexception-can-not-access-a-member-of-class-java-util-col)). I'm not familiar with the deign choices of this API, so if you want to go this route you'd need to get this changed in the main micro-manager repo.

Also note that this acquisition API is, at this point, entirely separate from Pycro-manager. You can call it, but none of the other features of pycro-manager will be compatible with it. (e.g. no way to read data through Python).

**Comment by impact27** [comment]
I understand but here I am not interested in the acquisition API, I just want to adjust the scaling of the live window from python. Is there a way to do that using pycromanager?

I am not sure if I understand your message, why can't I do:
```
import numpy as np
import matplotlib.pyplot as plt
import time
from pycromanager import Bridge
bridge = Bridge(convert_camel_case=False)
mmStudio = bridge.get_studio()
acquisition_manager = mmStudio.acquisitions()


settings = bridge.construct_java_object(
    'org.micromanager.acquisition.SequenceSettings')
settings.intervalMs = 0
settings.numFrames = 10
settings.save = False


datastore = acquisition_manager.runAcquisitionWithSettings(settings, False)
time.sleep(1)
im = datastore.getAnyImage()
pixels = np.reshape(
    im.getRawPixels(),
    newshape=[im.getHeight(),
              im.getWidth()])
plt.figure()
plt.imshow(pixels)
```
Here I am accessing the image with the acquisition API? I guess I could reformulate the issue: Some parts of the micromanager API are not accessible because of reflection problems with `org.micromanager.internal.zmq.ZMQServer`? I will open a bug in micromanager.

**Comment by henrypinkard** [comment]
I'm not sure where API controls of the micro-manager live window live, so I can't say for sure if it's possible or not.

If you wanted to make your own live window with Pycro-manager features, I could add ability to programmatically control display settings of `Acquisition`s. Alternatively, If you don't care about saving the images, I'd recommend running and `Acquisition` with saving disabled, and then add in an image processor function to automatically get the data in python, and then show them in a python-based viewer like matplotlib or napari.

The code above you wrote runs fine for me.

**Comment by henrypinkard** [comment]
Nevermind, figured out a way to fix this in the ZMQ server (https://github.com/micro-manager/pycro-manager/pull/45)
