### ISSUE TITLE
Creating Dataset object 

### ISSUE THREAD

**Issue by PaigeWhyteFagundes** [micro-manager/pycro-manager#440]
Hi, 

I am new to python, so I apologize if this is a very basic question. I am trying to use pycromanager for acquiring videos and have been successful so far. But when I go to access the acquired videos when I create the Dataset object according to the pycromanager documentation I keep getting a 'list index out of range error.' Do you know why this may be the case?

Please see my code below and the error associated. 

**The code is**

from pycromanager import Dataset

dataset_dir = '/Users/Customer/Desktop/Data/test_90'

dataset = Dataset(dataset_dir)

**The error is:**

Finshed reading index          
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13460/3978366997.py in <module>
----> 1 dataset = Dataset(dataset_dir)

~\anaconda3\lib\site-packages\ndtiff\_superclass.py in __new__(cls, dataset_path, full_res_only, remote_storage_monitor)
     35             # It must be an NDTiff >= 3.0 non-multi-resolution, loaded from disk
     36             obj = NDTiffDataset.__new__(NDTiffDataset)
---> 37             obj.__init__(dataset_path, remote_storage_monitor=remote_storage_monitor)
     38             return obj
     39         fullres_path = (

~\anaconda3\lib\site-packages\ndtiff\nd_tiff_current.py in __init__(self, dataset_path, remote_storage_monitor, **kwargs)
    185             count += 1
    186             self._readers_by_filename[tiff.split(os.sep)[-1]] = _SingleNDTiffReader(tiff)
--> 187         self.summary_metadata = list(self._readers_by_filename.values())[0].summary_md
    188 
    189 

IndexError: list index out of range

**Comment by henrypinkard** [comment]
Hmm looks like some kind of bug. How big are the datasets? Is it possible to share one so I can test it?

**Comment by caichangjia** [comment]
same issue here, I probably miss something. 
I ran the following code. There are two files in the dataset folder: display_setting file and NDTiff index file.

from pycromanager import Dataset, Acquisition, multi_d_acquisition_events
with Acquisition(directory=save_dir, name=save_name) as acq:
    events = multi_d_acquisition_events(num_time_points=10)
    acq.acquire(events)
Dataset(dataset_dir)

**Comment by PaigeWhyteFagundes** [comment]
They are ~ 26,000KB. I can't attach an NDTiff file here, do you have another suggestion on how to share the file? Perhaps email?

**Comment by henrypinkard** [comment]
Okay looks like the (image) data is never getting written in the first place. Yikes. Could one or both of you attach the Micro-Manager core log (in the MM install directory in the corelogs folder) after such a run?

**Comment by caichangjia** [comment]
I can see the graphical interface after running the code, but the data is not saved. 
In the log, there is only one more line: Sequence thread exiting

**Comment by henrypinkard** [comment]
I fixed it and it should be available in tomorrows nightly build. If you want it sooner you can download [this](https://s01.oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.micro-manager.ndtiffstorage&a=NDTiffStorage&v=2.6.1&e=jar) and put it in the `plugins` folder of the MM install directory, deleting the old one thats currently in there.

This was a really bad bug, sorry!

**Comment by caichangjia** [comment]
Great! Thanks.

**Comment by PaigeWhyteFagundes** [comment]
Thank you!
