### ISSUE TITLE
ZMQError: Operation cannot be accomplished in current state throws in multi-threads

### ISSUE THREAD

**Issue by sfzhang** [micro-manager/pycro-manager#442]
### Bug report

**Bug summary**

Suppose this scenario: one thread use `core` to snap images and display it in a loop. Anther thread does some operations with the same `core`.

`ZMQError: Operation cannot be accomplished in current state`  exception may throw when one thread is snapping image while other threads are doing some operations with the same `core`.

**Code for reproduction**

```python

from pycromanager import Acquisition, multi_d_acquisition_events, start_headless, Bridge, Core
import threading


def snap_image(core):
    while True:
        try:
            core.snap_image()
            image = core.get_tagged_image()
        except Exception as e:
            print("snap image error: %s" % e)


if __name__ == '__main__':
    mm_app_path = 'C:\\Program Files\\Micro-Manager-2.0'
    config_file = 'c:\\Program Files\\Micro-Manager-2.0\\MMConfig_demo.cfg'

    start_headless(mm_app_path, config_file, timeout=10000)

    bridge = Bridge(timeout=1000)
    core = Core()
    print(core.get_version_info())

    t = threading.Thread(target=snap_image, args=(core,))
    t.start()

    while True:
        tm = core.get_exposure()
        print("Exposure %d" % tm)

```

**Expected outcome**

pycromanager can be used in multi-threads.

**Actual outcome**

Exposure 10
Exposure 10
Exposure 10
snap image error: Operation cannot be accomplished in current state
Exposure 10
python-BaseException
Traceback (most recent call last):
  File "zmq\backend\cython\socket.pyx", line 250, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state

**Version Info**

  * Operating system: Windows 11
  * pycromanager version: 0.19.2
  * MicroManager version: MMCore version 10.1.1
  * Python version: 3.9.7
  * Python environment (command line, IDE, Jupyter notebook, etc): pycharm

**Comment by henrypinkard** [comment]
If you're going to use different threads, you can't can you the same `Core` object across them, because the messages get interleaved across the same socket and everything gets jumbled up

using :
```python
def snap_image():
    while True:
    core = Core()
        try:
            core.snap_image()
            image = core.get_tagged_image()
        except Exception as e:
            print("snap image error: %s" % e)
```

Fixes it for me.  

Also, you don't need to explicitly create a `Bridge`
