### ISSUE TITLE
ZMQError: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by janislinke** [micro-manager/pycro-manager#447]
Hi,
i followed the installation instructions, however when I try to run the following code:

from pycromanager import Core
core = Core()

i do get the following error: 

ZMQError: Operation cannot be accomplished in current state

**Comment by henrypinkard** [comment]
Doesn't reproduce for me. You may have a port that failed to close from some previous PM activity. Try restarting your computer

**Comment by henrypinkard** [comment]
Assuming this is now working, and recent changes should make this type of thing less likely to come up in the future
