### ISSUE TITLE
PM fails to save data from one of two simultaneous acquisitions

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#455]
Using this example code:

```python
import os
from pycromanager import Core, Acquisition, multi_d_acquisition_events, start_headless

PORT1 = 4827
mmc1 = Core(port=PORT1)  # running MMConfig_demo config
print(mmc1)

PORT2 = 5827
mm_app_path = r'C:\Program Files\Micro-Manager-2.0_09_01_2022'
config_file = os.path.join(mm_app_path, 'MMConfig_demo.cfg')
start_headless(mm_app_path, config_file, port=PORT2) 
mmc2 = Core(port=PORT2)
print(mmc2)

events1 = multi_d_acquisition_events(num_time_points = 100)
events2 = multi_d_acquisition_events(num_time_points = 50)

save_path = r'D:\temp'

acq1 = Acquisition(directory=save_path, name='acq1', port=PORT1)
acq2 = Acquisition(directory=save_path, name='acq2', port=PORT2)

acq1.acquire(events1)
acq2.acquire(events2)

acq1.mark_finished()
acq2.mark_finished()

acq1.await_completion()
acq2.await_completion()
```

pycromanager fails to save data from `acq1`. No errors are thrown, the `acq1_1` folder contains the `NDTiff.index` and `display_settings.txt` files, but not `.tif` file with the image data. The data from `acq2` does not seem to be corrupted.

**Comment by henrypinkard** [comment]
I think the way to actually do this is not to create two instances of the Core, but instead to have a single instance, and have the acquisition engine control which acquisition can use it at any given time. Having 2 cores might lead to weird problem if they're controlling any of the same hardware, but I guess that's not what you're doing here because you're using demo. So I don't know why the above isn't working. 

But, changing to a shared Core instance seems to work for me, with:
```python
import os
from pycromanager import Core, Acquisition, multi_d_acquisition_events, start_headless

# Assuming you've already opened MM (i.e. no headless mode)

events1 = multi_d_acquisition_events(num_time_points = 100)
events2 = multi_d_acquisition_events(num_time_points = 50)

save_path = r'D:\temp'

acq1 = Acquisition(directory=save_path, name='acq1',)
acq2 = Acquisition(directory=save_path, name='acq2')

acq1.acquire(events1)
acq2.acquire(events2)

acq1.mark_finished()
acq2.mark_finished()

acq1.await_completion()
acq2.await_completion()
```

So I guess in principle this works. There may yet be hardware control issues in terms of making sure you know which acquisition events are running at which time. This isn't as simple as just calling `acquire` at different times, since the actual acquisition happens asynchronously (i.e. on a different thread). You may need to implement an acquisition hook that makes sure that the events from `acq1` have all been executed before calling `acquire` on `acq2`, and maybe repeat the process for each time point.

But I don't have a full picture in my head of how your system works, so I'm just speculating and maybe that doesn't actually matter. Let me know what other problems you run into.

**Comment by ieivanov** [comment]
This issue has resolved itself it seems - with the latest version of PM both datasets are saved correctly. I think there may have been  an unrelated issue with my previous installation - at one point event single acquisitions were failing to save data. But now all is good.

To give you a bit more context on what I am trying to do - I have two MM instances running completely separate hardware (cameras, stages, filter wheels, etc). One instance is running through the MM GUI and the other is started headless through PM, as in the example above. I can then use PM to connect to both cores, manipulate them independently, and save data from the two instances running in parallel without problems (so far :crossed_fingers:). It's all working well!

I don't think I can use a single core for this, because (at the minimum) the two cameras have different image size and bit depth, so they can't share the same circular buffer. I also need independent control of the channels and z-stacks for each acquisition.

Just to be clear, this implementation is a hack that is allowing me to collect the data that I need right away. I think many of these issues will be resolved with the upcoming changed to the MM acquisition engine. My application is also quite possibly an edge case in microscopy.

**Comment by ieivanov** [comment]
This is mostly a note to myself.

This issue came back, but I was able to find a fix / workaround.

I got it to work with `pycromanager==0.25.40` (full conda env [here](https://github.com/micro-manager/pycro-manager/files/10712060/pm2540.yml.txt)), two separate installations of the `MMSetup_64bit_2.0.1_20230208` nightly build, and the following script:

```python
#%% import modules

import os
from pycromanager import start_headless, Core, Acquisition, multi_d_acquisition_events

#%% Connect to running MM on default port 4827
# mm_app_path = 'C:\Users\Cameron\Micro-Manager-nightly_2'

PORT1 = 4827
mmc1 = Core(port=PORT1)

print(mmc1)

#%% Start and connect to headless MM on port 5827

mm_app_path = r'C:\Users\Cameron\Micro-Manager-nightly'
config_file = os.path.join(mm_app_path, "MMConfig_demo.cfg")

# Start the Java process
PORT2 = 5527
start_headless(mm_app_path, config_file, port=PORT2)  # we need to space out port numbers a bit

mmc2 = Core(port=PORT2)
print(mmc2)

#%% Acquire 100 timepoints on both cameras

events = multi_d_acquisition_events(num_time_points=3)
save_path = 'Q:\Ivan\debug'

mmc2.set_config('Camera', 'LowRes')

print('Starting acquisition')
acq1 = Acquisition(directory=save_path, name='sim_acq1', port=PORT1, show_display=False, debug=True)
acq2 = Acquisition(directory=save_path, name='sim_acq2', port=PORT2, show_display=False, debug=True)

acq1.acquire(events)
acq2.acquire(events)

acq1.mark_finished()
acq2.mark_finished()

acq1.await_completion()
acq2.await_completion()
print('Acquisition completed')
```

The NDViewer viewer does not work properly in this case, but that's OK - setting `show_display=True` on both acquisitions shows garbage, the acq completes, and the saved data look fine. I got an error when trying to use the same MM installation for both acquisitions.
