### ISSUE TITLE
Channel sequencing does not work

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#457]
PM does not properly handle channel sequencing. 

Using this simple extension of the demo config: 
[MMConfig_demo_ChannelSeq.txt](https://github.com/micro-manager/pycro-manager/files/10109277/MMConfig_demo_ChannelSeq.txt) (please rename to .cfg)

and the following example code:

```python
from pycromanager import Core, Acquisition, multi_d_acquisition_events

mmc = Core()

def print_acq_event(event):
    print(event)

    return event

#%% Test sequenced channel acquisition
mmc.set_property('DAC', 'UseSequences', 'Yes')

events = multi_d_acquisition_events(channel_group='DAC-Channel', channels=[f'State{i}' for i in range(5)])

print('Testing sequenced channel acquisition \n')
with Acquisition(directory=r'D:\temp', name='PM_test2', pre_hardware_hook_fn=print_acq_event) as acq:
    acq.acquire(events)
```

the `pre_hardware_hook_fn` prints individual acquisition events rather than a list of events for sequenced acquisition.

**Comment by henrypinkard** [comment]
took a look. The reason sequencing doesnt happen in this case is because the `Position` property of the DAC device is not sequencable. This would need to be fixed in the device adapter

![Screen Shot 2022-12-15 at 2 22 48 PM](https://user-images.githubusercontent.com/7969470/207980013-5ecf726c-afa8-4266-9431-60dc5519b693.png)

**Comment by ieivanov** [comment]
That's strange. The DAC device is really a `DStage`, and I know that the `DStage` position property can be sequenced. `mmc.set_property('DAC', 'UseSequences', 'Yes')` turns on the sequencing of that property. How come it's off by the time it reaches the acquisition engine?

**Comment by ieivanov** [comment]
P.S. I'm pretty sure that I tested that this runs as a sequenced acquisition in the MM MDA

**Comment by ieivanov** [comment]
Hey @henrypinkard could you reopen this issue?

Now that micro-manager/mmCoreAndDevices#307 and micro-manager/micro-manager#1582 are merged, we should be able to make the `test_channel_seq_acq`, `test_channel_z_seq_acq`, and `test_time_channel_z_seq_acq` tests run

I'll have to redo my setup for troubleshooting AcqEngJ, it would be great if you could also take a look at this.

**Comment by ieivanov** [comment]
Thank you!

**Comment by ieivanov** [comment]
I think I found the source of this bug - some device properties in a given config group can be the same between channels and don't need to be sequencable for the acquisition to be sequencable as a whole. For example in 

```
# Preset: DAPI
ConfigGroup,Channel-Multiband,DAPI,Dichroic,Label,89402bs
ConfigGroup,Channel-Multiband,DAPI,Emission,Label,89402m
ConfigGroup,Channel-Multiband,DAPI,Excitation,Label,Empty
ConfigGroup,Channel-Multiband,DAPI,LED,Label,385nm
ConfigGroup,Channel-Multiband,DAPI,Core,Shutter,LED Shutter

# Preset: FITC
ConfigGroup,Channel-Multiband,FITC,Dichroic,Label,89402bs
ConfigGroup,Channel-Multiband,FITC,Emission,Label,89402m
ConfigGroup,Channel-Multiband,FITC,Excitation,Label,Empty
ConfigGroup,Channel-Multiband,FITC,LED,Label,470nm
ConfigGroup,Channel-Multiband,FITC,Core,Shutter,LED Shutter
```

All device properties between the DAPI and FITC channels are the same except for LED Label. Since all other properties between the two channels are the same only LED Label needs to be sequencable for this acquisition to be sequencable.

I started addressing this in micro-manager/AcqEngJ#59. I modified `isSequencable` to 

```java
//check all properties in the channel
Configuration config1 = core_.getConfigData(e1.getConfigGroup(), e1.getConfigPreset());
Configuration config2 = core_.getConfigData(e2.getConfigGroup(), e2.getConfigPreset());
for (int i = 0; i < config1.size(); i++) {
   PropertySetting ps1 = config1.getSetting(i);
   String deviceName = ps1.getDeviceLabel();
   String propName = ps1.getPropertyName();
   String propValue1 = ps1.getPropertyValue();
   PropertySetting ps2 = config2.getSetting(i);
   String propValue2 = ps2.getPropertyValue();
   if (!propValue1.equals(propValue2)) {
      if (!core_.isPropertySequenceable(deviceName, propName)) {
         return false;
      }
      if (core_.getPropertySequenceMaxLength(deviceName, propName) < newSeqLength) {
         return false;
      }
   }
}
```

to get the right behavior, but then also had to make changes in `prepareHardware`, which I'm less certain about. Let me know what you think @henrypinkard. I think the current implementation is a bit inefficient in that we check multiple times which channel properties are sequencable and which are not. In `prepareHardware` we should set the non-sequencable properties and then start sequence for the sequencable properties. Not too sure how to implement that properly.

**Comment by henrypinkard** [comment]
Nice detective work! That seems correct to me. I think a good test of this is if it passes the pycro-manager checks, since it should be easier to describe it in tests than code.

As for the multiple checks for whether a property is sequencable, I dont think this is unique to these changes, and Ive been considering implementing a caching mechanism in the acquisition engine whether particular properties/devices are sequencable. But I'm unsure as to whether the API intends for these to be static properties of a particular device. @nicost and @marktsuchida do you have any idea?

**Comment by marktsuchida** [comment]
Most sequenceable devices have a property that switches sequencing on and off, so no, the sequenceability is not static.
