### ISSUE TITLE
Unexpected problems on windows due to multiprocessing

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#46]
Pycro-manager acquisitions use multiple threads in order to asynchronously execute different parts of the acquisition cycle. These correspond to different threads on the Java side as well. Specifically, sending acquisition events, running acquisition hooks, and running image processors should each occur separately, such that one does not block another, and none interferes with the main thread. Right now, this is achieved using python's `multiprocessing` module, so that each of theses actions occurs in its own dedicated process. However, `multiprocessing` can behave in non-intuitive ways on windows, leading to unexpected issues (https://github.com/micro-manager/pycro-manager/issues/9, https://github.com/micro-manager/pycro-manager/issues/42).

One alternative to this behavior might be to use python's `threading` module instead. For acquisition events it would be pretty easy to swap in multiple threads instead of multiple processes, and I doubt there would much (if any) performance hit, but image processors and acquisition hooks run by the same mechanism, and if using both at the same time global interpreter lock blocking could become a problem. Ideally, there could be a change that would cover all three cases, but I've yet to figure out what that could be. It might make sense in the mean time to switch all three cases to using threads to ensure that simple use cases work as expected, and allow swapping in of processes for more performant use cases.

**Comment by impact27** [comment]
`multiprocessing.dummy` provides the same API than `multiprocessing` but using threads instead of processes. This can be useful if you want to support both. Is the global interpreter lock really a problem here?

**Comment by henrypinkard** [comment]
`multiprocessing.dummy` is just a wrapper around `threading`, so as you mention it would be trivial to support both. I'm just wondering if there is a way to get the best of both worlds--fully asynchronous image processors, acquisitions hooks, and acquisition events, without having to expose the user to the annoying complexities of `multiprocessing`. In most cases GIL wouldn't be a problem, but if trying to run on two different threads at the same time with functions that fail to release GIL, there could be a major performance hit

**Comment by henrypinkard** [comment]
closing for now since all issues seem to be resolved. Might reopen/reconsider later
