### ISSUE TITLE
UnboundLocalError generated in _run_image_processor()

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#462]
### Bug report

**Bug summary**
If an invalid image_processing_function is provided, an exception is generated.

Also, documentation seems inconsistant, saying that this function can have 2 or 4 arguments, while the code requires 2 or 3 arguments.

**Code for reproduction**

If the params is such that acquisition.abort is called, processed won't be initialized and this will generate an error.  Simple fix would be to initialize processed outside of the if statement.
```python

        params = signature(process_fn).parameters
        if len(params) == 2 or len(params) == 3:
            processed = None
            try:
                if len(params) == 2:
                    processed = process_fn(image, metadata)
                elif len(params) == 3:
                    processed = process_fn(image, metadata, event_queue)
            except Exception as e:
                acquisition.abort(Exception("exception in image processor: {}".format(e)))
                continue
        else:
            acquisition.abort(Exception(
                "Incorrect number of arguments for image processing function, must be 2 or 3"
            ))

        if processed is None:
            continue
```

**Expected outcome**

**Actual outcome**

**Version Info**

  * Operating system:
  * pycromanager version: 
  * MicroManager version:
  * Python version:
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by henrypinkard** [comment]
Got it, thanks!

https://github.com/micro-manager/pycro-manager/pull/472
