### ISSUE TITLE
Missing port argument to JavaObject in aqusition.py

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#474]
### Bug report

**Bug summary**

Alternative port is not being passed to JavaObject creation in Aquisition initialization.  

I've submitted a pull request with the fix.
**Code for reproduction**

```python
# Paste your code here
#
#
```

**Expected outcome**

**Actual outcome**

**Version Info**

  * Operating system:
  * pycromanager version: 
  * MicroManager version:
  * Python version:
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by henrypinkard** [comment]
Thanks!
