### ISSUE TITLE
Image Object Memory Leak

### ISSUE THREAD

**Issue by jsokoloff23** [micro-manager/pycro-manager#476]
Hey Henry, this is pretty much exactly the same as the tagged image leak I had before, just with image objects instead.

**Bug summary**

Image object remains in memory

**Code for reproduction**

Reproducible in the demo config (OutOfMemoryException is thrown if Java environment runs out of memory)

```python

for i in range(20):
    core.start_sequence_acquisition(400, 0, True)
    while core.get_remaining_image_count() > 0 or core.is_sequence_running():
        if core.get_remaining_image_count() > 0:
            tagged = core.pop_next_tagged_image()
            studio.data().convert_tagged_image(tagged)
        else:
            core.sleep(5)
```

Same thing happens if you assign a variable to studio.data().convert_tagged_image(tagged) (ie image).

**Expected outcome**
Image is removed from memory each time a new image is popped. Loop runs without OutOfMemoryException.

**Actual outcome**

Image remains in memory until Micro-Manager is closed. Throws OutOfMemoryException

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.23.0 (works on 0.20.0, breaks after that)
  * MicroManager version: Gamma 2.0 12/18/2022 build
  * Python version: 3.9.6
  * VSC

**Comment by henrypinkard** [comment]
I think its fixed by https://github.com/micro-manager/pycro-manager/pull/477

**Comment by jsokoloff23** [comment]
Perfect, fixed. Thanks.
