### ISSUE TITLE
Access to class methods

### ISSUE THREAD

**Issue by impact27** [micro-manager/pycro-manager#48]
Some part of the API call directly to classes, which the bridge doesn't let me do (as far as I know). For example: 
```java
import org.micromanager.data.Datastore;
import org.micromanager.data.internal.DefaultDatastore;
DefaultDatastore.setPreferredSaveMode(mmStudio_,
    Datastore.SaveMode.SINGLEPLANE_TIFF_SERIES);
```
Here, I want to call a function in `DefaultDatastore` and I want to access an enumeration in `Datastore`. The solution I found which I don't feel like is very nice is:
```python
# Construct object as we can't access classes
datastore = bridge.construct_java_object(
    'org.micromanager.data.internal.DefaultDatastore',
    args=(mmStudio,))
# Use getPreferredSaveMode as we can't access the enum in Datastore.SaveMode
save_mode = mmStudio.data().getPreferredSaveMode().SINGLEPLANE_TIFF_SERIES
# Add interface because interface is listed as
# org.micromanager.data.Datastore$SaveMode
save_mode._interfaces.append('org.micromanager.data.Datastore.SaveMode')
datastore.setPreferredSaveMode(mmStudio, save_mode)
```

Is there a better way of doing that?

PS: `_check_method_args` doesn't recognise:
`'org.micromanager.data.Datastore.SaveMode'` as 
`'org.micromanager.data.Datastore$SaveMode'`

**Comment by henrypinkard** [comment]
The PS part is now fixed by #51

You're right, there's not a way to do this right now. I created a new issue to track it: https://github.com/micro-manager/pycro-manager/issues/52. Since you have a workaround, I'd say this isn't a super hight priority at the moment, but if you want to give fixing it a try, go ahead
