### ISSUE TITLE
DMD Usage with Pycromanager

### ISSUE THREAD

**Issue by jdlamstein** [micro-manager/pycro-manager#488]
Hi,

Thanks for your help. I'm working to use a Polygon 1000 DMD with Pycromanager. I got it working with micromanager and Pymmcore. In Pycromanager, I'm getting a type error when I put in a numpy array of the bitmap. 

```
rng = np.random.default_rng()
mask = rng.random((self.slmHeight, self.slmWidth)) > .6
mask = mask.ravel()
self.core.set_slm_image(self.dmd_name, mask)

error:  Incorrect arguments. 
Expected java.lang.String, int[] or java.lang.String, byte[] 
```

I've tried converting to list and string. In Pymmcore, I got it to work by using version 10.1.1.70.3, my device driver is version 70, and inputting a string. The command setSLMImage expects the argument as a char *, which I believe is represented as a python string.

```
bmp_image= imageio.imread(file)
flatarray = bmp_image.ravel().tolist()
tostring = ['\x7f' if pixel > 0 else '\x00' for pixel in flatarray]
mask = ''.join(tostring)
self.mmc.setSLMImage(self.dmd_name, mask)
```

I'm using hex '\x7f' and '\x00' as to inputs to represent on and off respectively. When I try '\xff' for 255, the dmd errors. 

 In micromanager java, I got it by using 

 ```
 BufferedImage bi = ImageIO.read(new File(bmpFile));
DataBufferByte dbb = (DataBufferByte) bi.getRaster().getDataBuffer();
pixels = dbb.getData();
innerCore.setSLMImage(slm, pixels);
```

When you have a chance, please let me know the proper way to input a bitmap image to a DMD. 

Thanks!

**Comment by henrypinkard** [comment]
I think you need to use a numpy array with a data type uint8 or unit32

**Comment by jdlamstein** [comment]
Thanks that worked great!
