### ISSUE TITLE
[BUG] NDViewer unexpected channel behavior

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#522]
* Currently by default, Composite mode in the NDViewer is not selected (which I like), but all channels in the histogram panel are selected. It would be better if only the first channel is selected.
* If one channel is deselected, the channel slider does not switch between channels. Switching to the Metadata panel and then returning to Contrast panel seems to fix this behavior

**Comment by henrypinkard** [comment]
https://github.com/micro-manager/NDViewer/pull/28

Fixed

**Comment by ieivanov** [comment]
Thanks! Confirming that everything works on my end too
