### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#53]
Error `'Dataset' object has no attribute '_remote_storage'` received after a call to
```
dataset = Dataset(r'Y:\Test\Test1_1')
data = dataset.as_array()
```
for data acquired with 
```
if __name__ == '__main__':

        with Acquisition(directory=r'Y:\Test', name='Test1') as acq:
            events = multi_d_acquisition_events(num_time_points = 100, time_interval_s = 0)
            acq.acquire(events)
```

**Comment by henrypinkard** [comment]
just pushed a fix, try upgrading to pycromanager 0.3.3

**Comment by ieivanov** [comment]
Thanks! Could you push to `origin`, I don't see it there yet?

**Comment by ieivanov** [comment]
Ah, that's on pypi already, I see it now.

**Comment by henrypinkard** [comment]
Assuming this is fixed. Open a new one if not
