### ISSUE TITLE
Problem with Remote Acquisition

### ISSUE THREAD

**Issue by Rabo98** [micro-manager/pycro-manager#530]
Dear all, I am trying to run my code on pycromanager but an error always appears: "AttributeError: 'org_micromanager_remote_RemoteAcquisition' object has no attribute 'get_storage' " and I don't know how to fix it.
Previously it didn't appear. It started this morning after I uploaded both Micro-manager and pycromanager.
Thank you in advance for your help.

**Comment by ieivanov** [comment]
Hi @Rabo98, sorry, currently there is a problem with the viewer. 

Please use `pycromanager < 0.25`, e.g. https://pypi.org/project/pycromanager/0.24.1/ or disable the viewer as in

```python
with Acquisition(..., show_viewer=False) as acq:
    acq.acquire(events)
```

We'll update this issue once this bug is fixed.

**Comment by Rabo98** [comment]
Thank you very much.
Actually, I commented the file "acquisitions.py" in the following way (around line 360) and it worked without problems:

self._remote_acq.start()
        """
        self._dataset_disk_location = (
            self._remote_acq.get_storage().get_disk_location()
            if self._remote_acq.get_storage() is not None
            else None
        )
        """
        self._start_events()
        """
        # Load remote storage
        remote_storage_monitor = self._remote_acq.get_storage_monitor()
        if remote_storage_monitor is not None:
            self._dataset = Dataset(remote_storage_monitor=remote_storage_monitor)
            if image_saved_fn is not None:
                self._storage_monitor_thread = self._dataset._add_storage_monitor_fn(
                    callback_fn=image_saved_fn, debug=self._debug
                )
            else:
                # Monitor image arrival so they can be loaded on python side, but with no callback function
                # Need to do this regardless of whether you use it, so that it signals to shut down on Java side
                self._storage_monitor_thread = self._dataset._add_storage_monitor_fn(_storage_monitor_fn, callback_fn=None, debug=self._debug)
        """


I know that this is not the best way to do it but it worked.

**Comment by ieivanov** [comment]
This bug is fixed, you can download the latest MicroManager nightly build and install the most recent version of pycromanager to use the NDViewer.
