### ISSUE TITLE
Headless mode does not keep full core log

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#549]
When I start `pycromanager` in headless mode with `start_headless(..., core_log_path=path_to_core_log.txt)` and run an acquisition with the demo config, I get only a single line in the core log:

```
2023-02-10T15:16:44.840969 tid24368 [IFO,LogManager] Enabled primary log file C:\Users\Cameron\Micro-Manager-nightly\CoreLogs\CoreLog20230210T151643_pmheadless.txt
```

I don't think this is quite the intended behavior. Is it possible to get a more complete core log saved?

**Comment by henrypinkard** [comment]
Weird. I'm not sure I ever explicitly checked that this worked. I did at one point add a mode to print the corelog to the python console using a `debug=True` flag.

https://github.com/micro-manager/pycro-manager/blob/602db21d0636b66fd78c608b143f6a8921d31b91/pycromanager/acq_util.py#L91

It might be worth trying that to see if anything is logged there.

Maybe there's also something that needs to be activated in the core API (see the "logging" section [here](https://valelab4.ucsf.edu/~MM/doc/MMCore/html/class_c_m_m_core.html))

**Comment by ieivanov** [comment]
Hm, seems to be working now with this script:

```python
import os
from datetime import datetime
from pycromanager import Core, start_headless, multi_d_acquisition_events, Acquisition

timestamp = datetime.now().strftime("%Y%m%dT%H%M%S")
mm_app_path = r'C:\Users\Cameron\Micro-Manager-nightly'
mm_config_file = os.path.join(mm_app_path, 'MMConfig_demo.cfg')
core_log_path = os.path.join(mm_app_path, 'CoreLogs', f'CoreLog{timestamp}_pycromanager_headless.txt')

start_headless(mm_app_path, mm_config_file, core_log_path=core_log_path)

events = multi_d_acquisition_events(
    num_time_points=10,
    time_interval_s=0,
    channel_group="Channel",
    channels=["DAPI", "FITC"],
    z_start=0,
    z_end=5,
    z_step=1,
    order="tcz",
)

with Acquisition(r'Q:\Ivan\debug', 'acq', show_display=True) as acq:
    acq.acquire(events)
```

I was playing around with settings last time, maybe I accidentally turned something off. I'll close this for now, and I'll reopen if I find an actual bug.
