### ISSUE TITLE
External hardware control via hardware hooks when using custom axis

### ISSUE THREAD

**Issue by Flemingjp** [micro-manager/pycro-manager#553]
I have an acquistion that has a custom axis `i`, and for each image taken along this axis, I need to update some hardware external to MicroManager (illumination source).

However the acquistion events for the custom axis only calls the hardware hooks once at the start of the acquisition

```
[Function call order for three events]
pre_hardware_hook
post_hardware_hook
post_camera_hook
image_processor
image_processor
image_processor
```

Is there someway to modify the events such that we get this behaviour

```
pre_hardware_hook
post_hardware_hook
post_camera_hook
image_processor

pre_hardware_hook
post_hardware_hook
post_camera_hook
image_processor

pre_hardware_hook
post_hardware_hook
post_camera_hook
image_processor
```

In this way, our external hardware can be dealt with in either the `pre_hardware_hook` or `post_hardware_hook` prior to images being taken

**Comment by henrypinkard** [comment]
Its sequencing the events so they run as fast as possible, so the command only gets sent to the camera once. If you want to turn this off, do:

```python
with Acquisition...as acq:
  for event in events:
     acq.acquire(event)
```

**Comment by Flemingjp** [comment]
Thank you - that will work currently

Is there any solution where events can be kept sequenced - for example #207 suggests the use case for switching lasers. This would be roughly our requirements

**Comment by henrypinkard** [comment]
If you're asking if you can both sequence events and run a hook every time -- no. The point of sequencing is that the computer is out of the loop and the hardware controls itself.

Events will only sequence over each call to `acquire`, so if you want to sequence some subsets of events, just call `acquire` on whatever subsets you want to sequence over

**Comment by Flemingjp** [comment]
In that case is there any advantage to using `Acquisition` vs using `core.snap_image()` when considering the need of software control between images?

**Comment by henrypinkard** [comment]
Yes it will be faster and you get the viewer/data storage

**Comment by Flemingjp** [comment]
Excellent - thank you again for your help
