### ISSUE TITLE
Improve sequencing documentation

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#554]
The documentation would probably benefit from a better description of sequencing events and how to turn it on and off, because questions like https://github.com/micro-manager/pycro-manager/issues/553 arise periodically

**Comment by ieivanov** [comment]
I agree, happy to help with this

**Comment by henrypinkard** [comment]
That would be great!

**Comment by henrypinkard** [comment]
https://github.com/micro-manager/pycro-manager/pull/644
