### ISSUE TITLE
Use p-m to change displayed camera image in µ-m

### ISSUE THREAD

**Issue by WKrauze** [micro-manager/pycro-manager#557]
I am wondering if it is possible to use pycromanager to change the behaviour of micro-manager. I would like to control my home-built phase microscope with micro-manager - there I can easily set-up time-lapse capture, destination folder etc. However, in addition to camera image shown in micro-manager, I would like to see the live phase image (calculated on the fly based on camera image). I can imagine 2 possibilities: either I can control what is shown in micro-manager (I would change from standard image mode to phase mode) or I could create a new window that would show the live phase. However, I find it difficult to see if this is possible with pycromanager. Any help appreciated!

**Comment by henrypinkard** [comment]
There are a few different ways you might be able to do this.

To clarify that I understand correctly: you want to continue using the MM GUI rather than building your own, but you want to do image processing in python, and display the result, either in python or in the MM GUI. Is that right?

Do you need this to run without launching anything from python? Or is it okay to initiate acquisitions from a python script/GUI?

**Comment by WKrauze** [comment]
> To clarify that I understand correctly: you want to continue using the MM GUI rather than building your own, but you want to do image processing in python, and display the result, either in python or in the MM GUI. Is that right?

Yes, exactly.


> Do you need this to run without launching anything from python? Or is it okay to initiate acquisitions from a python script/GUI?

Both ways are fine. However, when launching acquisition I would like to be able to specify the measurement procedure through MM GUI (e.g. timelapse parameters, exposition, destination folder, ROI etc.).

**Comment by henrypinkard** [comment]
Have you read the documentation of/tried the [`Acquisition`](https://pycro-manager.readthedocs.io/en/latest/acq_events.html#acquisition) class? It doesn't use the mm GUI but there are only a few parameters and there mostly the same.

**Comment by WKrauze** [comment]
Ok, thank you for the information!
