### ISSUE TITLE
Continuous acquisition (aka Burst mode) not implemented

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#56]
In Micromanager setting the time point interval to 0 seconds runs the camera in continuous acquisition mode, in which the camera controls the acquisition rate and Micromanager listens for arriving images until the requested total number of images is received. 

https://micro-manager.org/wiki/Micro-Manager_User%27s_Guide#Multi-dimensional_acquisition

When `time_interval_s = 0`, `pycromanager` instead still triggers acquisition of frames one-by-one. The resulting acquisition rate is low and unpredictable. 

It'll be great to implement continuous acquisition mode when `time_interval_s = 0`. Continuous acquisition can also be run when all acquisition hardware (e.g. light sources or stages) are controlled through electronic signals: https://micro-manager.org/wiki/Hardware-based_Synchronization_in_Micro-Manager

**Comment by henrypinkard** [comment]
Yes, it is designed to do this, but I never got a chance to test on actual hardware (and now don't have access to any). Do you have access to your setup with this configured? I could probably remote control and get it working pretty quickly

**Comment by ieivanov** [comment]
Hi @henrypinkard, yes, we can certainly help. We'll discuss ways to do that on Monday, and I'll let you know what the options are. Thanks for your help on this also.

**Comment by dpshepherd** [comment]
We are also happy to provide remote access to working setups that use hardware triggering + continuous acquisition. Having this functionality is key for two of projects we would potentially use pycro-manager for.

**Comment by henrypinkard** [comment]
Great. One or both of you could email me and we can find a time for remote control.

hbp
atsymbol
berkeley
dot
edu

**Comment by henrypinkard** [comment]
From an email correspondence with @dpshepherd, it sounds like their setup is not the conventional way that a micro-manager MDA would sequence hardware, so maybe it makes sense to start with your setup @ieivanov, since everything is already designed to work with this and it just needs to be debugged

**Comment by henrypinkard** [comment]
This all works now and will soon be available in nightly builds (https://github.com/micro-manager/micro-manager/pull/855). Closing and creating a separate issue for @dpshepherd's external triggering setup
