### ISSUE TITLE
Stop a running acquisition in sequencing mode (acq.abort() not functional)

### ISSUE THREAD

**Issue by Fredxxx** [micro-manager/pycro-manager#573]
An _Aqcuisition_ in sequencing mode cannot be stopped. This would be very helpful for time series or longer acquisitions.

It is not possible to use _acq.abort()_ in sequencing mode and the _events_ cannot be thrown. 

The work aorund at the moment is to restart uManager and pycromanager. This is very inconvenient, especially because during restart the hardware is set to default values, which might damage the sample.

**Comment by Fredxxx** [comment]
I just tried it, but it still freezes microManager

**Comment by henrypinkard** [comment]
attempt at fixing this in https://github.com/micro-manager/AcqEngJ/pull/77

Now going to write some testing code to ensure it works

**Comment by henrypinkard** [comment]
This now works on the demo configuration and passes tests for a timelapse and a zstack. Let me know if you run into any issues
