### ISSUE TITLE
Bridge object - example in readthedocs

### ISSUE THREAD

**Issue by kmpape** [micro-manager/pycro-manager#574]
I am new to using MM and pycro-manager and I found the example [Closed-loop acquisition and perturbation with pycro-manager](https://pycro-manager.readthedocs.io/en/latest/application_notebooks/closedloop_headless_demo.html) to be unclear as it imports a `Bridge` object, which does not seem to exist after installing  pycro-manager usin pip. Is the `Bridge` class now handled internally and covered by `Core`, or is there possibly something wrong with my installation? In addition, I am unable to find a `Core` method that does something similar to `Bridge.close()` provided in the above example.

I have installed version 0.27.2.  Thank you very much.

**Comment by henrypinkard** [comment]
> Is the `Bridge` class now handled internally and covered by `Core`

Yes, exactly.

> I am unable to find a `Core` method that does something similar to `Bridge.close()` provided in the above example.

You don't need to call `close()` in the newer versions. Everything gets cleaned up automatically by the python garbage collector

**Comment by mcgheealex** [comment]
How would you modify this code to capture an image

# simple single image acquisition example with snap
from pycromanager import Bridge
import numpy as np
import matplotlib.pyplot as plt
import time

#### Setup ####
bridge = Bridge()
core = bridge.get_core()

#### imaging settings
exposure = 20
num_frames_to_capture = 100
core.set_exposure(exposure)

#### strobe settings
# by enforcing a strobe (a small delay between acquisitions), our snap_image acquisition framerate becomes an order of magnitude more precise (as of 20201006)
interframe_interval = 50
assert interframe_interval > exposure

#### holder variables for images, model values, and processing timestamps
frames = []
model = []
acq_timestamps = []
process_timestamps = []

**Comment by henrypinkard** [comment]
@mcgheealex as a beginner it can be very helpful to thoroughly read through the documentation, as many answers to common questions are already in there. Also, in general it is helpful to ask specific questions and detail what things you have already tried, what went wrong, what you are confused about, etc. I am happy to help resolve confusions after you have done that.
