### ISSUE TITLE
from pycromanager import Bridge    Not working for me

### ISSUE THREAD

**Issue by mcgheealex** [micro-manager/pycro-manager#577]
I am a beginner and I have gone through the instructions to install micromanager 2.0 and pycromanager.

running this code works :
from pycromanager import Core

core = Core()
print(core)

However, running this code results in the following error
from pycromanager import Bridge

bridge = Bridge()
bridge.get_core()

ImportError: cannot import name 'Bridge' from 'pycromanager' (C:\Python311\Lib\site-packages\pycromanager\__init__.py)

Is there anything else I need to install beforehand to make this work?

**Comment by henrypinkard** [comment]
Nope, you should be all set. The Bridge is now hidden behind the scenes--you no longer need to call it in new versions

**Comment by mcgheealex** [comment]
Ok, it seems that the Bridge class is now baked into Core.

so how do I modify my code (below) to remove the bridge 
def video_stream(queue):
    bridge = Bridge()
    core = bridge.get_core()

    while True:
        # Acquire an image from the camera
        img = core.snap_image()

        # Convert the image to an OpenCV-compatible format
        img = np.array(img, dtype=np.uint8)

        # Convert the image from grayscale to RGB
        img_rgb = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

        # Send the RGB image to the GUI process
        queue.put(img_rgb)
