### ISSUE TITLE
Improve testing documentation

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#608]
Add documentation on how `pytest` installs MM and updates `.jar` files.

Outline the structure of the `test` folder and suggest what kinds of tests belong where.

**Comment by ieivanov** [comment]
See: 

https://github.com/micro-manager/pycro-manager/pull/562#issuecomment-1460686653
https://github.com/micro-manager/pycro-manager/pull/592#issuecomment-1572736071

**Comment by ieivanov** [comment]
@henrypinkard I am planning to describe the testing infrastructure in [Contributing.md](https://github.com/micro-manager/pycro-manager/blob/main/Contributing.md). 

The contributing guide is currently a bit heavy on instruction on how to use git. Do you mind if I shorten these sections a bit and instead add links to the github documentation? For example, the `Keeping your branches up-to-date` section can describe the purpose of syncing your fork and provide a link to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork. This gives users more options on how to do that, and helps keep our instruction more general - for example, the current version still references a `master` branch, which doesn't exist anymore.

**Comment by henrypinkard** [comment]
Yes, please edit as you see fit. I copied that from another project a while back so I'm not surprised its out of date
