### ISSUE TITLE
Long term acquisition bug might still be there.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#615]
Hi,

While the last fix clearly made things better, I think there is still an issue with the time required to do the write of the NFTiff store increasing over the duration of a long acquisition.  I have put timers around the call to dataset._add_index_entry in the storage management thread and it seems to be steadily increasing.  

The test case is pretty simple... I startup a headless micromanager using the demo driver and just do a big acquisition against it.  You should see increase with an event size of 50K.

I didn't see this before because my 1 hour long test runs fine.  I tried a two hour long acqusision and the problem returned.
Thanks,

Carl

#

**Comment by carlkesselman** [comment]
Looks like this is the offending code in _add_index_entry in ndtiff:

```for axis_name in axes.keys():     
        if axis_name not in self.axes.keys():         
            self.axes[axis_name] = [] 
            self.axes_types[axis_name] = type(axes[axis_name]) 
            self.axes[axis_name].append(axes[axis_name])
             self.axes[axis_name] = sorted(list(set(self.axes[axis_name])))
```

**Comment by henrypinkard** [comment]
Thanks for tracking that down. That makes sense why it eventually causes a problem and I agree that it should be constant time. 

I believe the reason they are sorted is for the `as_array` function to put all the individual images in the correct order. I'm not recalling why they also have to be in a list instead of a set...but I don't think that's just extraneous. So it would seem the requirements as the code is written now is that they are 1) unique 2) sorted 3) in a `list`. Can bisect make this work with these requirements, without assuming that all the values are sequential?

**Comment by carlkesselman** [comment]
There is also: https://grantjenks.com/docs/sortedcontainers/

This seems to be popular, but now unclear if its still in active development.

The set and sort on read approach would seem to me to be the closest to constant time.

Carl



On Jun 12, 2023, at 9:23 AM, Carl Kesselman ***@***.***> wrote:

One option would be to put the sorting in as_array and you could cache the result?  Then you could just keep everything as a set and it would be better?

I’ve been thinking about this.. .the set is implemented as a hash table, which I think would be suboptimal for the time access. A more complicated result would be to detect if you are looking at a monotonically increasing sequence, store that as a list using just append, and convert to the set version if you violate the condition.

I think bisect will do the right thing. Rather than convert to a set, I would just use index to look up if the element already exists (log(N)) and the just insert (log(N))

Carl


On Jun 12, 2023, at 8:55 AM, Henry Pinkard ***@***.***> wrote:



Thanks for tracking that down. That makes sense why it eventually causes a problem and I agree that it should be constant time.

I believe the reason they are sorted is for the as_array function to put all the individual images in the correct order. I'm not recalling why they also have to be in a list instead of a set...but I don't think that's just extraneous. So it would seem the requirements as the code is written now is that they are 1) unique 2) sorted 3) in a list. Can bisect make this work with these requirements, without assuming that all the values are sequential?

**Comment by henrypinkard** [comment]
> I think bisect will do the right thing. Rather than convert to a set, I would just use index to look up if the element already exists (log(N)) and the just insert (log(N))

This seems like the most promising option. Do you want to try it out and see if it gives sufficient performance?

**Comment by carlkesselman** [comment]
Sure… I’ll give it a shot.

Carl


On Jun 12, 2023, at 9:43 AM, Henry Pinkard ***@***.***> wrote:



I think bisect will do the right thing. Rather than convert to a set, I would just use index to look up if the element already exists (log(N)) and the just insert (log(N))

This seems like the most promising option. Do you want to try it out and see if it gives sufficient performance?

**Comment by carlkesselman** [comment]
Ok…

If you are willing to use the sorted containers library, then there is an order log(N) solution that requires very few code changes.

Basically store index as a SortedSet, add elements one at a time, and then in one place in as_array, you need to add a list() function.

Carl


On Jun 12, 2023, at 10:23 AM, Carl Kesselman ***@***.***> wrote:

Actually, I take it back…..

bisect.insort_right(a, x, lo=0, hi=len(a), *, key=None)
bisect.insort(a, x, lo=0, hi=len(a), *, key=None)
Similar to insort_left(), but inserting x in a after any existing entries of x.

This function first runs bisect_right() to locate an insertion point. Next, it runs the insert() method on a to insert x at the appropriate position to maintain sort order.

To support inserting records in a table, the key function (if any) is applied to x for the search step but not for the insertion step.

Keep in mind that the O(log n) search is dominated by the slow O(n) insertion step.

So while this would be several times better than the current approach, it will still be order N in the number of axis values, which I think is going to be a problem for the time axis.  I think the simplest option is to keep this as a set, which will support constant time insertion and then you pay the price when you want as_array.  This will shift the cost from creation to reading, but in total, the cost for doing the conversion of set to list and than sorting once if as_array is called, will still be a lot less than what is currently there.

Otherwise, I think the only viable solution is to use the proper SortedList library which will use a btree, or some such thing while providing a list interface.

Carl

On Jun 12, 2023, at 10:07 AM, Carl Kesselman ***@***.***> wrote:

Sure… I’ll give it a shot.

Carl


On Jun 12, 2023, at 9:43 AM, Henry Pinkard ***@***.***> wrote:



I think bisect will do the right thing. Rather than convert to a set, I would just use index to look up if the element already exists (log(N)) and the just insert (log(N))

This seems like the most promising option. Do you want to try it out and see if it gives sufficient performance?

**Comment by carlkesselman** [comment]
Two hour run… rock solid.  Not a frame dropped, no increase in add_index time.

I can clone and do a PR on NDTiff if you like.  Changes are really small.

Carl


On Jun 12, 2023, at 3:13 PM, Carl Kesselman ***@***.***> wrote:

Ok…

If you are willing to use the sorted containers library, then there is an order log(N) solution that requires very few code changes.

Basically store index as a SortedSet, add elements one at a time, and then in one place in as_array, you need to add a list() function.

Carl


On Jun 12, 2023, at 10:23 AM, Carl Kesselman ***@***.***> wrote:

Actually, I take it back…..

bisect.insort_right(a, x, lo=0, hi=len(a), *, key=None)
bisect.insort(a, x, lo=0, hi=len(a), *, key=None)
Similar to insort_left(), but inserting x in a after any existing entries of x.

This function first runs bisect_right() to locate an insertion point. Next, it runs the insert() method on a to insert x at the appropriate position to maintain sort order.

To support inserting records in a table, the key function (if any) is applied to x for the search step but not for the insertion step.

Keep in mind that the O(log n) search is dominated by the slow O(n) insertion step.

So while this would be several times better than the current approach, it will still be order N in the number of axis values, which I think is going to be a problem for the time axis.  I think the simplest option is to keep this as a set, which will support constant time insertion and then you pay the price when you want as_array.  This will shift the cost from creation to reading, but in total, the cost for doing the conversion of set to list and than sorting once if as_array is called, will still be a lot less than what is currently there.

Otherwise, I think the only viable solution is to use the proper SortedList library which will use a btree, or some such thing while providing a list interface.

Carl

On Jun 12, 2023, at 10:07 AM, Carl Kesselman ***@***.***> wrote:

Sure… I’ll give it a shot.

Carl


On Jun 12, 2023, at 9:43 AM, Henry Pinkard ***@***.***> wrote:



I think bisect will do the right thing. Rather than convert to a set, I would just use index to look up if the element already exists (log(N)) and the just insert (log(N))

This seems like the most promising option. Do you want to try it out and see if it gives sufficient performance?
