### ISSUE TITLE
Potential Issue with large acquisition with big images

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#619]
### Bug report

I am seeing some behavior that might indicate a problem with large acquisitions of big images.  I'm running a hamamatsu camera at about 25 frames per second for an extended period of time.  Everything looks good for about 6000 images.  At that point the core log reports an immediate jump in the image queue from 0 to 30.  If you look at the sequence buffer monitor in micromanager, everything is fine up until about the same point, at which time the sequence buffer size starts to increase and never recovers.  If there is enough memory, this manifests in dropped images, if not, out of memory space.

This issue definitely seems to be on the image acquisition side.  I'm wondering if there might be something going on in the java part of NDTIff.  The fact that it seems find up until a certain point and then starts falling behind is curious.  I will verify if I see the same problem in pure micromanager without pycromanager.

Carl

**Comment by henrypinkard** [comment]
Check out this [speed test code also](https://github.com/henrypinkard/pycro-manager/blob/main/scripts/speed_test.py)

Running this generates csv files, which you can then plug into [this notebook](https://github.com/micro-manager/micro-manager/blob/main/acqengj_speed_test/analysis.ipynb) to see some more diagonostics:

From there you can figure out where backups occur: the circular buffer, the acquisition engine, or NDTiff

Let me know if you have questions on how to use it

**Comment by carlkesselman** [comment]
Hi,  

Its looking like this might be operator error in that I was at the edge of what the disk could to.  It is interesting to note that writing OME tiff seems to put less stress on the disk than NDTiff option even from micromanager console.  Perhaps this is because of pyramids?

**Comment by henrypinkard** [comment]
Are you doing tiling? pyramids are off by default. but if you are, then that would make sense

**Comment by carlkesselman** [comment]
Nope… just ticking off the NDTiff box in the out of the box micromanager interface.  Ny pycromanager here at all.


Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 19, 2023 at 12:06 PM -0700, Henry Pinkard ***@***.***>, wrote:

Are you doing tiling? pyramids are off by default. but if you are, then that would make sense

**Comment by henrypinkard** [comment]
Hmmm then I'm not sure. NDTiff is definitely faster than OME-Tiff, but the amount of data they write should be the same

**Comment by carlkesselman** [comment]
Don’t know what is going on then.

This was out of the box micro-manager, multi-dimensional acquisiton, external trigger on a hammamastu camera at about 25FPS.

With OME-Tiff file save no problem.  Sequence buffer stayed at 0 or an occasional blip to 1 or 2.

With NDTiff file save, we saw the problem that after a few thousand images, the sequence buffer started filling up, ran out of space, and then aborted when it ran out of memory.

There was no other change between the two runs.

Lowering the framerate or setting a ROI seemed to fix (or at least delay) the problem.

I was seeing the same behavior in pycromanager, so I found the fact that you see it in micromanager makes me wonder if there is something not quite right in the image saving routine on the Java side.

Trying to work around this led me to the problem I’m having setting ROI in pycromanager, which seems to work ok in micromanager.

Carl


On Jun 19, 2023, at 3:27 PM, Henry Pinkard ***@***.***> wrote:



Hmmm then I'm not sure. NDTiff is definitely faster than OME-Tiff, but the amount of data they write should be the same

**Comment by henrypinkard** [comment]
> I was seeing the same behavior in pycromanager, so I found the fact that you see it in micromanager makes me wonder if there is something not quite right in the image saving routine on the Java side.

I'd be surprised, since lots of people rely on this code and it rarely changes. Running the speed tests is the best diagnostic for this.

**Comment by carlkesselman** [comment]
Ok… I’ll do that.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 19, 2023 at 3:41 PM -0700, Henry Pinkard ***@***.***>, wrote:

I was seeing the same behavior in pycromanager, so I found the fact that you see it in micromanager makes me wonder if there is something not quite right in the image saving routine on the Java side.

I'd be surprised, since lots of people rely on this code and it rarely changes. Running the speed tests is the best diagnostic for this.
