### ISSUE TITLE
Acquisition hangs when setting ROI.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#620]
### Bug report

**Bug summary**

It seems that pycromanager is hanging after attempting to set the ROI.  The following code will not complete when run against the demo camera.
**Code for reproduction**

```python
Core().set_roi(Core().get_camera_device(), 0,0,256,256) 
roi = Core().get_roi(Core().get_camera_device()) 
print(f"ROI {[roi.x, roi.y, roi.width, roi.height]}")
 e = multi_d_acquisition_events(num_time_points=5) 
with pycromanager.Acquisition(directory="foo", name="test") as mmacquisition: 
    print(f"Start acquisition")     
   mmacquisition.acquire(e)
 print(f"Acquisition complete")
```

**Expected outcome**
Completion

**Actual outcome**
Acquisition never completes

**Version Info**
Latest version of everything from repo.  Running on Windows 10.

**Comment by henrypinkard** [comment]
Im not able to reproduce running on demo config. Is it possible something is amiss with the particular hard drive you're using?

If you want to test further whether this is specific to your system, you could try submitting a PR with this added to the tests and see if it completes successfully

**Comment by carlkesselman** [comment]
Hmm... this is consistently failing for me.  In poking around, it looks like the events are never processed so this hangs in the await_completion call. Only happens if I have the set_roi, if its just get_roi, everything is ok.

I'm running latest version of everything on Windows 10.  

Any suggestions as to where I might look to figure out what is going on?

Carl

**Comment by henrypinkard** [comment]
I think I might have seen this the other day on an actual system, which used a Basler camera. Have you been seeing this with a Basler too? Do you have another camera you can swap and test? This may be a device adapter bug, which would explain why it doesn't happen with the demo config

**Comment by carlkesselman** [comment]
Actually, I’m seeing this with the demo config on my system.  I have checked this carefully, but will do so again.

Carl


On Jun 21, 2023, at 5:39 PM, Henry Pinkard ***@***.***> wrote:



I think I might have seen this the other day on an actual system, which used a Basler camera. Have you been seeing this with a Basler too? Do you have another camera you can swap and test? This may be a device adapter bug, which would explain why it doesn't happen with the demo config

**Comment by henrypinkard** [comment]
If thats the case, then I think the best course of action would be to add to the [acquisition tests](https://github.com/micro-manager/pycro-manager/blob/main/pycromanager/test/test_acquisition.py) and make a PR. That would guard this from being a bug in the future, and it would help me figure out why i dont see it. 

You could also try turning on `debug` and `core_log_debug` in the acquisition and checking the python console and MM core log for anything suspicious

**Comment by carlkesselman** [comment]
I”m seeing funny things… hold off until I can do a bit more. testing.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 22, 2023 at 1:34 PM -0700, Henry Pinkard ***@***.***>, wrote:

If thats the case, then I think the best course of action would be to add to the acquisition tests<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_blob_main_pycromanager_test_test-5Facquisition.py&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=Y4HbnVNv1NNqs-u74J0fR0Z_zTwn3buFkqr84CcZqtAb_JReDmv002MsRuerMV2Q&s=zCrkA1l-EjifkxXQ8x5d7fgw8RiBRKUpvpGI13AvTmc&e=> and make a PR. That would guard this from being a bug in the future, and it would help me figure out why i dont see it.

You could also try turning on debug and core_log_debug in the acquisition and checking the python console and MM core log for anything suspicious

**Comment by carlkesselman** [comment]
Yea, on Hamamatsu camera, if I set the ROI thrugh the Core object, I don’t get any images from the acquisitoin.  If I don’t set the ROI, everything is fine.  After setting the ROI, if I query, I do get back the updated value.

It looks like there is no code available for this driver…. but I wonder if the issue is somewhere in the shadow object?

Carl


On Jun 22, 2023, at 1:42 PM, Carl Kesselman ***@***.***> wrote:

I”m seeing funny things… hold off until I can do a bit more. testing.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 22, 2023 at 1:34 PM -0700, Henry Pinkard ***@***.***>, wrote:


If thats the case, then I think the best course of action would be to add to the acquisition tests<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_blob_main_pycromanager_test_test-5Facquisition.py&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=Y4HbnVNv1NNqs-u74J0fR0Z_zTwn3buFkqr84CcZqtAb_JReDmv002MsRuerMV2Q&s=zCrkA1l-EjifkxXQ8x5d7fgw8RiBRKUpvpGI13AvTmc&e=> and make a PR. That would guard this from being a bug in the future, and it would help me figure out why i dont see it.

You could also try turning on debug and core_log_debug in the acquisition and checking the python console and MM core log for anything suspicious

**Comment by carlkesselman** [comment]
Ok… this seems to definitely be an issue with the hamamatsu drive.  The funny thing is that it seems to be ok when done from the script interface.  Also, if I do set_roi with the full camera size, its fine, but if I do any other size via the API the camera seems to go nuts.

Is there a difference in how the camera is controled when going via the micromanager script interface and the pycromanager API?

Thanks,

Carl


On Jun 28, 2023, at 8:19 PM, Carl Kesselman ***@***.***> wrote:

Yea, on Hamamatsu camera, if I set the ROI thrugh the Core object, I don’t get any images from the acquisitoin.  If I don’t set the ROI, everything is fine.  After setting the ROI, if I query, I do get back the updated value.

It looks like there is no code available for this driver…. but I wonder if the issue is somewhere in the shadow object?

Carl


On Jun 22, 2023, at 1:42 PM, Carl Kesselman ***@***.***> wrote:

I”m seeing funny things… hold off until I can do a bit more. testing.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 22, 2023 at 1:34 PM -0700, Henry Pinkard ***@***.***>, wrote:


If thats the case, then I think the best course of action would be to add to the acquisition tests<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_blob_main_pycromanager_test_test-5Facquisition.py&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=Y4HbnVNv1NNqs-u74J0fR0Z_zTwn3buFkqr84CcZqtAb_JReDmv002MsRuerMV2Q&s=zCrkA1l-EjifkxXQ8x5d7fgw8RiBRKUpvpGI13AvTmc&e=> and make a PR. That would guard this from being a bug in the future, and it would help me figure out why i dont see it.

You could also try turning on debug and core_log_debug in the acquisition and checking the python console and MM core log for anything suspicious

**Comment by carlkesselman** [comment]
A little more testing…..

Use micromanager server, not headless mode.  Test program uses pycromanager, just does a acquire of a couple events using a with block.

I use the script interface in micromanager to change the ROI.  If I set to full resolution (2048x2048) everything is fine.  If I use the script interface (mmc.setROI) to change the ROI to anything else, the acquisition hangs in pycromanager.  However, if I do the exact same acquisition in micromanger, it works fine.

Any thoughts?

Carl


On Jul 5, 2023, at 9:12 AM, Carl Kesselman ***@***.***> wrote:

Ok… this seems to definitely be an issue with the hamamatsu drive.  The funny thing is that it seems to be ok when done from the script interface.  Also, if I do set_roi with the full camera size, its fine, but if I do any other size via the API the camera seems to go nuts.

Is there a difference in how the camera is controled when going via the micromanager script interface and the pycromanager API?

Thanks,

Carl


On Jun 28, 2023, at 8:19 PM, Carl Kesselman ***@***.***> wrote:

Yea, on Hamamatsu camera, if I set the ROI thrugh the Core object, I don’t get any images from the acquisitoin.  If I don’t set the ROI, everything is fine.  After setting the ROI, if I query, I do get back the updated value.

It looks like there is no code available for this driver…. but I wonder if the issue is somewhere in the shadow object?

Carl


On Jun 22, 2023, at 1:42 PM, Carl Kesselman ***@***.***> wrote:

I”m seeing funny things… hold off until I can do a bit more. testing.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine
Fellow, Information Sciences Institute
Viterbi School of Engineering


University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 22, 2023 at 1:34 PM -0700, Henry Pinkard ***@***.***>, wrote:


If thats the case, then I think the best course of action would be to add to the acquisition tests<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_blob_main_pycromanager_test_test-5Facquisition.py&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=Y4HbnVNv1NNqs-u74J0fR0Z_zTwn3buFkqr84CcZqtAb_JReDmv002MsRuerMV2Q&s=zCrkA1l-EjifkxXQ8x5d7fgw8RiBRKUpvpGI13AvTmc&e=> and make a PR. That would guard this from being a bug in the future, and it would help me figure out why i dont see it.

You could also try turning on debug and core_log_debug in the acquisition and checking the python console and MM core log for anything suspicious

**Comment by henrypinkard** [comment]
> Is there a difference in how the camera is controled when going via the micromanager script interface and the pycromanager API?

if you're doing `mmc.` in the script interface versus `core.` in PM, then no. These should be the exact same. 

> I use the script interface in micromanager to change the ROI. If I set to full resolution (2048x2048) everything is fine. If I use the script interface (mmc.setROI) to change the ROI to anything else, the acquisition hangs in pycromanager. However, if I do the exact same acquisition in micromanger, it works fine. Any thoughts?

This sounds to me like there is a bug in the Hammumatsu code for setting ROIs that gets the camera into a bad state, and then the acquisition engine gets stuck due to some freeze.


I think the easiest way to debug this would be to make a script that calls the core directly and see if you can isolate the problem with a minimal example. It should be something like this (I didn't test it--might need some tweaking):

```python
sequence_length = 100

# TODO: change ROI

if sequence_length == 1:
   core.snap_image()
else:
   core.start_sequence_acquisition(100, 0, True) # acquire 100 images


if sequence_length == 1:
   image = core.get_tagged_image(0)
else:
   count = 0   
   while count < sequence_length:
      try:
        image = core.pop_next_tagged_image()
        count += 1
     except:
        pass
```

**Comment by carlkesselman** [comment]
Ok… interesting.

If I set ROI and then run acquision using Acquisition class, things hang.

If I set ROI and then run your code, it works.

If I then run the code that uses the Acquisition class after running the snap_image  code, it no longer hangs.

So while this does suggest something funny is going on in the camera, its still curious that the behavior when using snap_image/get_tagged_image is different than using the Acquisition class.

Carl


On Jul 6, 2023, at 10:24 AM, Henry Pinkard ***@***.***> wrote:



Is there a difference in how the camera is controled when going via the micromanager script interface and the pycromanager API?

if you're doing mmc. in the script interface versus core. in PM, then no. These should be the exact same.

I use the script interface in micromanager to change the ROI. If I set to full resolution (2048x2048) everything is fine. If I use the script interface (mmc.setROI) to change the ROI to anything else, the acquisition hangs in pycromanager. However, if I do the exact same acquisition in micromanger, it works fine. Any thoughts?

This sounds to me like there is a bug in the Hammumatsu code for setting ROIs that gets the camera into a bad state, and then the acquisition engine gets stuck due to some freeze.

I think the easiest way to debug this would be to make a script that calls the core directly and see if you can isolate the problem with a minimal example. It should be something like this (I didn't test it--might need some tweaking):

sequence_length = 100

# TODO: change ROI

if sequence_length == 1:
   core.snap_image()
else:
   core.start_sequence_acquisition(100, 0, True) # acquire 100 images


if sequence_length == 1:
   image = core.get_tagged_image(0)
else:
   count = 0
   while count < sequence_length:
      try:
        image = core.pop_next_tagged_image()
        count += 1
     except:
        pass

**Comment by carlkesselman** [comment]
Ok… so here is the funny bit.  If I add:


core.start_sequence_acquisition(1, 0, True)  # acquire 100 images
try:
    image = core.pop_next_tagged_image()
except:
    pass

to my code, after I set the ROI, then the subsequent Acquisition class operations seem to work.

While I am prepared to believe that there is something wonky in the camera driver… it also does seem that there is something slightly different going on in the acquisition code that is causing this issue to show up.

Carl



On Jul 6, 2023, at 11:48 AM, Carl Kesselman ***@***.***> wrote:

Ok… interesting.

If I set ROI and then run acquision using Acquisition class, things hang.

If I set ROI and then run your code, it works.

If I then run the code that uses the Acquisition class after running the snap_image  code, it no longer hangs.

So while this does suggest something funny is going on in the camera, its still curious that the behavior when using snap_image/get_tagged_image is different than using the Acquisition class.

Carl


On Jul 6, 2023, at 10:24 AM, Henry Pinkard ***@***.***> wrote:



Is there a difference in how the camera is controled when going via the micromanager script interface and the pycromanager API?

if you're doing mmc. in the script interface versus core. in PM, then no. These should be the exact same.

I use the script interface in micromanager to change the ROI. If I set to full resolution (2048x2048) everything is fine. If I use the script interface (mmc.setROI) to change the ROI to anything else, the acquisition hangs in pycromanager. However, if I do the exact same acquisition in micromanger, it works fine. Any thoughts?

This sounds to me like there is a bug in the Hammumatsu code for setting ROIs that gets the camera into a bad state, and then the acquisition engine gets stuck due to some freeze.

I think the easiest way to debug this would be to make a script that calls the core directly and see if you can isolate the problem with a minimal example. It should be something like this (I didn't test it--might need some tweaking):

sequence_length = 100

# TODO: change ROI

if sequence_length == 1:
   core.snap_image()
else:
   core.start_sequence_acquisition(100, 0, True) # acquire 100 images


if sequence_length == 1:
   image = core.get_tagged_image(0)
else:
   count = 0
   while count < sequence_length:
      try:
        image = core.pop_next_tagged_image()
        count += 1
     except:
        pass

**Comment by henrypinkard** [comment]
> Ok… so here is the funny bit. If I add: core.start_sequence_acquisition(1, 0, True) # acquire 100 images try: image = core.pop_next_tagged_image() except: pass to my code, after I set the ROI, then the subsequent Acquisition class operations seem to work. While I am prepared to believe that there is something wonky in the camera driver… it also does seem that there is something slightly different going on in the acquisition code that is causing this issue to show up.

Oh that is strange. I think the easiest way to debug this is to get a debugger in the Java code for the acquisition engine. Are you willing/able to give that a try? I can guide you through the setup

**Comment by carlkesselman** [comment]
Hi,

Willing to give a try, but I’m not really a Java programmer.  Let me wait until someone in my group who is comes back from vacation and I’ll give it a shot.  I may need help on the setup.

Thanks,

Carl


On Jul 6, 2023, at 4:18 PM, Henry Pinkard ***@***.***> wrote:



Ok… so here is the funny bit. If I add: core.start_sequence_acquisition(1, 0, True) # acquire 100 images try: image = core.pop_next_tagged_image() except: pass to my code, after I set the ROI, then the subsequent Acquisition class operations seem to work. While I am prepared to believe that there is something wonky in the camera driver… it also does seem that there is something slightly different going on in the acquisition code that is causing this issue to show up.

Oh that is strange. I think the easiest way to debug this is to get a debugger in the Java code for the acquisition engine. Are you willing/able to give that a try? I can guide you through the setup

**Comment by henrypinkard** [comment]
Okay sounds good. There's some setup instructions [here](https://github.com/micro-manager/pycro-manager/issues/123). Don't hesitate to ask questions once you get to it

**Comment by henrypinkard** [comment]
Okay I made a PR that I think fixes this. In the mean time you may be able to work around by calling `core.initialize_circular_buffer()` just after setting the ROI

Thanks for the patience with this @carlkesselman !

**Comment by carlkesselman** [comment]
Yep… the work around fixes my issue.

Thanks!!

Carl


On Jul 29, 2023, at 9:58 AM, Henry Pinkard ***@***.***> wrote:

ore.initialize_circular_buffer()
