### ISSUE TITLE
Zoom/pan controls in the acquisition window

### ISSUE THREAD

**Issue by ckolluru** [micro-manager/pycro-manager#621]
Hi,

Is there a feature for zooming in/out and panning of the acquired image in the acquisition window that is launched from pycromanager?

When running an acquisition from micromanager, I can click and use the tools in the imageJ window on the acquisition window.

Thanks,
Chaitanya

**Comment by henrypinkard** [comment]
Yes if you scroll the mouse wheel or press +/-

**Comment by ckolluru** [comment]
Got it, the +/- buttons work for me. Thanks.
