### ISSUE TITLE
NDViewer histograms do not render properly 

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#624]
Running on Windows.

<img width="1496" alt="Screenshot 2023-06-27 at 12 57 21 PM" src="https://github.com/micro-manager/pycro-manager/assets/11934632/025e8250-4c7e-4b2a-8b3d-d00cfc464c9f">

**Comment by henrypinkard** [comment]
Always? Or specific conditions needed to reproduce?

**Comment by ieivanov** [comment]
I think I saw this behavior during the viewer tests (`test_multi_d_acq_NDViewer`?), but I haven't looked closer. Let me know if you can't replicate it.

**Comment by henrypinkard** [comment]
Should be fixed by https://github.com/micro-manager/NDViewer/pull/33

I did a big internal refactor to clean up a lot of confusing code. I tested everything fairly well, but may be worth keeping an eye out for subtle bugs that may arise
