### ISSUE TITLE
How to Emulate images?

### ISSUE THREAD

**Issue by michaelpmay** [micro-manager/pycro-manager#630]
Hello, 

I am trying to write a python side emulator that loads some images before-hand and overwrites the acquired images with my own.

Currently, I can display an image as my own using an image hook, but I'm unsure if this also saves the images too.

How would I start doing this?

Thanks

**Comment by henrypinkard** [comment]
If you return the images from an image processor they will save to disk. Try it out by opening with a `Dataset`

**Comment by michaelpmay** [comment]
Thanks!
