### ISSUE TITLE
Translate Python variable types to Java data types for Micro-Manager Core?

### ISSUE THREAD

**Issue by ischoegl** [micro-manager/pycro-manager#64]
First of all, it's great to find this project! - I successfully tested the interface (following your [Controlling Micro-Manager Core](https://pycro-manager.readthedocs.io/en/latest/core.html) tutorial) for a machine vision camera we're using, and most things appear to work really smoothly.

While testing, I tried to get/set the ROI / region of interest from `pycromanager`. While the methods `core.get_roi` and `core.set_roi` exist as expected (considering `snake_case` vs `CamelCase`), only the latter works. The former results in an error:
```
[...]

In [10]: a = b = c = d = 0

In [11]: core.get_roi(a, b, c, d)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-71-df0daa3b1c10> in <module>
----> 1 core.get_roi(a, b, c, d)

~\miniconda3\envs\crio\lib\site-packages\pycromanager\core.py in <lambda>(instance, signatures_list, *args)
    261                 params, methods_with_name, method_name_modified = _parse_arg_names(methodSpecs, method_name, convert_camel_case)
    262                 return_type = methods_with_name[0]['return-type']
--> 263                 fn = lambda instance, *args, signatures_list=tuple(methods_with_name): instance._translate_call(signatures_list, args)
    264                 fn.__name__ = method_name_modified
    265                 fn.__doc__ = "{}.{}: A dynamically generated Java method.".format(_java_class, method_name_modified)

~\miniconda3\envs\crio\lib\site-packages\pycromanager\core.py in _translate_call(self, method_specs, fn_args)
    341         #args that are none are placeholders to allow for polymorphism and not considered part of the spec
    342         # fn_args = [a for a in fn_args if a is not None]
--> 343         valid_method_spec = _check_method_args(method_specs, fn_args)
    344         #args are good, make call through socket, casting the correct type if needed (e.g. int to float)
    345         message = {'command': 'run-method', 'hash-code': self._hash_code, 'name': valid_method_spec['name'],

~\miniconda3\envs\crio\lib\site-packages\pycromanager\core.py in _check_method_args(method_specs, fn_args)
    467
    468     if valid_method_spec is None:
--> 469         raise Exception('Incorrect arguments. \nExpected {} \nGot {}'.format(
    470             ' or '.join([', '.join(method_spec['arguments']) for method_spec in method_specs]),
    471             ', '.join([str(type(a)) for a in fn_args]) ))

Exception: Incorrect arguments.
Expected  or java.lang.String or int[], int[], int[], int[] or java.lang.String, int[], int[], int[], int[]
Got <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>
```
I am admittedly not very familiar with Micro-Manager, and loosely followed a [Beanshell example](https://micro-manager.org/w/images/d/df/Roi_copy.bsh), so I may be overlooking something obvious. Regardless, the error stack points at `get_roi` requiring a conversion from Python to Java data types (call by reference vs call by value?). Looking at the source code, this may be part of the TODO comment ...

**Comment by henrypinkard** [comment]
Glad it is able to be useful to you! 

The python interface for controlling the core is being dynamically being translated to a [Java API](https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmcorej/mmcorej/CMMCore.html) for the core. Not every conversion from Java to python works so cleanly, and this is one example of that. The Java signature you're calling is `getROI(int[] x, int[] y, int[] xSize, int[] ySize)`, which expects the methods to fill in the values in the corresponding arrays.

So I think the solution here is to instead call `getROI() `, which will return a `java.awt.Rectangle`, on which you can then call `get_x()`, `get_width()`, etc

**Comment by ischoegl** [comment]
@henrypinkard ... thanks for your prompt response! And your solution works nicely, so thank you. 

When I posted the issue, I thought that there may be a way to generate Java objects based on the Python parameters on-the-fly. While Python by default passes arguments by reference, integers are still immutable, so I'm not sure that this can actually be solved.
