### ISSUE TITLE
unable to successfully connect micromanager

### ISSUE THREAD

**Issue by jdeseze** [micro-manager/pycro-manager#65]
Hi!
i'm sorry I think it's a basic issue but I couldn't find out how to solve it.
After installing pycromanager and the last version of micromanager, the two initial lines of codes gave this

In [1]:from pycromanager import Bridge
bridge = Bridge()
bridge.get_core()
Out[1]: <pycromanager.core.mmcorej_CMMCore at 0x172fdcfdac8>

then any command to micromanager would not do anything (without throwing any exception)
Thanks!

**Comment by henrypinkard** [comment]
Have you made sure to update to the latest versions of both micro-manager and pycro-manager?

If yes, and still having an issue, can you post the exception it throws?

**Comment by jdeseze** [comment]
ok problem solved. The connection was done but I hadn't seen the double _ in '__main__'
Thanks a lot!
