### ISSUE TITLE
Automated tests dont use latest source when PR includes changes to PycroManagerJava

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#653]
When making a PR with changes to PycroManagerJava, the tests do not use the latest source code (in the PR). This means that passing the tests requires changes there, they will not pass. In theory this should be possible by using maven to build the jar based on the latest source and using that to the run the tests, and I think thats what the testing framework is trying to do, but something must be going wrong...

**Comment by ieivanov** [comment]
@henrypinkard I think your experience is consistent with the current intended behavior. When the tests run in GitHub Action, we only use the `.jar` files which ship with Micro-manager. You're right that if we make changes to PycroManagerJava we should use that new code. Currently the `build_and_test.yml` workflow builds the PycroManagerJava.jar file, but it seems like we don't use it during testing. That can be fixed.

**Comment by henrypinkard** [comment]
Added as part of #685
