### ISSUE TITLE
Restart acquisition after abort

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#664]
@henrypinkard I'm dealing with a problem where the camera can drop a frame or miss a trigger pulse during a sequenced acquisition and the acquisition gets stuck waiting for a frame that would never arrive.

Is there a way for me to abort a sequenced acquisition and then send new events with non-overlapping axes? For example:

```python
acq = Acquisition(...)
events0 = multi_d_acquisition_events(z_start=0, z_end=999, z_step=1)
events1 = multi_d_acquisition_events(z_start=1000, z_end=1009, z_step=1)

acq.acquire(events0)
time.sleep(10)
acq.abort()  #terminate current acquisition, reset z stage sequence

acq.acquire(events1)
acq.mark_finished()
acq.await_completion()

dataset = acq.get_dataset()

assert(all([i in dataset.axes['z'] for i in range(1000, 1010)]))
```

With the current code, `acq.abort()` aborts the acquisition such that no new events are accepted and `dataset.axes['z']` is something like `[0, 1, 2, 3, 4, 5, 6, 7, 8]`

**Comment by ieivanov** [comment]
P.S. this example is not great, events should be, for example:

```python
events0 = [{'axes': {'z': i}, 'z': i} for i in range(20)]
events1 = [{'axes': {'z': i}, 'z': i} for i in range(20, 30)]
```

**Comment by henrypinkard** [comment]
Added this in: https://github.com/micro-manager/AcqEngJ/pull/101. Would be good if you could check it works as expected on real hardware

**Comment by ieivanov** [comment]
Thanks Henry, that looks like a good implementation! I'll give it a try, though likely not right away. I'll keep you posted.
