### ISSUE TITLE
Script hangs in headless mode

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#672]
Greetings,

I tried running the following snippet from command line:

```py
from pycromanager import Core, start_headless
from pymmcore_plus import find_micromanager 

import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger()

mm_app_path = find_micromanager()

logger.info("Found Micro-Manager at: " + mm_app_path)

config_file = mm_app_path + "/MMConfig_demo.cfg"

# Start the Java process
start_headless(mm_app_path, config_file)

logger.info("Started Micro-Manager headless, creating core... ")

core = Core()

logger.info("Done")
```

The script executes fine but after the last logging line the CLI hangs and I have to manually insert a keyboard interrupt to make the script stop. Am I doing something incorrectly?

Python version: 3.8.10
Pycromanager version: 0.28.1
MM Studio version: 2.0.2 20230819 (nightly build)
MMCore version: 10.4.0
Device API version 71, Module API version 10

**Comment by henrypinkard** [comment]
Hi Jacapo, try:

```
from pycromanager.acq_util import cleanup
cleanup()
```
 
At the end to shut down the headless process. 

Probably this needs to be added to the documentation (https://github.com/micro-manager/pycro-manager/issues/673)

**Comment by jacopoabramo** [comment]
Hi @henrypinkard , thanks for replying. I tried it, it still hangs after calling cleanup

**Comment by henrypinkard** [comment]
You're right. That function wasn't working. I just fixed it https://github.com/micro-manager/pycro-manager/pull/674/

I also changed the name to `stop_headless`

**Comment by henrypinkard** [comment]
@jacopoabramo 
I've just made some fixes to this in the latest versions (pypi/nightly build), let me know if you run into any more problems

**Comment by henrypinkard** [comment]
Oh it appears this is because `core` doesn't get garbage collected. I just was able to get this to work properly by adding in `core = None`. This is a bit confusing...I'm going to see if there's a way for this to happen automatically:

this script works for me:
```python
config_file = mm_app_path + "/MMConfig_demo.cfg"

print('starting headless')
start_headless(mm_app_path, config_file)
print('creating core')
core = Core()
core = None
stop_headless()
print('ending')
```

**Comment by henrypinkard** [comment]
Okay I think this is actually fixed now by https://github.com/micro-manager/pycro-manager/pull/700. You shouldn't need to set `core = None`. Let me know if this works for you

**Comment by jacopoabramo** [comment]
Hi @henrypinkard , that did the trick. Now the test script works either with or without the `stop_headless` method. Closing the issue.
