### ISSUE TITLE
Add cleanup() to headless mode docs

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#673]

**Comment by ieivanov** [comment]
I've haven't had good experience trying to call `cleanup()` independently. I most often run into problems when trying to quit an acquisition with Ctr+C.

The trick is that `cleanup()` needs to be called exactly once. It is always called when python exists normally, so the script will hang if you also try to call it once before. But apparently `atexit` registered functions are not called if the program does not exit normally, like with Ctr+C. I found [this topic](https://stackoverflow.com/questions/23468042/the-invocation-of-signal-handler-and-atexit-handler-in-python) but I haven't been able to get it to work yet - I need to close my terminal if I want to quit mid acquisition.

**Comment by henrypinkard** [comment]
Does this fix solve the problem for you? https://github.com/micro-manager/pycro-manager/pull/674
