### ISSUE TITLE
UserWarning on acquisition notification handler.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#678]
### Bug report

**Bug summary**

I am getting the following warning message.  Pip install of latest versions of pycromanager.  Have latest nightly build of micromanager installed.  It tells me not to worry, but I'm worried....

```
C:\ProgramData\Anaconda3\envs\spim-data\Lib\site-packages\pycromanager\acquisitions.py:366: UserWarning: Could not create acquisition notification handler. This should not affect performance, but indicates that Micro-Manager is out of date
  warnings.warn('Could not create acquisition notification handler. This should not affect performance,'
```

**Expected outcome**

**Actual outcome**

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 28.2
  * MicroManager version: 2.03 20230827
  * Python version: 3.11.5
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by henrypinkard** [comment]
Hahahah. I'm working on a branch that should enable a very useful new API and some cool functionality, which hopefully will be PRed soon and should fix this. Perhaps a more reassuring error message in the mean time? :)

**Comment by carlkesselman** [comment]
Take a look at my recently posted bug report: https://github.com/micro-manager/pycro-manager/issues/682

I’m wondering if I was right to be worried after all……


Carl


On Sep 5, 2023, at 9:40 AM, Carl Kesselman ***@***.***> wrote:

Actually, I’m ok… so this is expected behavior.  I’m fighting another issue and I didn’t want to waste time chasing it down if it was a different problem.

I have been tracking the new API…. I think I could use it.

Carl


On Sep 5, 2023, at 9:03 AM, Henry Pinkard ***@***.***> wrote:



Hahahah. I'm working on a branch that should enable a very useful new API and some cool functionality, which hopefully will be PRed soon and should fix this. Perhaps a more reassuring error message in the mean time? :)

**Comment by henrypinkard** [comment]
Ack! Your intuition was right yet again! I will look into a fix ASAP
