### ISSUE TITLE
Images being processed but not saved

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#682]
### Bug report

The following test case seems to hang after saving 100 out of the 200 images in the acquisition.  All of the images are processed, but onlly 100 are saved.

```python

import os

import pycromanager
from pycromanager import multi_d_acquisition_events, Core, Acquisition
from spimmgr.config import java_loc, mm_app_path

config = r"C:\Program Files\Micro-Manager-2.0\MMConfig_demo.cfg"
pycromanager.start_headless(mm_app_path, config, java_loc=java_loc)

core = Core(debug=False)
print(f"Camera is {core.get_camera_device()}")

iprocess = 1
isaved = 1


def processed(image, metadata):
    global iprocess
    print(f"process image {iprocess}")
    iprocess += 1
    return image, metadata


def saved(_axis, _dataset):
    global isaved
    print(f"saved image {isaved}")
    isaved += 1


try:
    with Acquisition(directory="foo",
                     name="test",
                     image_saved_fn=saved,
                     image_process_fn=processed,
                     debug=False,
                     show_display=False) as mmacquisition:
        print(f"Start acquisition")
        mmacquisition.acquire(multi_d_acquisition_events(num_time_points=200))
    print(f"Acquisition complete")
    for p in pycromanager.acq_util.SUBPROCESSES:
        p.terminate()
except KeyboardInterrupt:
    print("Cores shut down.....")
    os._exit(1)

print("Cores shut down.....")
os._exit(1)
```

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 28.2
  * MicroManager version: 2.0.3 20230827
  * Python version: 3.11
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by carlkesselman** [comment]
Did a little digging.  The number 100 happens to be the size of the notification queue in Acquire class.  Change to 150 and that is where it stalls out.....

**Comment by henrypinkard** [comment]
Hopefully fixed by https://github.com/micro-manager/pycro-manager/pull/685

I'm going to add a test for this now

Btw, I made some improvements to headless mode, so there is a now a `stop_headless()` so you shouldn't have to terminate manually.

**Comment by henrypinkard** [comment]
Great! No not yet. I'm making some examples/tests right now. Curious to hear what you think--changes can certainly be made if you have ideas for improvement.

**Comment by henrypinkard** [comment]
There's also the python backend now: `start_headless(python_backed=True)`. No file saving built in, so you have to use an image processor to divert images if you don't want to fill up RAM. Not sure if this fits your use case or not, but if you try it, let me know how it goes

**Comment by henrypinkard** [comment]
You'll also need the[ latest CI build](https://download.micro-manager.org/ci/2.0/Windows/) to test if you don't want to wait until tomorrows nightly build

**Comment by henrypinkard** [comment]
Added test based on your example: https://github.com/micro-manager/pycro-manager/pull/689

**Comment by carlkesselman** [comment]
So with the Python backend, the image_saved_fn callback will not be called and the acquisition engine will not write the ndtiff?  I like the idea of no Java (I never bothered to learn Java), but would like to make sure that I don’t end up an extra copy operation on the acquisition, which seems to be what happens when you define the callback with the java backend (looks like the java engine sends the image to python for processing by the callback, and then back again)

So assuming I’m still using NDTiff, I would need to open the file and set the image_process_fn to do the write myself (rendering the directory argument useless?).  I assume that I would save the image and then return None in the image argument from the callback?


Does this sound correct?

Carl


----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl















On Sep 7, 2023, at 10:56 AM, Henry Pinkard ***@***.***> wrote:



There's also the python backend now: start_headless(python_backed=True). No file saving built in, so you have to use an image processor to divert images if you don't want to fill up RAM. Not sure if this fits your use case or not, but if you try it, let me know how it goes

**Comment by carlkesselman** [comment]
Ahh, so here’s the rub… There is no way to write NDTiff from Python.  I suppose I can just write the raw images, or write Zarr myself, or even …gasp… use OME-Zarr?


Thoughts?  Perhaps there is a way to spool out of the in memory copy to an on disk version?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl















On Sep 7, 2023, at 1:31 PM, Henry Pinkard ***@***.***> wrote:



So with the Python backend, the image_saved_fn callback will not be called and the acquisition engine will not write the ndtiff?

Right now, the image_saved_fn still gets called (when the image "saves" to RAM)--Im not sure I actually tested it though. No saving to NDTiff, as the writer code for this lives in Java. image_saved_fn and and image processors are pretty similar in python backend, with the difference being that the later allows you to prevent the image from being stored in memory in python (and accessible via a Dataset)

I like the idea of no Java (I never bothered to learn Java), but would like to make sure that I don’t end up an extra copy operation on the acquisition, which seems to be what happens when you define the callback with the java backend (looks like the java engine sends the image to python for processing by the callback, and then back again)

Yes exactly, there is an inefficient copy/serialization that should be avoidable with the python backend.

I made a python engine that is essentially a line-for-line copy of the Java one. So the nice thing about this is if you find bugs/improvements in the python engine, you can PR them and then it will be easy to improve the Java engine simultaneously.

So assuming I’m still using NDTiff, I would need to open the file and set the image_process_fn to do the write myself (rendering the directory argument useless?). I assume that I would save the image and then return None in the image argument from the callback?

Yes, with the python backend you should get an error if you pass directory. If you implement an image processor that returns None then you can save the images yourself. Or if you implement a an image_save_fn, the images will be stored in a Dataset in RAM

**Comment by henrypinkard** [comment]
Correct, there's no NDTiff writing from python. And this doesn't seem likely to be added anytime soon, because better to focus on new file saving in the c++ layer (https://github.com/micro-manager/mmCoreAndDevices/issues/323), which would be faster than NDTiff and available from Java and Python.

As far as I know, Zarr and anything based on it [currently lacks the features](https://github.com/micro-manager/micro-manager/issues/1243#issuecomment-1594932561) to be _really_ fast. But I don't actually know what that the limit of its performance is.

So if you're saving to disk and NDTiff is good enough, probably best to stick with the Java backend. Though the python backend can still be a useful tool to swap in at times for debugging

**Comment by carlkesselman** [comment]
Got it.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl















On Sep 7, 2023, at 2:39 PM, Henry Pinkard ***@***.***> wrote:



Correct, there's no NDTiff writing from python. And this doesn't seem likely to be added anytime soon, because better to focus on new file saving in the c++ layer (micro-manager/mmCoreAndDevices#323<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_mmCoreAndDevices_issues_323&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=ZOm5gpXsNzrmZI8pUufUoW8rzFZ96SbXST3qpG4oPA-P1JAXYEY2OolsaLOIxmlQ&s=DJvVnVEculSZwxkCovMTiPmOYP-THbHRPsVK8HnMBJ8&e=>), which would be faster than NDTiff and available from Java and Python.

As far as I know, Zarr and anything based on it currently lacks the features<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_micro-2Dmanager_issues_1243-23issuecomment-2D1594932561&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=ZOm5gpXsNzrmZI8pUufUoW8rzFZ96SbXST3qpG4oPA-P1JAXYEY2OolsaLOIxmlQ&s=rfkt0xq5fwohJh213bvCYTQS2Ou6BN2AmTa2VlDpqFc&e=> to be really fast. But I don't actually know what that the limit of its performance is.

So if you're saving to disk and NDTiff is good enough, probably best to stick with the Java backend. Though the python backend can still be a useful tool to swap in at times for debugging

**Comment by carlkesselman** [comment]
FYI…. for the first time since I’ve started, I was able to complete a 2 hour, three camera run, with Z-stack from the SPIM (hamamatsu camera) and two other observational cameras at 40FPS (Basler).  This includes setting ROI and controlling all aspects from my python control program.

 Success!!

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl















On Sep 7, 2023, at 3:16 PM, Carl Kesselman ***@***.***> wrote:

Got it.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl















On Sep 7, 2023, at 2:39 PM, Henry Pinkard ***@***.***> wrote:



Correct, there's no NDTiff writing from python. And this doesn't seem likely to be added anytime soon, because better to focus on new file saving in the c++ layer (micro-manager/mmCoreAndDevices#323<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_mmCoreAndDevices_issues_323&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=ZOm5gpXsNzrmZI8pUufUoW8rzFZ96SbXST3qpG4oPA-P1JAXYEY2OolsaLOIxmlQ&s=DJvVnVEculSZwxkCovMTiPmOYP-THbHRPsVK8HnMBJ8&e=>), which would be faster than NDTiff and available from Java and Python.

As far as I know, Zarr and anything based on it currently lacks the features<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_micro-2Dmanager_issues_1243-23issuecomment-2D1594932561&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=ZOm5gpXsNzrmZI8pUufUoW8rzFZ96SbXST3qpG4oPA-P1JAXYEY2OolsaLOIxmlQ&s=rfkt0xq5fwohJh213bvCYTQS2Ou6BN2AmTa2VlDpqFc&e=> to be really fast. But I don't actually know what that the limit of its performance is.

So if you're saving to disk and NDTiff is good enough, probably best to stick with the Java backend. Though the python backend can still be a useful tool to swap in at times for debugging

**Comment by henrypinkard** [comment]
Awesome!! Thanks for all your testing, suggestions, and PRs--they've really made pycromanager a lot better for everyone
