### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [micro-manager/pycro-manager#695]
Hi team!

While working on https://github.com/conda-forge/pycromanager-feedstock/pull/33, we found that 

- sortedcontainers is Imported but not declared in requirements

Could this be validated and fixed for the next release?

 Cheers 🚀 !

**Comment by henrypinkard** [comment]
I believe this is because the sortedcontainers is a dependency of nditff, which is a dependency of pycromanager?

**Comment by goanpeca** [comment]
If there is a direct import in your package, then this means that your package directly depends on that library and should be listed as a requirement, even if it is already indirectly provided by another dependency.
