### ISSUE TITLE
Save single image snap as NDTiff

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#697]
Greetings,

I'm continuing my experiments with Pycro-Manager and for consistency reason I'm trying to store a single snapped image into an NDTiff file. I know that the `ndtiff` package is available but this seems to be only capable of reading and NDTiff stack. Would it be possible to also write a stack? Similarly to what is available with the `tifffile` package (I checked it as well but apparently tifffile only supports reading NDTiff stacks)

**Comment by henrypinkard** [comment]
Do you mean you're trying to write a single image in each tiff file? The `ndtiff` python package is only a reader. The only writer that yet exists for NDTiff is written in Java. So you need to use the java backend to pycro-manager if you want to make use of it.

And then on top of that, are you saying you want to save just one image per file? NDTiff is designed to put many images in the same file for performance reasons. Though you could do this if you ran multiple `Acquisition`s that each acquired one image
