### ISSUE TITLE
Interrupting acquisition while running

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#713]
Greetings,

I'm currently progressing in integrating pycromanager as a backend into [ImSwitch](https://github.com/ImSwitch/ImSwitch/tree/pymmcore-llm). Currently ImSwitch allows a user to toggle a recording on/off in case the application gets stuck due to some issues like memory or an unresponding device. I would like to know if it is possible to abort a running acquisition using one of the notifications available in the pycromanager framework, or if it's doable at all.

Thanks!

**Comment by henrypinkard** [comment]
You should be able to call `acquisition.abort()`
