### ISSUE TITLE
After first acquired dataset, PycroManager acquisition is stuck (headless mode)

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#717]
I'm currently running PycroManager on a separate thread which is called from the user interface. I'm using the `Acquisition` API as context manager. After acquiring a first dataset, the command line reports the following:

```
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Users\\jacop\\OneDrive\\Documenti\\ImSwitchConfig\\recordings\\2023-10-09\\17h54m29s_rec_1\\17h54m29s_rec_NDTiffStack.tif'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

I tried using `tracemalloc` to dump some statistics but I could not figure out much from those, so I don't have much of a traceback to show. From the Python side of PycroManager I'm noticing that there is a refence to the collected dataset; could it be that for some reason it is not released properly whenever I trigger a new acquisition?

EDIT: forgot to specify that I'm running PycroManager in headless mode.

**Comment by henrypinkard** [comment]
> could it be that for some reason it is not released properly whenever I trigger a new acquisition?

Yes, but I don't think it should be released because you'd still like to be able to call `acq.get_dataset` after the acquisition is finished. I tried to reproduce this based on your description, but I don't see anything similar. Can you make a minimal way to reproduce this with the demo config? Here was my attempt:

```python
from pycromanager import Acquisition, multi_d_acquisition_events, start_headless
import threading

mm_app_path = r'C:\Users\henry\Micro-Manager-nightly'
config_file = mm_app_path + "/MMConfig_demo.cfg"
start_headless(mm_app_path, config_file)

save_dir = r"C:\Users\henry\Desktop\data"


def run_acq():
    with Acquisition(directory=save_dir, name="tcz_acq", show_display=False) as acq:
        # Generate the events for a single z-stack
        events = multi_d_acquisition_events(num_time_points=5)
        acq.acquire(events)

    with Acquisition(directory=save_dir, name="tcz_acq", show_display=False) as acq:
        # Generate the events for a single z-stack
        events = multi_d_acquisition_events(num_time_points=5)
        acq.acquire(events)

# run on a different thread
thread = threading.Thread(target=run_acq)
thread.start()

thread.join()
```

**Comment by jacopoabramo** [comment]
Just tested myself. This works. I also tested with a version using QThread and works as well. I think that this has to do with some internals of ImSwitch that do not release properly the data after acquiring. Closing.
