### ISSUE TITLE
Multi-D Acquisition window freezes when changing window size

### ISSUE THREAD

**Issue by caichangjia** [micro-manager/pycro-manager#723]
Hi, I am using micromanager2.0 for Andor Zyla 5.5 camera on a Win 10 machine. I could run the following lines to capture a multi-D stack with full FOV size. However, when I switched to a smaller window size, the acquisition window will freeze and no output (see attached image).  
If I capture with Multi-D Acquisition GUI (instead of code) and the issue is not there.
Let me know if I missed anything, thank you!

```
core = Core()
TriggerMode = ['External', 'Internal (Recommended for fast acquisitions)'][1]
AcquisitionWindow = ['Full Image', '1024x1024', ' 512x512', ' 128x128'][3]
ElectronicShutteringMode = ['Global', 'Rolling'][0]
Overlap = ['On', 'Off'][0]
Exposure = 1.5

properties = {'TriggerMode': TriggerMode, 'AcquisitionWindow': AcquisitionWindow, 
              'ElectronicShutteringMode': ElectronicShutteringMode, 'Exposure': Exposure, 
              'Overlap': Overlap}#, 'FrameRate': FrameRate}
for key, value in properties.items():
    core.set_property('Andor sCMOS Camera', key, value)

save_name = r'acquisition_small_movie'
with Acquisition(directory=save_dir, name=save_name, ) as acq:
    events = multi_d_acquisition_events(num_time_points=400, time_interval_s=0)
    acq.acquire(events)
```
![image](https://github.com/micro-manager/micro-manager/assets/30387087/11e62824-57a1-43bf-bf30-fe6aba6a590a)

**Comment by henrypinkard** [comment]
I think you should try updating to the latest nightly build/pycromanager. This may be the same issue as https://github.com/micro-manager/pycro-manager/issues/620

**Comment by caichangjia** [comment]
Thank you. It is the same problem. My problem generally gets solved after updating to latest nightly build and pycromanager. 
However, there is still some small bug. After changing the size of the FOV (from 128x128 to full image) and use the multi-D acquisition using command line, the images are captured, but the gui still stuck there (same issue not happens when I use a small FOV like 128x128).  
![image](https://github.com/micro-manager/pycro-manager/assets/30387087/9787026a-3e6b-49bd-bd2f-9e2a21aa6e05)

**Comment by henrypinkard** [comment]
Hmm I'm not sure. Are you able to reproduce this with the demo configuration? (I know you originally filed this issue on the main Micro-Manager repo, so it may be worth taking a look at the instructions for filing a good bug report on pycro-manager).

I'd be happy to take look into this more after you've gone through the procedure there, but I also need more information about the conditions for reproducing:
- Does it happen with the demo camera?
- What is the bit depth of pixels?
- what image sizes does it work for and which ones does it not?
- Which versions of pycro-manager, micro-manager, and which OS are you using?
