### ISSUE TITLE
Provide working examples as templates for pycro-manager applications

### ISSUE THREAD

**Issue by ischoegl** [micro-manager/pycro-manager#73]
MicroManager provides a [DemoCamera Configuration](https://micro-manager.org/w/images/9/9f/MMConfig_Demo.cfg) which allows testing of a virtual camera.

At the moment, most examples in the `test` folder use a system-specific path (`directory='/Users/henrypinkard/megllandump'`), and it is not clear how to make them work. Attempts to create working acquisition events failed (e.g. last comment in #66)

**Comment by henrypinkard** [comment]
Yes, right now `test` is more of my personal testing repo than a proper set of examples. PRs welcome if you'd like to improve this!

**Comment by ischoegl** [comment]
Updating the paths should be straightforward once I can advance past the exception in #66
