### ISSUE TITLE
core.snap_image() works once and then crashes

### ISSUE THREAD

**Issue by mdanderson03** [micro-manager/pycro-manager#735]
I have used pycromanager for years and never had this issue. I was running it earlier today and it was working well and then nothing changed and it wouldnt work anymore. The issue I am having is when micromanager is first loaded up, I can use MM core to snap and image one time. If I ask it again in the same script or rerun the script, it crashes. I have MM and pycromanager up to date. I have an IRIS 15 camera with up to date driver. I have restarted software and hardware and it still does it.

![core_snap_error](https://github.com/micro-manager/pycro-manager/assets/48689483/9fb87c9e-22e5-48eb-bc00-30e9c81c42da)

<img width="1454" alt="snap_error" src="https://github.com/micro-manager/pycro-manager/assets/48689483/a7ceea27-38a4-4dd9-af35-e410d783f7b3">

**Code for reproduction**
```python
# your code here
from pycromanager import Core

core = Core()
core.snap_image()



**Expected outcome**
Take a snap shot

**Actual outcome**
First try takes a snap shot. Will never take another one if rerun

**Comment by mdanderson03** [comment]
I did try with demo config and couldnt replicate this. Its quite possible that its a micromanager issue.

**Comment by henrypinkard** [comment]
Yeah this is almost certainly a bug with the device adapter and unrelated to pycro-manager. You should open an issue on MMCoreAndDevices
