### ISSUE TITLE
pycromanager on wsl2 with micromanager 2.0 on windows 10

### ISSUE THREAD

**Issue by svikolev** [micro-manager/pycro-manager#738]
Just wondering if its possible to use pycromanager running on linux kernel with wsl2 while micromanger runs on windows 10?
I would like to use tensorflow 2.15 (so that I can use keras_cv package which requires tf 2.11 or higher) with gpu support and this is only possible on windows 10 with WLS2 because native windows has gpu support on tf 2.10 or lower.

**Comment by jacopoabramo** [comment]
After thinking about it for a moment, I would make the point that since Micro-Manager exposes a server one could connect to it - and with WSL2 you can still inspect Windows paths so it should be doable.

I'll give it a try.

**Comment by henrypinkard** [comment]
I think this actually should work. You'd need to as you say run MM on the windows machine, then only run pycromanager on WSL. The key is that you'll need to forward ports from the windows machine to the linux machine (at least port 4827 for basic control of the core, additional ones depending on what features you're using). 

I don't know exactly how to do this port forwarding, but it [seems like its possible](https://stackoverflow.com/questions/64513964/wsl-2-which-ports-are-automatically-forwarded)
