### ISSUE TITLE
Magellan class does not initialize

### ISSUE THREAD

**Issue by mdanderson03** [micro-manager/pycro-manager#739]
I have been unable to initialize the Magellan class from pycromanager with recent versions of micromanager. Not certain on when it changed, but some time between 9-29-2023 and 10-30-2023. In the screen shots below, I have pycromanager version 0.29.9 and am running various versions of micromanager in demo configuration. 

**9-29-2023 micromanager version**

![image](https://github.com/micro-manager/pycro-manager/assets/48689483/c5fd9ff6-4a9a-400a-9153-220f819aa50a)

**10-30-2023 micromanager version**

![image](https://github.com/micro-manager/pycro-manager/assets/48689483/11b3a846-e89a-4023-a6ef-8fd322a22855)

**2-06-2024 micromanager version**

![image](https://github.com/micro-manager/pycro-manager/assets/48689483/a2371e7d-410d-49e6-9435-f86020e02dee)

**Comment by JonesLab-TAMU** [comment]
Any update on this?  We're getting the same issue.

**Comment by henrypinkard** [comment]
@nicost it appears you may have changed the API in https://github.com/micro-manager/micro-manager/pull/1832, which has broken Magellan access through pycro-manager

Could you look into this? Or if you don't have time and aren't using the changes you made, perhaps revert that PR?

**Comment by nicost** [comment]
Do you have the studio object available in Pycromanager?  If so, can you call 

`magellan - Magellan(studio)`

?

**Comment by henrypinkard** [comment]
@nicost, I appreciate your quick response. I attempted the following approach:

```python
from pycromanager import Magellan, Studio

s = Studio()
magellan = Magellan(s)
```

but unfortunately, it didn't resolve the issue. I don't understand why--it may be related to the inheritance structure of the Studio and limitations of the Java python bridge.

While I understand the changes in micro-manager/micro-manager#1832 were necessary, they've resulted in a breaking API change that currently leaves Magellan unusable from Python. Considering your previous focus on avoiding such disruptions, I'm hopeful you see the need for a resolution. I lack both a comprehensive understanding of the alterations made in that PR and the equipment to conduct proper testing. Could you please investigate a solution?

**Comment by nicost** [comment]
I'll dive into this, but it may take some time.  First thought is to take
studio out of the constructor, create a function that adds it in, then test
everywhere it is used to make sure that it is not null.

**Comment by nicost** [comment]
and sorry about the disruption, I clearly had forgotten about the use of
Micro-Magellan outside of the MMStudio eco-system.

**Comment by henrypinkard** [comment]
No worries, thanks!

**Comment by henrypinkard** [comment]
should be fixed in https://github.com/micro-manager/micro-manager/pull/1914

**Comment by jrtage** [comment]
I'm running the 20240426 nightly build downloaded from the website and I am getting this error. did the issue return since fixing it?

**Comment by henrypinkard** [comment]
This would be surprising. I suspect you may have an old version of a library hanging around. Can you try deleting your MM installation and performing a fresh new install of latest version?
