### ISSUE TITLE
Allow for multiple acquisitions within a Python session

### ISSUE THREAD

**Issue by ischoegl** [micro-manager/pycro-manager#75]
With the current implementation, acquisitions require a `__main__` module to spawn a task in `multiprocessing`. While it is possible to launch acquisition scripts from within a Python environment (e.g. IPython), only the first acquisition is successful; subsequent attempts raise an exception, e.g. running an acquisition script `pycrotest.py` results in
```
In [1]: %run pycrotest.py # this is successful

In [2]: %run pycrotest.py # this fails
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\GitLab\umanager\examples\pycrotest.py in <module>
      6     #cwd = Path.cwd()
      7     exposures = np.linspace(100, 1000, 10)
----> 8     with pm.Acquisition(directory='.', name='pycrotest') as acq:
      9         events = []
     10         for idx, exposure in enumerate(exposures):

~\miniconda3\envs\crio\lib\site-packages\pycromanager\acquire.py in __init__(self, directory, name, image_process_fn, pre_hardware_hook_fn, post_hardware_hook_fn, post_camera_hook_fn, show_display, tile_overlap, magellan_acq_index, process, debug)
    227                                                          name='Event sending')
    228                     # if multiprocessing else threading.Thread(target=event_sending_fn, args=(), name='Event sending')
--> 229             self.event_process.start()
    230
    231

~\miniconda3\envs\crio\lib\multiprocessing\process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

~\miniconda3\envs\crio\lib\multiprocessing\context.py in _Popen(process_obj)
    222     @staticmethod
    223     def _Popen(process_obj):
--> 224         return _default_context.get_context().Process._Popen(process_obj)
    225
    226 class DefaultContext(BaseContext):

~\miniconda3\envs\crio\lib\multiprocessing\context.py in _Popen(process_obj)
    324         def _Popen(process_obj):
    325             from .popen_spawn_win32 import Popen
--> 326             return Popen(process_obj)
    327
    328     class SpawnContext(BaseContext):

~\miniconda3\envs\crio\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     43
     44     def __init__(self, process_obj):
---> 45         prep_data = spawn.get_preparation_data(process_obj._name)
     46
     47         # read end of pipe will be duplicated by the child process

~\miniconda3\envs\crio\lib\multiprocessing\spawn.py in get_preparation_data(name)
    181     # or through direct execution (or to leave it alone entirely)
    182     main_module = sys.modules['__main__']
--> 183     main_mod_name = getattr(main_module.__spec__, "name", None)
    184     if main_mod_name is not None:
    185         d['init_main_from_name'] = main_mod_name

AttributeError: module '__main__' has no attribute '__spec__'
```
As an aside, it would be great if pycro-manager could support acquisition tasks defined within functions or objects instead of having everything tied to `__main__`.

**Comment by henrypinkard** [comment]
I think this is more a python problem with `multiprocessing` than a pycro-manager problem. See discussion [here](https://github.com/micro-manager/pycro-manager/issues/42). Python is not a "true" multithreaded language. Hence the use of `multiprocessing`. But `multiprocessing` has OS-dependent behavior. Hence to need for the main guard (on windows). I agree this is unfortunate, but doesn't seem to be a way to get around it while still supporting true parallelism for the features required of `Acqusition`s. 

In any case, why don't you just run your script from the command line rather than iPython?

**Comment by ischoegl** [comment]
@henrypinkard ... multiprocessing is indeed a little complicated in Python. While you’re correct that the issue won’t arise from the command line, this is unfortunately not an option for our application. We are running an automated data acquisition script from Python, where pycromanager would be used for periodic image acquisition (I.e. an individual task within a series of measurements). Everything else is using multiprocessing also, and we generally haven’t found it necessary to rely on dedicated bindings to `__main__`.

**Comment by henrypinkard** [comment]
It depends on what you're doing with multiprocessing (see https://stackoverflow.com/questions/20360686/compulsory-usage-of-if-name-main-in-windows-while-using-multiprocessi).

Why don't you just [run a shell command through python](https://janakiev.com/blog/python-shell-commands/)

**Comment by ischoegl** [comment]
Now that I know more about the resulting custom TIFF file format (which isn't fully supported natively by other TIFF file readers, i.e. information on axes is lost and metadata aren't accessible from ImageJ), the issue is moot.
