### ISSUE TITLE
`acquire` does not accept generators; RAM dataset not recoverable

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#750]
Single issue for two different bugs.

I tested the recent update of pycromanager, 0.30.3, with the code snippet you provided in this [`PR`](https://github.com/ImSwitch/ImSwitch/pull/177#issuecomment-2044148231). I slightly modified it by starting the engine in headless mode.

```python
from pycromanager import Acquisition, start_headless
import threading
import numpy as np
import time

mm_app_path = r"C:/Program Files/Micro-Manager-2.0"
config_file = mm_app_path + "/MMConfig_demo.cfg"

start_headless(mm_app_path, config_file)

stop_event = threading.Event()
current_image = None

def run_live_stream(delay_time=1/120):
    global current_image

    def event_generator():
        while True:
            # keep generating images with the same key ({'time': '0'})
            # so only one is stored and RAM doesn't fill up
            yield {'axes': {'time': '0'}, 'exposure': np.random.rand() * 30}
            time.sleep(0.0001) # This is important so the generator thread doesn't block others

    # events = multi_d_acquisition_events(num_time_points=10)

    generator_object = event_generator()

    with Acquisition(debug=False, name=None, show_display=False) as acq:
        got_image_time = 0
        future = acq.acquire(generator_object)
        while not stop_event.is_set():
            time.sleep(max(0, got_image_time + delay_time - time.time()))
            image = future.await_image_saved(return_image=True, return_metadata=False)
            got_image_time = time.time()
            current_image = image
        acq.abort()
    print('done with live stream')

# start live stream
first_live_thread = threading.Thread(target=run_live_stream, name="Pycro-Manager live thread")
first_live_thread.start()

while current_image is None:
    time.sleep(.1) # wait for first image to be grabbed

for i in range(10):
    # simulate grabbing image for live display
    time.sleep(.1)
    print(current_image.mean())

print('stop signal')
stop_event.set() # send stop signal
first_live_thread.join() # wait for thread to finish


print('start again')
# start live stream
stop_event.clear()
second_live_thread = threading.Thread(target=run_live_stream)
second_live_thread.start()

for i in range(10):
    # simulate grabbing image for live display
    time.sleep(.1)
    print(current_image.mean())

print('stop signal')
stop_event.set() # send stop signal
second_live_thread.join()
```

**Expected outcome using generator**

The acquisition runs fine.

**Actual outcome using generator**

I get the following stack trace:

```
Exception in thread Pycro-Manager live thread:
Traceback (most recent call last):
  File "C:\Users\jacop\miniforge3\envs\pycromanager-sandbox\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\jacop\miniforge3\envs\pycromanager-sandbox\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\sandbox\python\pycromanager_sandbox.py", line 31, in run_live_stream
    future = acq.acquire(generator_object)
  File "C:\Users\jacop\miniforge3\envs\pycromanager-sandbox\lib\site-packages\pycromanager\acquisition\acquisition_superclass.py", line 210, in acquire
    _validate_acq_events(event_or_events)
  File "C:\Users\jacop\miniforge3\envs\pycromanager-sandbox\lib\site-packages\pycromanager\acquisition\acquisition_superclass.py", line 297, in _validate_acq_events
    raise Exception('events must be a dictionary or a list of dictionaries')
Exception: events must be a dictionary or a list of dictionaries
```

**Expected outcome using `multi_d_acquisition_events`**

Acquisition runs fine.

**Actual outcome using `multi_d_acquisition_events`**

```
Traceback (most recent call last):
  File "C:\Users\jacop\miniforge3\envs\pycromanager-sandbox\lib\site-packages\pycromanager\acquisition\java_backend_acquisitions.py", line 199, in _notification_handler_fn
    axes = acquisition._dataset._add_index_entry(index_entry)
AttributeError: 'NoneType' object has no attribute '_add_index_entry'
```

The first bug is due to `validate_acq_events` not having a branch condition for generators. I suspect that this propagates in ways I cannot predict further down in the code.

The second bug is related to what I already mentioned in the PR.

Note that currently I'm using a `mamba` environment with Python 3.11 but I don't think this could cause problems... right?

**Comment by henrypinkard** [comment]
Looks like the new version didnt build due to a version number typo https://github.com/micro-manager/pycro-manager/actions/runs/8610355239

I fixed that, and new version (0.31.0) is going up now. Make sure you pip install -- the conda versions can be slow to update. You'll also need the latest build. You can get the continuous integration developer versions (which go up sooner than nightly builds) here: https://download.micro-manager.org/ci/2.0/Windows/

**Comment by jacopoabramo** [comment]
@henrypinkard the workflow shows that the publication on PyPi was skipped

**Comment by henrypinkard** [comment]
Good catch, I just bumped it https://github.com/micro-manager/pycro-manager/pull/752

**Comment by jacopoabramo** [comment]
So I tested the snippet and with the generator works fine.

But! When I use multi_d_acquisition_events to generate the events, the script blocks when attempting to join the live thread. Are you noticing this on your end as well? I'm guessing that for this script using the multi_d_acquisition it's not the correct way to tackle the problem

**Comment by henrypinkard** [comment]
How many events? I would suspect perhaps that `image = future.await_image_saved(return_image=True, return_metadata=False)` waits forever because all the images have already arrived by the time that gets called. If you make way more events with `multi_d_acquisition_events` does it work?

**Comment by jacopoabramo** [comment]
Confirmed: I initially tested with 10 time points and it blocked; with 100 time points it proceeds correctly. I tested the generator combined with `multi_d_acquisition` and works. I get an exception because the `post_exposure` notification is not currently handled in the code and it is considered unrecognized but I don't categorize it as a bug so all good.

**Comment by henrypinkard** [comment]
Awesome! Yeah so long as you stick to infinite generators of events you should be fine. Also, very minor, btput I just fixed a bug so that you don't have to have the `'time': 0` anymore, you can instead just do:

```python
 def event_generator():
        while True:
            yield {'axes': {}, 'exposure': np.random.rand() * 30}
            time.sleep(0.0001) # This is important so the generator thread doesn't block others
```
 
> EDIT: actually I saw you recently pushed version 0.31.2 which removed the post_exposure notification entirely; you might want to check it out

Yes, I'm going through the notification API now and trying to finalize it. I removed `post_exposure` because it wasnt quite correct. When running snaps, you can a notification after exposure (which I renamed `post_snap`), but for sequences, there's no way through the API to know when individual frames have finished exposing, so now you only get a `post_sequence_stopped` notification
