### ISSUE TITLE
µManager NDtiff viewer bug when using pycro-manager

### ISSUE THREAD

**Issue by Oftatkofta** [micro-manager/pycro-manager#767]
This issue was originally posted as a question on [image.sc](https://forum.image.sc/t/ndtiff-viewer-error-in-manager/96436).

**Code for reproduction**
```python
filename_1 = 'Democam_16bit_1ch_1079x1079_frame' #works as expected
filename_2 = 'Democam_16bit_1ch_1080x1080_frame' #freezes the NDtiff viewer

with Acquisition(directory=outpath, name=filename, debug=True) as acq:
    events = multi_d_acquisition_events(
                                    num_time_points=3, time_interval_s=4,
                                    channel_group='Channel', channels=['DIC'], channel_exposures_ms= [10],
                                    order='tc'
                                    )
    acq.acquire(events)

```

**Expected outcome**

An updating NDtiff viewer to follow the progress of the acquisition in µManager.

**Actual outcome**

The NDtiff viewer breaks between frame sizes of 1079x1079 and 1080x1080 for both 8 and 16 bit images for 1 channel time lapse series. For 2 channel time lapse series it breaks between 1062x1062 and 1064x1064. This behavior is identical when using both the DemoCamera and cropped subframes from real (Hamamatsu) camera. Upon inspection of the files and directory written to disk, the error occurs as the output folder begins containing the 'Downsampled_x2' subfolder.

[Democam_16bit_1ch_1079x1079_frame_1.zip <- works](https://github.com/micro-manager/pycro-manager/files/15497196/Democam_16bit_1ch_1079x1079_frame_1.zip)

[Democam_16bit_1ch_1080x1080_frame_1.zip <- does not work](https://github.com/micro-manager/pycro-manager/files/15497198/Democam_16bit_1ch_1080x1080_frame_1.zip)

**Comment by henrypinkard** [comment]
Thanks for the very helpful report and all the detailed testing. I think I tracked this down to a bug in the NDTiff library that was allowing for multi-resolution data when it shouldn't have been https://github.com/micro-manager/NDTiffStorage/pull/143. Hence, the larger size triggered this, and the viewer was looking for a downsampled version of the image that didn't actually exist. I think this is fixed, once that PR goes through a propagates to the new nightly builds of MM
