### ISSUE TITLE
Read multi-resolution tiles during acquisition

### ISSUE THREAD

**Issue by oeway** [micro-manager/pycro-manager#78]
I am following the [xy_tilling example](https://github.com/micro-manager/pycro-manager/blob/master/test/xy_tiling.py), however, it's not clear to me how can I get the image tiles during acquisition for real-time display.

Ideally, I would like to initiate an acquisition with `tile size`, `tile_overlap`, but also `levels` to specify how many resolution to be generated. Right after I call `acq.acquire({'row': i, 'col': j})` I would like to access to all the resolution levels for `{'row': i, 'col': j}`. Is this what you would do?

**Comment by henrypinkard** [comment]
Added the ability to do this, which should be available in nightly build after [this](https://github.com/micro-manager/micro-manager/pull/912) merges. There's now a `max_multi_res_index` argument for `Acquisition`. 0 is no pyramid, 1 is 2x downsampled, 2 is 4x etc.

That sounds reasonable. Though there might be some latency in pulling them all through the Java bridge at once. Might make sense to load them one at a time as needed (unless this introduces zooming latency on your end)

**Comment by oeway** [comment]
> Added the ability to do this, which should be available in nightly build after [this](https://github.com/micro-manager/micro-manager/pull/912) merges. There's now a `max_multi_res_index` argument for `Acquisition`. 0 is no pyramid, 1 is 2x downsampled, 2 is 4x etc.

Great Thanks!

> That sounds reasonable. Though there might be some latency in pulling them all through the Java bridge at once. Might make sense to load them one at a time as needed (unless this introduces zooming latency on your end)

I won't need to pull them all at once, just need to make them available.

**Comment by henrypinkard** [comment]
So will `dataset.read_image(row=0, col=0, resolution_level=1)` be sufficient? Or is there something I'm missing?

**Comment by oeway** [comment]
> So will `dataset.read_image(row=0, col=0, resolution_level=1)` be sufficient? Or is there something I'm missing?

I mean, I won't pull all resolutions levels at once, but I do need to be able to access different resolution levels. So no, I need to also access `resolution_level=2, 3, 4...` after calling acq.acquire. The exact resolution level will depend on which zoom level is the user looking at.

**Comment by henrypinkard** [comment]
I think this [updated xy tiling example](https://github.com/micro-manager/pycro-manager/blob/master/test/xy_tiling.py) should allow you to do what you're trying to do

**Comment by henrypinkard** [comment]
You'll also need to update to latest pycromanager and tomorrows micro-manager nighlty build (or replace Pycromanager-java, NDViewer, and NDTiffStorage from [here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/))

**Comment by oeway** [comment]
Ok, thanks!

How do I access different resolution level then?

**Comment by henrypinkard** [comment]
For other resolutions, you'd still need to use:

```
dataset = acq.get_dataset()
dataset.has_image(row=0, col=0, resolution_level=1)
dataset.read_image(row=0, col=0, resolution_level=1)
```

Which is maybe not ideal, but it wouldn't be so easy to change since the multi-resolution parts are embedded into the [file saving format library](https://github.com/micro-manager/NDTiffStorage). Maybe it would make sense to just downsample on-the-fly on the python side, and use this to update your Zarr array?

**Comment by henrypinkard** [comment]
I'm guessing this is more or less resolved now so I'm closing, but feel free to reopen if some else arises
