### ISSUE TITLE
Exception: Socket timed out after 1000 milliseconds

### ISSUE THREAD

**Issue by alex997-phy** [micro-manager/pycro-manager#781]
We install the pycromanager packgae version '0.34.4', micromanager 2.0.1 20220720 and turn on the microscope with CCD ORCA flash 4.0, but we have the following error when test:

from pycromanager import Core
core = Core()
print(core)

Below is the output:
Exception in thread BridgeSocketThread_port4827:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyjavaz/bridge.py", line 340, in _run_socket_thread
    raise Exception(f"Socket timed out after {self._timeout} milliseconds")
Exception: Socket timed out after 1000 milliseconds

**Comment by henrypinkard** [comment]
try increasing the timeout? `core = Core(timeout=5000)`

**Comment by henrypinkard** [comment]
And did you start the server in the options dialog?

**Comment by alex997-phy** [comment]
Problem solved. I used the Ubuntu subsystem in Windows. I think that is the problem. After I used python directly installed on windows, it worked.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Henry Pinkard ***@***.***>
发送时间: Tuesday, June 25, 2024 12:22:19 AM
收件人: micro-manager/pycro-manager ***@***.***>
抄送: alex997-phy ***@***.***>; Author ***@***.***>
主题: Re: [micro-manager/pycro-manager] Exception: Socket timed out after 1000 milliseconds (Issue #781)


And did you start the server in the options dialog?

―
