### ISSUE TITLE
Execution Blocked if Socket times out or unavailable. (Core) 

### ISSUE THREAD

**Issue by samhitech** [micro-manager/pycro-manager#786]
Hi, I'm uncertain whether this was done on purpose or if it's a bug. If a timeout occurs or if micromanager isn't running, the entire code freezes and the exception cannot be handled.

**Code for reproduction**
```python
from pycromanager import Core

try:
    core = Core()
except Exception as e:
    print(e)

# do anything afterward
print('here')
```

**Expected outcome**

> printed 'error message'
> printed 'here'

where further execution is not blocked

**Actual outcome**

> Exception in thread BridgeSocketThread_port4827:
Traceback (most recent call last):
  File "C:\Users\Nour\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Nour\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nour\AppData\Local\Programs\Python\Python39\lib\site-packages\pyjavaz\bridge.py", line 341, in _run_socket_thread
    raise Exception(f"Socket timed out after {self._timeout} milliseconds")
Exception: Socket timed out after 1000 milliseconds
*(Here execution freezes)*

**Comment by henrypinkard** [comment]
Should be fixed in 
https://github.com/micro-manager/pycro-manager/pull/787

**Comment by henrypinkard** [comment]
I think now fixed
https://github.com/micro-manager/pycro-manager/pull/788
