### ISSUE TITLE
Save data according to ome-tiff standard

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#83]
It would be nice if pycromanager data can be saved according to the OME-TIFF standard. This way data can easily be loaded using `tifffile` or the Fiji BioFormats reader. Currently, these readers load data from only one file if multi-file tif stack is saved. Further, the data is imported as 3D stack, and not shaped properly.

If implemented, one would need to figure out how to handle custom `pycromanager` axes.

**Comment by henrypinkard** [comment]
Unfortunately, the OME-TIFF standard is not flexible enough to allow for the various types acquisitions supported by pycro-manager (at least last I checked). For this reason, the [`Dataset`](https://pycro-manager.readthedocs.io/en/latest/read_data.html) API is the reccomended way to read pycromanager data
