### ISSUE TITLE
Feature: Load pycromanager data in micro-manager

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#84]
It would be nice to be able to load `pycromanager` data with standard dimensions (`STCZYX` where `S` is scene or position) in micro-manager.

**Comment by henrypinkard** [comment]
It's a good idea. Shouldn't be so hard to implement

**Comment by henrypinkard** [comment]
Update: you can now open pycro-manager datasets through the Magellan GUI (in upcoming version)

**Comment by henrypinkard** [comment]
I might add a `Viewer` object in pycromanager to do this through python code

**Comment by ieivanov** [comment]
Ah, very nice! Do you know if you can open pycromanager `Dataset` objects in `napari`? That could be a nice feature that may not be hard to implement. If that works, a useful next step would be viewing the image metadata through `napari` in some way, I'm not sure if they're already working on something along these lines

**Comment by henrypinkard** [comment]
You mean something different than [this](https://github.com/micro-manager/pycro-manager/blob/master/test/read_data.py)? (for pixels, that example doesn't do metadata)

**Comment by ieivanov** [comment]
That's exactly what I was referring to, thanks!

**Comment by henrypinkard** [comment]
This should work now

**Comment by ieivanov** [comment]
I have it a try, but it didn't work for me. I tried both drag-and-drop of the acquisition folder, and also File>Open (RAM). Was this your intended use mode?
