### ISSUE TITLE
Garbled images in image processor functions using non-square images

### ISSUE THREAD

**Issue by davidfange** [micro-manager/pycro-manager#86]
Hi,

we had problems running pycromanager acquisitions together with an image processor on non-square images. Images in the image processor function are garbled and have swapped height and width. Modifications made to images in the processor functions are also garbled. 

Swapping the order of Height and Width on line 93 of acquire.py produces images that look correct in the image processor function and in micro-manager.

/david

**Comment by henrypinkard** [comment]
Nice catch. Want to make a pull request to merge in the fix? Or I can if you don't want to

**Comment by davidfange** [comment]
Would be perfect if you could do it :-)

**Comment by henrypinkard** [comment]
Done

https://github.com/micro-manager/pycro-manager/pull/87
