### ISSUE TITLE
Feature: Add keep_shutter_open option

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#88]
It would be nice to add a `keep_shutter_open` option which will keep the shutter open when acquiring data along any given axis (time, channel, z, custom, etc.). Currently the shutter is closed after every slice of a z stack.

**Comment by henrypinkard** [comment]
For non hardware-sequenced acquisitions, I assume?

**Comment by ieivanov** [comment]
Correct

**Comment by henrypinkard** [comment]
See if this does what you'd expect on your system: https://github.com/micro-manager/pycro-manager/commit/2d74e4e9da7dc7e2ebfe69c938d3e19cd5896a5b

Should be available after https://github.com/micro-manager/micro-manager/pull/942

If it works I'll add it to acquisition event specification in the docs

**Comment by henrypinkard** [comment]
Added to api

**Comment by ieivanov** [comment]
I finally got around to testing the `keep_shutter_open` option. Here are a few observations:

- Passing `keep_shutter_open=True` does keep the shutter open, as intended

- You can pass `keep_shutter_open` argument in both the `events` list and the `acquire` function. Isn't this redundant? My understanding is that calling `acquire(events, keep_shutter_open=True)` will keep the shutter open during the entire acquisition (regardless of keys in `events`?). This could be accomplished by adding `keep_shutter_open` key to all events in the dictionary at construction

- Right now there is no easy way to construct events for multichannel acquisition where the shutter is kept open between z slices, but closed between channels. `multi_d_acquisition_events` does not currently take a `keep_shutter_open` argument. You may consider adding `keep_shutter_open_between_slices` and `keep_shutter_open_between_channels` as in the micro-manager MDA window

- The way I acquired data as described above was:
```
z_stage = mmc.get_focus_device()
mmc.set_property(z_stage,'UseSequence','Yes')

events = []
for ch in channels:
    for idx, z_um in enumerate(np.arange(start=0, stop=10, step=0.25)):
        events.append({'axes': {'z': idx},
                       'z': z_um,
                       'channel': {'group': 'Cube', 'config': ch},
                       'keep_shutter_open': True})
    events.append({'keep_shutter_open': False})
```
The shutter behaved as expected. However, the microscope did not run a sequenced acquisition. Running a single z-stack as `acq.acquire(multi_d_acquisition_events(z_start=0, z_end=10, z_step=0.25), keep_shutter_open=True)` did not run as sequenced acquisition either.

- Actually, there seems to be a general problem with sequenced acquisition in this version. Running `acq.acquire(multi_d_acquisition_events(z_start=0, z_end=10, z_step=0.25))` does not result in sequenced acquisition either.

- In micro-manager after an MDA acquisition the microscope is returned in the original state (in this example back to the first channel). In the acquisition above the microscope stayed in the configuration of the last image (i.e. last channel). That is fine, I'm just making a note of this difference.

Let me know if you'd like to troubleshoot together.

**Comment by henrypinkard** [comment]
Thanks for all the testing!

>     * You can pass `keep_shutter_open` argument in both the `events` list and the `acquire` function. Isn't this redundant? My understanding is that calling `acquire(events, keep_shutter_open=True)` will keep the shutter open during the entire acquisition (regardless of keys in `events`?). This could be accomplished by adding `keep_shutter_open` key to all events in the dictionary at construction

I think it makes sense to have some way of doing this with acquisition events, because it preserves the paradigm that you can fully specify an acquisition from the events alone, without having to make API calls. This leaves the possibility of doing cool stuff like being able to fully describe an acquisition in a text file.

The argument in the `acquire` function is redundant--its just a convenience to set this field in the events 

>     * Right now there is no easy way to construct events for multichannel acquisition where the shutter is kept open between z slices, but closed between channels. `multi_d_acquisition_events` does not currently take a `keep_shutter_open` argument. You may consider adding `keep_shutter_open_between_slices` and `keep_shutter_open_between_channels` as in the micro-manager MDA window

Good idea. Added. https://github.com/micro-manager/pycro-manager/pull/134

> ```
> z_stage = mmc.get_focus_device()
> mmc.set_property(z_stage,'UseSequence','Yes')
> 
> events = []
> for ch in channels:
>     for idx, z_um in enumerate(np.arange(start=0, stop=10, step=0.25)):
>         events.append({'axes': {'z': idx},
>                        'z': z_um,
>                        'channel': {'group': 'Cube', 'config': ch},
>                        'keep_shutter_open': True})
>     events.append({'keep_shutter_open': False})
> ```
> 
> The shutter behaved as expected. However, the microscope did not run a sequenced acquisition. Running a single z-stack as `acq.acquire(multi_d_acquisition_events(z_start=0, z_end=10, z_step=0.25), keep_shutter_open=True)` did not run as sequenced acquisition either.
> 
>     * Actually, there seems to be a general problem with sequenced acquisition in this version. Running `acq.acquire(multi_d_acquisition_events(z_start=0, z_end=10, z_step=0.25))` does not result in sequenced acquisition either.

Looks like there was a bug with sequencing z stacks. Doesn't seem new though. I guess you've not tried a sequenced z stack before?

**Comment by ieivanov** [comment]
> I think it makes sense to have some way of doing this with acquisition events, because it preserves the paradigm that you can fully specify an acquisition from the events alone, without having to make API calls. This leaves the possibility of doing cool stuff like being able to fully describe an acquisition in a text file.
> 
> The argument in the `acquire` function is redundant--its just a convenience to set this field in the events

Right, I was suggesting keeping `keep_shutter_open` as a key in the events dictionary, but removing it from `acquire`.

> Looks like there was a bug with sequencing z stacks. Doesn't seem new though. I guess you've not tried a sequenced z stack before?

Hm, maybe I never tested that? 

A bit off topic: it would be great to have tests that check that acquisitions run as expected after the code has been modified. I'm sure you've already thought of that - do you know how it can be accomplished? It's relatively straightforward for software projects, but it gets a bit tricky once you have hardware involved too.

**Comment by henrypinkard** [comment]
> > I think it makes sense to have some way of doing this with acquisition events, because it preserves the paradigm that you can fully specify an acquisition from the events alone, without having to make API calls. This leaves the possibility of doing cool stuff like being able to fully describe an acquisition in a text file.
> > The argument in the `acquire` function is redundant--its just a convenience to set this field in the events
> 
> Right, I was suggesting keeping `keep_shutter_open` as a key in the events dictionary, but removing it from `acquire`.

Oh the other thing i forgot is that you have to pass an event at the end of a `keep_shutter_open` series with `keep_shutter_open=False`. Using the argument with acquire will do it for you, which I think can be a bit more convenient. What do you think?

> > Looks like there was a bug with sequencing z stacks. Doesn't seem new though. I guess you've not tried a sequenced z stack before?
> 
> Hm, maybe I never tested that?
> 
> A bit off topic: it would be great to have tests that check that acquisitions run as expected after the code has been modified. I'm sure you've already thought of that - do you know how it can be accomplished? It's relatively straightforward for software projects, but it gets a bit tricky once you have hardware involved too.

Yeah I'm not sure. It would definitely be possible to automate tests for the low level stuff in the bridge--basic tests of java python communication. But as you said, hardware gets tricky. There are also a lot of places where things can go wrong. It would be nice though considering I keep breaking basic functionality :)

**Comment by ieivanov** [comment]
Sorry I didn't get to respond earlier.

>Oh the other thing i forgot is that you have to pass an event at the end of a keep_shutter_open series with keep_shutter_open=False. Using the argument with acquire will do it for you, which I think can be a bit more convenient. What do you think?

I think this gets back to the issue of returning the microscope to its original state after an acquisition. Currently, the MM MDA return the microscope to its state at the beginning of the acquisition, while `pycro-manager` leaves it at its state at the end of the acquisition. 

For example, if the shutter is open when `acquire` is called, we shouldn't close it at the end of the acquisition. Or if the shutter was closed at the start, we should either 1) close it when the acquisition is finished or 2) expect that the user will do their own cleanup (close the shutter, reset the stages, etc) at the end. 

Maybe `acquire` can take an argument of the sort `return_to_original_state=False`? Because I'm sure you wouldn't want to reset after every time `acquire` is called. Or can we have an API call that captures the state of the microscope such that we can bring it back there at some point later?

>Yeah I'm not sure. It would definitely be possible to automate tests for the low level stuff in the bridge--basic tests of java python communication. But as you said, hardware gets tricky. There are also a lot of places where things can go wrong. It would be nice though considering I keep breaking basic functionality :)

I agree. Tho we may be able to set up a very simple rig that uses the TTL output of a camera to report that images were taken, the encoder of a motor to report that the stage moves as expected, and maybe a servo to emulate channel switching. This will be a bit of work though. Do the demo camera and stage report that they've performed certain actions?

**Comment by henrypinkard** [comment]
> I think this gets back to the issue of returning the microscope to its original state after an acquisition. Currently, the MM MDA return the microscope to its state at the beginning of the acquisition, while `pycro-manager` leaves it at its state at the end of the acquisition.
> 
> For example, if the shutter is open when `acquire` is called, we shouldn't close it at the end of the acquisition. Or if the shutter was closed at the start, we should either 1) close it when the acquisition is finished or 2) expect that the user will do their own cleanup (close the shutter, reset the stages, etc) at the end.
> 
> Maybe `acquire` can take an argument of the sort `return_to_original_state=False`? Because I'm sure you wouldn't want to reset after every time `acquire` is called. Or can we have an API call that captures the state of the microscope such that we can bring it back there at some point later?

I think `return_to_original_state` option is a good idea. I opened an issue for it (https://github.com/micro-manager/pycro-manager/issues/144). But I dont think this totally addresses the `keep_shutter_open=False` thing, because you would be calling at the end of every series of events with the shutter open (e.g. end of every Z-stack). So we agree that it'll remain as an acquisition event in to make the full acquisition instructions serializable, but my preference is to have the redundant mechanism on top of that to have `acq.acquire(keep_shutter_open=True)`, because it think it can make for more readable code, like:

```
acq.acquire(events1, keep_shutter_open=True)
acq.acquire(events12 keep_shutter_open=False)
acq.acquire(events3, keep_shutter_open=True)
```

> > Yeah I'm not sure. It would definitely be possible to automate tests for the low level stuff in the bridge--basic tests of java python communication. But as you said, hardware gets tricky. There are also a lot of places where things can go wrong. It would be nice though considering I keep breaking basic functionality :)
> 
> I agree. Tho we may be able to set up a very simple rig that uses the TTL output of a camera to report that images were taken, the encoder of a motor to report that the stage moves as expected, and maybe a servo to emulate channel switching. This will be a bit of work though. Do the demo camera and stage report that they've performed certain actions?

Love this idea. I think the demo camera and stage can report to the core log on debug mode, but this seems like a brittle thing to rely on for testing

**Comment by ieivanov** [comment]
> I think `return_to_original_state` option is a good idea. I opened an issue for it (#144). But I dont think this totally addresses the `keep_shutter_open=False` thing, because you would be calling at the end of every series of events with the shutter open (e.g. end of every Z-stack). So we agree that it'll remain as an acquisition event in to make the full acquisition instructions serializable, but my preference is to have the redundant mechanism on top of that to have `acq.acquire(keep_shutter_open=True)`, because it think it can make for more readable code, like:
> 
> ```
> acq.acquire(events1, keep_shutter_open=True)
> acq.acquire(events12 keep_shutter_open=False)
> acq.acquire(events3, keep_shutter_open=True)
> ```

Ok, I'm convinced!

Let's close this issue and continue the discussion of `return_to_original_state` and hardware testing on separate threads?

**Comment by henrypinkard** [comment]
actually, one last thing. Should it maybe be named `autoshutter` instead of `keep_shutter_open`? I think this would probably more closely mirror the mm API, and I'm not sure there are any situations where you'd want autoshutter off but not want to have the shutter left open, so maybe this would be more clear

**Comment by ieivanov** [comment]
Hm, interesting. For collecting background images you'd sometimes want to collect images with the shutter closed.

Does pycromanager always open the shutter at the beginning of the acquisition currently? I'd say that if the shutter is closed and autoshutter is not enabled in the mm API, then pycromanager shouldn't open the shutter at the beginning of the acquisition.

I think `keep_shutter_open` and `autoshutter` imply different things. autoshutter should be something you set in the MM, while `keep_shutter_open` can be an option in pycromanager. If autoshutter is enabled, then pycromanager will open the shutter at the beginning of the acquisition and close it at the end. If `keep_shutter_open=False` when pycromanager will close the shutter between every acquisition event. If autoshutter is disabled, then pycromanager shouldn't mess with the shutter. A user can enable autoshutter using a core call before the acquisition and disable afterwards if needed.

What do you think?

**Comment by henrypinkard** [comment]
Yes I think you're right. Pycro-manager relies on whatever is set for autoshutter, except in the case of this flag.

When you call `keep_shutter_open=True`, autoshutter has to be disabled. Thus there is some ambiguity here as to when it whould be re-enabled. Usually, I think you'd want it to be re-enabled when you pass in `keep_shutter_open=False`, but maybe there are situations where you started with autoshutter off, want to collect some events with the shutter kept open in between, and then want to finish and close the shutter, but not have autoshutter turned back on. 

So I guess this solution here is as you say to have both `keep_shutter_open` and `autoshutter` fields in the acquisition events. And maybe this is another good reason to have `keep_shutter_open` as an argument for `acquire`, because this much more common case where you want to turn autoshutter back on at the end can be put in as a default.

**Comment by ieivanov** [comment]
I think having both `keep_shutter_open` and `autoshutter` fields in the acquisition events will be complicated. I think to simplify things, we should manage the `autoshutter` through the MM core, outside of pycromanager. A user can manually turn the shutter on/off and the autoshutter on/off by making calls to `mmc.setAutoShutter` and `mmc.setShutterOpen` between calls to `acquire` for complicated acquisition schemes. Do you see a problem with that?

In that case if:
* `mmc.getAutoShutter()=true` and `keep_shutter_open=True`
   pycromanager will open the shutter at the beginning of the acquisition, keep it open between frames, and close it at the end
* `mmc.getAutoShutter()=true` and `keep_shutter_open=False`
   pycromanager will open the shutter at the beginning of the acquisition, close it open between frames, and close it at the end
* `mmc.getAutoShutter()=false`
   pycromanager will not open the shutter at the beginning of the acquisition and will ignore the `keep_shutter_open` argument. The acquisition will proceed with the current state of the shutter (open or closed). The shutter will be left in that state at the end.

> but maybe there are situations where you started with autoshutter off, want to collect some events with the shutter kept open in between, and then want to finish and close the shutter, but not have autoshutter turned back on.

In that case:
```
mmc.set_auto_shutter(False)
mmc.set_shutter_open(True)

acquire(events) % pycromanager does not change the shutter state

mmc.set_shutter_open(False)
```

What do you think?

**Comment by henrypinkard** [comment]
Yes that all makes sense. Thanks for thinking through this. The one note I will add is that you're manually making calls to the core to control the shutter, it should be through an acquisition hook so that it doesnt run asynchronously with the acquisition
