### ISSUE TITLE
Acquisition with hook_fn and img_process_fn can freeze if the function is defined in Jupyter notebook on Windows systems

### ISSUE THREAD

**Issue by binli123** [micro-manager/pycro-manager#94]
If the acquisition uses hook_fn or img_process_fn function, the function has to be defined in a .py file and imported to the main notebook in order to run on a Windows machine. Otherwise the acquisition cell freezes. There is no issue if both the function and the acquisition are in a .py file and the file is executed directly in the terminal.

**Comment by henrypinkard** [comment]
Should be addressed by https://github.com/micro-manager/pycro-manager/issues/95

**Comment by henrypinkard** [comment]
Should be addressed by https://github.com/micro-manager/pycro-manager/issues/95

**Comment by henrypinkard** [comment]
Fixed by https://github.com/micro-manager/pycro-manager/pull/96

Available in pycromanager 0.4.5
